// Code generated by ent, DO NOT EDIT.

package depprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/thienel/go-backend-template/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLTE(FieldID, id))
}

// ProfileName applies equality check predicate on the "profile_name" field. It's identical to ProfileNameEQ.
func ProfileName(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldProfileName, v))
}

// ProfileUUID applies equality check predicate on the "profile_uuid" field. It's identical to ProfileUUIDEQ.
func ProfileUUID(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldProfileUUID, v))
}

// AllowPairing applies equality check predicate on the "allow_pairing" field. It's identical to AllowPairingEQ.
func AllowPairing(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldAllowPairing, v))
}

// AutoAdvanceSetup applies equality check predicate on the "auto_advance_setup" field. It's identical to AutoAdvanceSetupEQ.
func AutoAdvanceSetup(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldAutoAdvanceSetup, v))
}

// AwaitDeviceConfigured applies equality check predicate on the "await_device_configured" field. It's identical to AwaitDeviceConfiguredEQ.
func AwaitDeviceConfigured(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldAwaitDeviceConfigured, v))
}

// ConfigurationWebURL applies equality check predicate on the "configuration_web_url" field. It's identical to ConfigurationWebURLEQ.
func ConfigurationWebURL(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldConfigurationWebURL, v))
}

// Department applies equality check predicate on the "department" field. It's identical to DepartmentEQ.
func Department(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldDepartment, v))
}

// DoNotUseProfileFromBackup applies equality check predicate on the "do_not_use_profile_from_backup" field. It's identical to DoNotUseProfileFromBackupEQ.
func DoNotUseProfileFromBackup(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldDoNotUseProfileFromBackup, v))
}

// IsReturnToService applies equality check predicate on the "is_return_to_service" field. It's identical to IsReturnToServiceEQ.
func IsReturnToService(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldIsReturnToService, v))
}

// IsMandatory applies equality check predicate on the "is_mandatory" field. It's identical to IsMandatoryEQ.
func IsMandatory(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldIsMandatory, v))
}

// IsMdmRemovable applies equality check predicate on the "is_mdm_removable" field. It's identical to IsMdmRemovableEQ.
func IsMdmRemovable(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldIsMdmRemovable, v))
}

// IsMultiUser applies equality check predicate on the "is_multi_user" field. It's identical to IsMultiUserEQ.
func IsMultiUser(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldIsMultiUser, v))
}

// IsSupervised applies equality check predicate on the "is_supervised" field. It's identical to IsSupervisedEQ.
func IsSupervised(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldIsSupervised, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldLanguage, v))
}

// OrgMagic applies equality check predicate on the "org_magic" field. It's identical to OrgMagicEQ.
func OrgMagic(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldOrgMagic, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldRegion, v))
}

// SupportEmailAddress applies equality check predicate on the "support_email_address" field. It's identical to SupportEmailAddressEQ.
func SupportEmailAddress(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldSupportEmailAddress, v))
}

// SupportPhoneNumber applies equality check predicate on the "support_phone_number" field. It's identical to SupportPhoneNumberEQ.
func SupportPhoneNumber(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldSupportPhoneNumber, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldURL, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProfileNameEQ applies the EQ predicate on the "profile_name" field.
func ProfileNameEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldProfileName, v))
}

// ProfileNameNEQ applies the NEQ predicate on the "profile_name" field.
func ProfileNameNEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldProfileName, v))
}

// ProfileNameIn applies the In predicate on the "profile_name" field.
func ProfileNameIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIn(FieldProfileName, vs...))
}

// ProfileNameNotIn applies the NotIn predicate on the "profile_name" field.
func ProfileNameNotIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotIn(FieldProfileName, vs...))
}

// ProfileNameGT applies the GT predicate on the "profile_name" field.
func ProfileNameGT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGT(FieldProfileName, v))
}

// ProfileNameGTE applies the GTE predicate on the "profile_name" field.
func ProfileNameGTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGTE(FieldProfileName, v))
}

// ProfileNameLT applies the LT predicate on the "profile_name" field.
func ProfileNameLT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLT(FieldProfileName, v))
}

// ProfileNameLTE applies the LTE predicate on the "profile_name" field.
func ProfileNameLTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLTE(FieldProfileName, v))
}

// ProfileNameContains applies the Contains predicate on the "profile_name" field.
func ProfileNameContains(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContains(FieldProfileName, v))
}

// ProfileNameHasPrefix applies the HasPrefix predicate on the "profile_name" field.
func ProfileNameHasPrefix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasPrefix(FieldProfileName, v))
}

// ProfileNameHasSuffix applies the HasSuffix predicate on the "profile_name" field.
func ProfileNameHasSuffix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasSuffix(FieldProfileName, v))
}

// ProfileNameEqualFold applies the EqualFold predicate on the "profile_name" field.
func ProfileNameEqualFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEqualFold(FieldProfileName, v))
}

// ProfileNameContainsFold applies the ContainsFold predicate on the "profile_name" field.
func ProfileNameContainsFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContainsFold(FieldProfileName, v))
}

// ProfileUUIDEQ applies the EQ predicate on the "profile_uuid" field.
func ProfileUUIDEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldProfileUUID, v))
}

// ProfileUUIDNEQ applies the NEQ predicate on the "profile_uuid" field.
func ProfileUUIDNEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldProfileUUID, v))
}

// ProfileUUIDIn applies the In predicate on the "profile_uuid" field.
func ProfileUUIDIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIn(FieldProfileUUID, vs...))
}

// ProfileUUIDNotIn applies the NotIn predicate on the "profile_uuid" field.
func ProfileUUIDNotIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotIn(FieldProfileUUID, vs...))
}

// ProfileUUIDGT applies the GT predicate on the "profile_uuid" field.
func ProfileUUIDGT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGT(FieldProfileUUID, v))
}

// ProfileUUIDGTE applies the GTE predicate on the "profile_uuid" field.
func ProfileUUIDGTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGTE(FieldProfileUUID, v))
}

// ProfileUUIDLT applies the LT predicate on the "profile_uuid" field.
func ProfileUUIDLT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLT(FieldProfileUUID, v))
}

// ProfileUUIDLTE applies the LTE predicate on the "profile_uuid" field.
func ProfileUUIDLTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLTE(FieldProfileUUID, v))
}

// ProfileUUIDContains applies the Contains predicate on the "profile_uuid" field.
func ProfileUUIDContains(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContains(FieldProfileUUID, v))
}

// ProfileUUIDHasPrefix applies the HasPrefix predicate on the "profile_uuid" field.
func ProfileUUIDHasPrefix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasPrefix(FieldProfileUUID, v))
}

// ProfileUUIDHasSuffix applies the HasSuffix predicate on the "profile_uuid" field.
func ProfileUUIDHasSuffix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasSuffix(FieldProfileUUID, v))
}

// ProfileUUIDIsNil applies the IsNil predicate on the "profile_uuid" field.
func ProfileUUIDIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldProfileUUID))
}

// ProfileUUIDNotNil applies the NotNil predicate on the "profile_uuid" field.
func ProfileUUIDNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldProfileUUID))
}

// ProfileUUIDEqualFold applies the EqualFold predicate on the "profile_uuid" field.
func ProfileUUIDEqualFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEqualFold(FieldProfileUUID, v))
}

// ProfileUUIDContainsFold applies the ContainsFold predicate on the "profile_uuid" field.
func ProfileUUIDContainsFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContainsFold(FieldProfileUUID, v))
}

// AllowPairingEQ applies the EQ predicate on the "allow_pairing" field.
func AllowPairingEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldAllowPairing, v))
}

// AllowPairingNEQ applies the NEQ predicate on the "allow_pairing" field.
func AllowPairingNEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldAllowPairing, v))
}

// AnchorCertsIsNil applies the IsNil predicate on the "anchor_certs" field.
func AnchorCertsIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldAnchorCerts))
}

// AnchorCertsNotNil applies the NotNil predicate on the "anchor_certs" field.
func AnchorCertsNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldAnchorCerts))
}

// AutoAdvanceSetupEQ applies the EQ predicate on the "auto_advance_setup" field.
func AutoAdvanceSetupEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldAutoAdvanceSetup, v))
}

// AutoAdvanceSetupNEQ applies the NEQ predicate on the "auto_advance_setup" field.
func AutoAdvanceSetupNEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldAutoAdvanceSetup, v))
}

// AwaitDeviceConfiguredEQ applies the EQ predicate on the "await_device_configured" field.
func AwaitDeviceConfiguredEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldAwaitDeviceConfigured, v))
}

// AwaitDeviceConfiguredNEQ applies the NEQ predicate on the "await_device_configured" field.
func AwaitDeviceConfiguredNEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldAwaitDeviceConfigured, v))
}

// ConfigurationWebURLEQ applies the EQ predicate on the "configuration_web_url" field.
func ConfigurationWebURLEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldConfigurationWebURL, v))
}

// ConfigurationWebURLNEQ applies the NEQ predicate on the "configuration_web_url" field.
func ConfigurationWebURLNEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldConfigurationWebURL, v))
}

// ConfigurationWebURLIn applies the In predicate on the "configuration_web_url" field.
func ConfigurationWebURLIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIn(FieldConfigurationWebURL, vs...))
}

// ConfigurationWebURLNotIn applies the NotIn predicate on the "configuration_web_url" field.
func ConfigurationWebURLNotIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotIn(FieldConfigurationWebURL, vs...))
}

// ConfigurationWebURLGT applies the GT predicate on the "configuration_web_url" field.
func ConfigurationWebURLGT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGT(FieldConfigurationWebURL, v))
}

// ConfigurationWebURLGTE applies the GTE predicate on the "configuration_web_url" field.
func ConfigurationWebURLGTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGTE(FieldConfigurationWebURL, v))
}

// ConfigurationWebURLLT applies the LT predicate on the "configuration_web_url" field.
func ConfigurationWebURLLT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLT(FieldConfigurationWebURL, v))
}

// ConfigurationWebURLLTE applies the LTE predicate on the "configuration_web_url" field.
func ConfigurationWebURLLTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLTE(FieldConfigurationWebURL, v))
}

// ConfigurationWebURLContains applies the Contains predicate on the "configuration_web_url" field.
func ConfigurationWebURLContains(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContains(FieldConfigurationWebURL, v))
}

// ConfigurationWebURLHasPrefix applies the HasPrefix predicate on the "configuration_web_url" field.
func ConfigurationWebURLHasPrefix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasPrefix(FieldConfigurationWebURL, v))
}

// ConfigurationWebURLHasSuffix applies the HasSuffix predicate on the "configuration_web_url" field.
func ConfigurationWebURLHasSuffix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasSuffix(FieldConfigurationWebURL, v))
}

// ConfigurationWebURLIsNil applies the IsNil predicate on the "configuration_web_url" field.
func ConfigurationWebURLIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldConfigurationWebURL))
}

// ConfigurationWebURLNotNil applies the NotNil predicate on the "configuration_web_url" field.
func ConfigurationWebURLNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldConfigurationWebURL))
}

// ConfigurationWebURLEqualFold applies the EqualFold predicate on the "configuration_web_url" field.
func ConfigurationWebURLEqualFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEqualFold(FieldConfigurationWebURL, v))
}

// ConfigurationWebURLContainsFold applies the ContainsFold predicate on the "configuration_web_url" field.
func ConfigurationWebURLContainsFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContainsFold(FieldConfigurationWebURL, v))
}

// DepartmentEQ applies the EQ predicate on the "department" field.
func DepartmentEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldDepartment, v))
}

// DepartmentNEQ applies the NEQ predicate on the "department" field.
func DepartmentNEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldDepartment, v))
}

// DepartmentIn applies the In predicate on the "department" field.
func DepartmentIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIn(FieldDepartment, vs...))
}

// DepartmentNotIn applies the NotIn predicate on the "department" field.
func DepartmentNotIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotIn(FieldDepartment, vs...))
}

// DepartmentGT applies the GT predicate on the "department" field.
func DepartmentGT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGT(FieldDepartment, v))
}

// DepartmentGTE applies the GTE predicate on the "department" field.
func DepartmentGTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGTE(FieldDepartment, v))
}

// DepartmentLT applies the LT predicate on the "department" field.
func DepartmentLT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLT(FieldDepartment, v))
}

// DepartmentLTE applies the LTE predicate on the "department" field.
func DepartmentLTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLTE(FieldDepartment, v))
}

// DepartmentContains applies the Contains predicate on the "department" field.
func DepartmentContains(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContains(FieldDepartment, v))
}

// DepartmentHasPrefix applies the HasPrefix predicate on the "department" field.
func DepartmentHasPrefix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasPrefix(FieldDepartment, v))
}

// DepartmentHasSuffix applies the HasSuffix predicate on the "department" field.
func DepartmentHasSuffix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasSuffix(FieldDepartment, v))
}

// DepartmentIsNil applies the IsNil predicate on the "department" field.
func DepartmentIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldDepartment))
}

// DepartmentNotNil applies the NotNil predicate on the "department" field.
func DepartmentNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldDepartment))
}

// DepartmentEqualFold applies the EqualFold predicate on the "department" field.
func DepartmentEqualFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEqualFold(FieldDepartment, v))
}

// DepartmentContainsFold applies the ContainsFold predicate on the "department" field.
func DepartmentContainsFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContainsFold(FieldDepartment, v))
}

// DevicesIsNil applies the IsNil predicate on the "devices" field.
func DevicesIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldDevices))
}

// DevicesNotNil applies the NotNil predicate on the "devices" field.
func DevicesNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldDevices))
}

// DoNotUseProfileFromBackupEQ applies the EQ predicate on the "do_not_use_profile_from_backup" field.
func DoNotUseProfileFromBackupEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldDoNotUseProfileFromBackup, v))
}

// DoNotUseProfileFromBackupNEQ applies the NEQ predicate on the "do_not_use_profile_from_backup" field.
func DoNotUseProfileFromBackupNEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldDoNotUseProfileFromBackup, v))
}

// IsReturnToServiceEQ applies the EQ predicate on the "is_return_to_service" field.
func IsReturnToServiceEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldIsReturnToService, v))
}

// IsReturnToServiceNEQ applies the NEQ predicate on the "is_return_to_service" field.
func IsReturnToServiceNEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldIsReturnToService, v))
}

// IsMandatoryEQ applies the EQ predicate on the "is_mandatory" field.
func IsMandatoryEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldIsMandatory, v))
}

// IsMandatoryNEQ applies the NEQ predicate on the "is_mandatory" field.
func IsMandatoryNEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldIsMandatory, v))
}

// IsMdmRemovableEQ applies the EQ predicate on the "is_mdm_removable" field.
func IsMdmRemovableEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldIsMdmRemovable, v))
}

// IsMdmRemovableNEQ applies the NEQ predicate on the "is_mdm_removable" field.
func IsMdmRemovableNEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldIsMdmRemovable, v))
}

// IsMultiUserEQ applies the EQ predicate on the "is_multi_user" field.
func IsMultiUserEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldIsMultiUser, v))
}

// IsMultiUserNEQ applies the NEQ predicate on the "is_multi_user" field.
func IsMultiUserNEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldIsMultiUser, v))
}

// IsSupervisedEQ applies the EQ predicate on the "is_supervised" field.
func IsSupervisedEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldIsSupervised, v))
}

// IsSupervisedNEQ applies the NEQ predicate on the "is_supervised" field.
func IsSupervisedNEQ(v bool) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldIsSupervised, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageIsNil applies the IsNil predicate on the "language" field.
func LanguageIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldLanguage))
}

// LanguageNotNil applies the NotNil predicate on the "language" field.
func LanguageNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldLanguage))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContainsFold(FieldLanguage, v))
}

// OrgMagicEQ applies the EQ predicate on the "org_magic" field.
func OrgMagicEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldOrgMagic, v))
}

// OrgMagicNEQ applies the NEQ predicate on the "org_magic" field.
func OrgMagicNEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldOrgMagic, v))
}

// OrgMagicIn applies the In predicate on the "org_magic" field.
func OrgMagicIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIn(FieldOrgMagic, vs...))
}

// OrgMagicNotIn applies the NotIn predicate on the "org_magic" field.
func OrgMagicNotIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotIn(FieldOrgMagic, vs...))
}

// OrgMagicGT applies the GT predicate on the "org_magic" field.
func OrgMagicGT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGT(FieldOrgMagic, v))
}

// OrgMagicGTE applies the GTE predicate on the "org_magic" field.
func OrgMagicGTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGTE(FieldOrgMagic, v))
}

// OrgMagicLT applies the LT predicate on the "org_magic" field.
func OrgMagicLT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLT(FieldOrgMagic, v))
}

// OrgMagicLTE applies the LTE predicate on the "org_magic" field.
func OrgMagicLTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLTE(FieldOrgMagic, v))
}

// OrgMagicContains applies the Contains predicate on the "org_magic" field.
func OrgMagicContains(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContains(FieldOrgMagic, v))
}

// OrgMagicHasPrefix applies the HasPrefix predicate on the "org_magic" field.
func OrgMagicHasPrefix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasPrefix(FieldOrgMagic, v))
}

// OrgMagicHasSuffix applies the HasSuffix predicate on the "org_magic" field.
func OrgMagicHasSuffix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasSuffix(FieldOrgMagic, v))
}

// OrgMagicIsNil applies the IsNil predicate on the "org_magic" field.
func OrgMagicIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldOrgMagic))
}

// OrgMagicNotNil applies the NotNil predicate on the "org_magic" field.
func OrgMagicNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldOrgMagic))
}

// OrgMagicEqualFold applies the EqualFold predicate on the "org_magic" field.
func OrgMagicEqualFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEqualFold(FieldOrgMagic, v))
}

// OrgMagicContainsFold applies the ContainsFold predicate on the "org_magic" field.
func OrgMagicContainsFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContainsFold(FieldOrgMagic, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionIsNil applies the IsNil predicate on the "region" field.
func RegionIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldRegion))
}

// RegionNotNil applies the NotNil predicate on the "region" field.
func RegionNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldRegion))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContainsFold(FieldRegion, v))
}

// SkipSetupItemsIsNil applies the IsNil predicate on the "skip_setup_items" field.
func SkipSetupItemsIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldSkipSetupItems))
}

// SkipSetupItemsNotNil applies the NotNil predicate on the "skip_setup_items" field.
func SkipSetupItemsNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldSkipSetupItems))
}

// SupervisingHostCertsIsNil applies the IsNil predicate on the "supervising_host_certs" field.
func SupervisingHostCertsIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldSupervisingHostCerts))
}

// SupervisingHostCertsNotNil applies the NotNil predicate on the "supervising_host_certs" field.
func SupervisingHostCertsNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldSupervisingHostCerts))
}

// SupportEmailAddressEQ applies the EQ predicate on the "support_email_address" field.
func SupportEmailAddressEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldSupportEmailAddress, v))
}

// SupportEmailAddressNEQ applies the NEQ predicate on the "support_email_address" field.
func SupportEmailAddressNEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldSupportEmailAddress, v))
}

// SupportEmailAddressIn applies the In predicate on the "support_email_address" field.
func SupportEmailAddressIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIn(FieldSupportEmailAddress, vs...))
}

// SupportEmailAddressNotIn applies the NotIn predicate on the "support_email_address" field.
func SupportEmailAddressNotIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotIn(FieldSupportEmailAddress, vs...))
}

// SupportEmailAddressGT applies the GT predicate on the "support_email_address" field.
func SupportEmailAddressGT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGT(FieldSupportEmailAddress, v))
}

// SupportEmailAddressGTE applies the GTE predicate on the "support_email_address" field.
func SupportEmailAddressGTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGTE(FieldSupportEmailAddress, v))
}

// SupportEmailAddressLT applies the LT predicate on the "support_email_address" field.
func SupportEmailAddressLT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLT(FieldSupportEmailAddress, v))
}

// SupportEmailAddressLTE applies the LTE predicate on the "support_email_address" field.
func SupportEmailAddressLTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLTE(FieldSupportEmailAddress, v))
}

// SupportEmailAddressContains applies the Contains predicate on the "support_email_address" field.
func SupportEmailAddressContains(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContains(FieldSupportEmailAddress, v))
}

// SupportEmailAddressHasPrefix applies the HasPrefix predicate on the "support_email_address" field.
func SupportEmailAddressHasPrefix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasPrefix(FieldSupportEmailAddress, v))
}

// SupportEmailAddressHasSuffix applies the HasSuffix predicate on the "support_email_address" field.
func SupportEmailAddressHasSuffix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasSuffix(FieldSupportEmailAddress, v))
}

// SupportEmailAddressIsNil applies the IsNil predicate on the "support_email_address" field.
func SupportEmailAddressIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldSupportEmailAddress))
}

// SupportEmailAddressNotNil applies the NotNil predicate on the "support_email_address" field.
func SupportEmailAddressNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldSupportEmailAddress))
}

// SupportEmailAddressEqualFold applies the EqualFold predicate on the "support_email_address" field.
func SupportEmailAddressEqualFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEqualFold(FieldSupportEmailAddress, v))
}

// SupportEmailAddressContainsFold applies the ContainsFold predicate on the "support_email_address" field.
func SupportEmailAddressContainsFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContainsFold(FieldSupportEmailAddress, v))
}

// SupportPhoneNumberEQ applies the EQ predicate on the "support_phone_number" field.
func SupportPhoneNumberEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldSupportPhoneNumber, v))
}

// SupportPhoneNumberNEQ applies the NEQ predicate on the "support_phone_number" field.
func SupportPhoneNumberNEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldSupportPhoneNumber, v))
}

// SupportPhoneNumberIn applies the In predicate on the "support_phone_number" field.
func SupportPhoneNumberIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIn(FieldSupportPhoneNumber, vs...))
}

// SupportPhoneNumberNotIn applies the NotIn predicate on the "support_phone_number" field.
func SupportPhoneNumberNotIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotIn(FieldSupportPhoneNumber, vs...))
}

// SupportPhoneNumberGT applies the GT predicate on the "support_phone_number" field.
func SupportPhoneNumberGT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGT(FieldSupportPhoneNumber, v))
}

// SupportPhoneNumberGTE applies the GTE predicate on the "support_phone_number" field.
func SupportPhoneNumberGTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGTE(FieldSupportPhoneNumber, v))
}

// SupportPhoneNumberLT applies the LT predicate on the "support_phone_number" field.
func SupportPhoneNumberLT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLT(FieldSupportPhoneNumber, v))
}

// SupportPhoneNumberLTE applies the LTE predicate on the "support_phone_number" field.
func SupportPhoneNumberLTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLTE(FieldSupportPhoneNumber, v))
}

// SupportPhoneNumberContains applies the Contains predicate on the "support_phone_number" field.
func SupportPhoneNumberContains(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContains(FieldSupportPhoneNumber, v))
}

// SupportPhoneNumberHasPrefix applies the HasPrefix predicate on the "support_phone_number" field.
func SupportPhoneNumberHasPrefix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasPrefix(FieldSupportPhoneNumber, v))
}

// SupportPhoneNumberHasSuffix applies the HasSuffix predicate on the "support_phone_number" field.
func SupportPhoneNumberHasSuffix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasSuffix(FieldSupportPhoneNumber, v))
}

// SupportPhoneNumberIsNil applies the IsNil predicate on the "support_phone_number" field.
func SupportPhoneNumberIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldSupportPhoneNumber))
}

// SupportPhoneNumberNotNil applies the NotNil predicate on the "support_phone_number" field.
func SupportPhoneNumberNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldSupportPhoneNumber))
}

// SupportPhoneNumberEqualFold applies the EqualFold predicate on the "support_phone_number" field.
func SupportPhoneNumberEqualFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEqualFold(FieldSupportPhoneNumber, v))
}

// SupportPhoneNumberContainsFold applies the ContainsFold predicate on the "support_phone_number" field.
func SupportPhoneNumberContainsFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContainsFold(FieldSupportPhoneNumber, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldContainsFold(FieldURL, v))
}

// ProfileDataIsNil applies the IsNil predicate on the "profile_data" field.
func ProfileDataIsNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIsNull(FieldProfileData))
}

// ProfileDataNotNil applies the NotNil predicate on the "profile_data" field.
func ProfileDataNotNil() predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotNull(FieldProfileData))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DepProfile {
	return predicate.DepProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DepProfile) predicate.DepProfile {
	return predicate.DepProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DepProfile) predicate.DepProfile {
	return predicate.DepProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DepProfile) predicate.DepProfile {
	return predicate.DepProfile(sql.NotPredicates(p))
}
