// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thienel/go-backend-template/internal/ent/apnsconfig"
)

// APNSConfigCreate is the builder for creating a APNSConfig entity.
type APNSConfigCreate struct {
	config
	mutation *APNSConfigMutation
	hooks    []Hook
}

// SetTopic sets the "topic" field.
func (_c *APNSConfigCreate) SetTopic(v string) *APNSConfigCreate {
	_c.mutation.SetTopic(v)
	return _c
}

// SetCertFilePath sets the "cert_file_path" field.
func (_c *APNSConfigCreate) SetCertFilePath(v string) *APNSConfigCreate {
	_c.mutation.SetCertFilePath(v)
	return _c
}

// SetKeyFilePath sets the "key_file_path" field.
func (_c *APNSConfigCreate) SetKeyFilePath(v string) *APNSConfigCreate {
	_c.mutation.SetKeyFilePath(v)
	return _c
}

// SetExpiry sets the "expiry" field.
func (_c *APNSConfigCreate) SetExpiry(v time.Time) *APNSConfigCreate {
	_c.mutation.SetExpiry(v)
	return _c
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (_c *APNSConfigCreate) SetNillableExpiry(v *time.Time) *APNSConfigCreate {
	if v != nil {
		_c.SetExpiry(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *APNSConfigCreate) SetCreatedAt(v time.Time) *APNSConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APNSConfigCreate) SetNillableCreatedAt(v *time.Time) *APNSConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *APNSConfigCreate) SetUpdatedAt(v time.Time) *APNSConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *APNSConfigCreate) SetNillableUpdatedAt(v *time.Time) *APNSConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *APNSConfigCreate) SetID(v uint) *APNSConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the APNSConfigMutation object of the builder.
func (_c *APNSConfigCreate) Mutation() *APNSConfigMutation {
	return _c.mutation
}

// Save creates the APNSConfig in the database.
func (_c *APNSConfigCreate) Save(ctx context.Context) (*APNSConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APNSConfigCreate) SaveX(ctx context.Context) *APNSConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APNSConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APNSConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APNSConfigCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apnsconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apnsconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APNSConfigCreate) check() error {
	if _, ok := _c.mutation.Topic(); !ok {
		return &ValidationError{Name: "topic", err: errors.New(`ent: missing required field "APNSConfig.topic"`)}
	}
	if v, ok := _c.mutation.Topic(); ok {
		if err := apnsconfig.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "APNSConfig.topic": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CertFilePath(); !ok {
		return &ValidationError{Name: "cert_file_path", err: errors.New(`ent: missing required field "APNSConfig.cert_file_path"`)}
	}
	if v, ok := _c.mutation.CertFilePath(); ok {
		if err := apnsconfig.CertFilePathValidator(v); err != nil {
			return &ValidationError{Name: "cert_file_path", err: fmt.Errorf(`ent: validator failed for field "APNSConfig.cert_file_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyFilePath(); !ok {
		return &ValidationError{Name: "key_file_path", err: errors.New(`ent: missing required field "APNSConfig.key_file_path"`)}
	}
	if v, ok := _c.mutation.KeyFilePath(); ok {
		if err := apnsconfig.KeyFilePathValidator(v); err != nil {
			return &ValidationError{Name: "key_file_path", err: fmt.Errorf(`ent: validator failed for field "APNSConfig.key_file_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "APNSConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "APNSConfig.updated_at"`)}
	}
	return nil
}

func (_c *APNSConfigCreate) sqlSave(ctx context.Context) (*APNSConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APNSConfigCreate) createSpec() (*APNSConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &APNSConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apnsconfig.Table, sqlgraph.NewFieldSpec(apnsconfig.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Topic(); ok {
		_spec.SetField(apnsconfig.FieldTopic, field.TypeString, value)
		_node.Topic = value
	}
	if value, ok := _c.mutation.CertFilePath(); ok {
		_spec.SetField(apnsconfig.FieldCertFilePath, field.TypeString, value)
		_node.CertFilePath = value
	}
	if value, ok := _c.mutation.KeyFilePath(); ok {
		_spec.SetField(apnsconfig.FieldKeyFilePath, field.TypeString, value)
		_node.KeyFilePath = value
	}
	if value, ok := _c.mutation.Expiry(); ok {
		_spec.SetField(apnsconfig.FieldExpiry, field.TypeTime, value)
		_node.Expiry = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apnsconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apnsconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// APNSConfigCreateBulk is the builder for creating many APNSConfig entities in bulk.
type APNSConfigCreateBulk struct {
	config
	err      error
	builders []*APNSConfigCreate
}

// Save creates the APNSConfig entities in the database.
func (_c *APNSConfigCreateBulk) Save(ctx context.Context) ([]*APNSConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APNSConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APNSConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APNSConfigCreateBulk) SaveX(ctx context.Context) []*APNSConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APNSConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APNSConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
