// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thienel/go-backend-template/internal/ent/appdeployment"
	"github.com/thienel/go-backend-template/internal/ent/application"
	"github.com/thienel/go-backend-template/internal/ent/appversion"
)

// AppVersionCreate is the builder for creating a AppVersion entity.
type AppVersionCreate struct {
	config
	mutation *AppVersionMutation
	hooks    []Hook
}

// SetApplicationID sets the "application_id" field.
func (_c *AppVersionCreate) SetApplicationID(v uint) *AppVersionCreate {
	_c.mutation.SetApplicationID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *AppVersionCreate) SetVersion(v string) *AppVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetBuildNumber sets the "build_number" field.
func (_c *AppVersionCreate) SetBuildNumber(v string) *AppVersionCreate {
	_c.mutation.SetBuildNumber(v)
	return _c
}

// SetMinimumOsVersion sets the "minimum_os_version" field.
func (_c *AppVersionCreate) SetMinimumOsVersion(v string) *AppVersionCreate {
	_c.mutation.SetMinimumOsVersion(v)
	return _c
}

// SetNillableMinimumOsVersion sets the "minimum_os_version" field if the given value is not nil.
func (_c *AppVersionCreate) SetNillableMinimumOsVersion(v *string) *AppVersionCreate {
	if v != nil {
		_c.SetMinimumOsVersion(*v)
	}
	return _c
}

// SetFileURL sets the "file_url" field.
func (_c *AppVersionCreate) SetFileURL(v string) *AppVersionCreate {
	_c.mutation.SetFileURL(v)
	return _c
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_c *AppVersionCreate) SetNillableFileURL(v *string) *AppVersionCreate {
	if v != nil {
		_c.SetFileURL(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *AppVersionCreate) SetSize(v int64) *AppVersionCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *AppVersionCreate) SetNillableSize(v *int64) *AppVersionCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *AppVersionCreate) SetMetadata(v map[string]interface{}) *AppVersionCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AppVersionCreate) SetCreatedAt(v time.Time) *AppVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AppVersionCreate) SetNillableCreatedAt(v *time.Time) *AppVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AppVersionCreate) SetUpdatedAt(v time.Time) *AppVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AppVersionCreate) SetNillableUpdatedAt(v *time.Time) *AppVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AppVersionCreate) SetID(v uint) *AppVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetApplication sets the "application" edge to the Application entity.
func (_c *AppVersionCreate) SetApplication(v *Application) *AppVersionCreate {
	return _c.SetApplicationID(v.ID)
}

// AddDeploymentIDs adds the "deployments" edge to the AppDeployment entity by IDs.
func (_c *AppVersionCreate) AddDeploymentIDs(ids ...uint) *AppVersionCreate {
	_c.mutation.AddDeploymentIDs(ids...)
	return _c
}

// AddDeployments adds the "deployments" edges to the AppDeployment entity.
func (_c *AppVersionCreate) AddDeployments(v ...*AppDeployment) *AppVersionCreate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDeploymentIDs(ids...)
}

// Mutation returns the AppVersionMutation object of the builder.
func (_c *AppVersionCreate) Mutation() *AppVersionMutation {
	return _c.mutation
}

// Save creates the AppVersion in the database.
func (_c *AppVersionCreate) Save(ctx context.Context) (*AppVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppVersionCreate) SaveX(ctx context.Context) *AppVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppVersionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := appversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := appversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppVersionCreate) check() error {
	if _, ok := _c.mutation.ApplicationID(); !ok {
		return &ValidationError{Name: "application_id", err: errors.New(`ent: missing required field "AppVersion.application_id"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "AppVersion.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := appversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "AppVersion.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BuildNumber(); !ok {
		return &ValidationError{Name: "build_number", err: errors.New(`ent: missing required field "AppVersion.build_number"`)}
	}
	if v, ok := _c.mutation.BuildNumber(); ok {
		if err := appversion.BuildNumberValidator(v); err != nil {
			return &ValidationError{Name: "build_number", err: fmt.Errorf(`ent: validator failed for field "AppVersion.build_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AppVersion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AppVersion.updated_at"`)}
	}
	if len(_c.mutation.ApplicationIDs()) == 0 {
		return &ValidationError{Name: "application", err: errors.New(`ent: missing required edge "AppVersion.application"`)}
	}
	return nil
}

func (_c *AppVersionCreate) sqlSave(ctx context.Context) (*AppVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppVersionCreate) createSpec() (*AppVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &AppVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(appversion.Table, sqlgraph.NewFieldSpec(appversion.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(appversion.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.BuildNumber(); ok {
		_spec.SetField(appversion.FieldBuildNumber, field.TypeString, value)
		_node.BuildNumber = value
	}
	if value, ok := _c.mutation.MinimumOsVersion(); ok {
		_spec.SetField(appversion.FieldMinimumOsVersion, field.TypeString, value)
		_node.MinimumOsVersion = value
	}
	if value, ok := _c.mutation.FileURL(); ok {
		_spec.SetField(appversion.FieldFileURL, field.TypeString, value)
		_node.FileURL = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(appversion.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(appversion.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(appversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(appversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appversion.ApplicationTable,
			Columns: []string{appversion.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ApplicationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeploymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   appversion.DeploymentsTable,
			Columns: []string{appversion.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(appdeployment.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AppVersionCreateBulk is the builder for creating many AppVersion entities in bulk.
type AppVersionCreateBulk struct {
	config
	err      error
	builders []*AppVersionCreate
}

// Save creates the AppVersion entities in the database.
func (_c *AppVersionCreateBulk) Save(ctx context.Context) ([]*AppVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AppVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppVersionCreateBulk) SaveX(ctx context.Context) []*AppVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
