// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/thienel/go-backend-template/internal/ent/depprofile"
)

// DepProfile is the model entity for the DepProfile schema.
type DepProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// ProfileName holds the value of the "profile_name" field.
	ProfileName string `json:"profile_name,omitempty"`
	// ProfileUUID holds the value of the "profile_uuid" field.
	ProfileUUID string `json:"profile_uuid,omitempty"`
	// AllowPairing holds the value of the "allow_pairing" field.
	AllowPairing bool `json:"allow_pairing,omitempty"`
	// AnchorCerts holds the value of the "anchor_certs" field.
	AnchorCerts []string `json:"anchor_certs,omitempty"`
	// AutoAdvanceSetup holds the value of the "auto_advance_setup" field.
	AutoAdvanceSetup bool `json:"auto_advance_setup,omitempty"`
	// AwaitDeviceConfigured holds the value of the "await_device_configured" field.
	AwaitDeviceConfigured bool `json:"await_device_configured,omitempty"`
	// ConfigurationWebURL holds the value of the "configuration_web_url" field.
	ConfigurationWebURL string `json:"configuration_web_url,omitempty"`
	// Department holds the value of the "department" field.
	Department string `json:"department,omitempty"`
	// Devices holds the value of the "devices" field.
	Devices []string `json:"devices,omitempty"`
	// DoNotUseProfileFromBackup holds the value of the "do_not_use_profile_from_backup" field.
	DoNotUseProfileFromBackup bool `json:"do_not_use_profile_from_backup,omitempty"`
	// IsReturnToService holds the value of the "is_return_to_service" field.
	IsReturnToService bool `json:"is_return_to_service,omitempty"`
	// IsMandatory holds the value of the "is_mandatory" field.
	IsMandatory bool `json:"is_mandatory,omitempty"`
	// IsMdmRemovable holds the value of the "is_mdm_removable" field.
	IsMdmRemovable bool `json:"is_mdm_removable,omitempty"`
	// IsMultiUser holds the value of the "is_multi_user" field.
	IsMultiUser bool `json:"is_multi_user,omitempty"`
	// IsSupervised holds the value of the "is_supervised" field.
	IsSupervised bool `json:"is_supervised,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// OrgMagic holds the value of the "org_magic" field.
	OrgMagic string `json:"org_magic,omitempty"`
	// Region holds the value of the "region" field.
	Region string `json:"region,omitempty"`
	// SkipSetupItems holds the value of the "skip_setup_items" field.
	SkipSetupItems []string `json:"skip_setup_items,omitempty"`
	// SupervisingHostCerts holds the value of the "supervising_host_certs" field.
	SupervisingHostCerts []string `json:"supervising_host_certs,omitempty"`
	// SupportEmailAddress holds the value of the "support_email_address" field.
	SupportEmailAddress string `json:"support_email_address,omitempty"`
	// SupportPhoneNumber holds the value of the "support_phone_number" field.
	SupportPhoneNumber string `json:"support_phone_number,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// ProfileData holds the value of the "profile_data" field.
	ProfileData map[string]any `json:"profile_data,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DepProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case depprofile.FieldAnchorCerts, depprofile.FieldDevices, depprofile.FieldSkipSetupItems, depprofile.FieldSupervisingHostCerts, depprofile.FieldProfileData:
			values[i] = new([]byte)
		case depprofile.FieldAllowPairing, depprofile.FieldAutoAdvanceSetup, depprofile.FieldAwaitDeviceConfigured, depprofile.FieldDoNotUseProfileFromBackup, depprofile.FieldIsReturnToService, depprofile.FieldIsMandatory, depprofile.FieldIsMdmRemovable, depprofile.FieldIsMultiUser, depprofile.FieldIsSupervised:
			values[i] = new(sql.NullBool)
		case depprofile.FieldID:
			values[i] = new(sql.NullInt64)
		case depprofile.FieldProfileName, depprofile.FieldProfileUUID, depprofile.FieldConfigurationWebURL, depprofile.FieldDepartment, depprofile.FieldLanguage, depprofile.FieldOrgMagic, depprofile.FieldRegion, depprofile.FieldSupportEmailAddress, depprofile.FieldSupportPhoneNumber, depprofile.FieldURL:
			values[i] = new(sql.NullString)
		case depprofile.FieldCreatedAt, depprofile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DepProfile fields.
func (_m *DepProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case depprofile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case depprofile.FieldProfileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_name", values[i])
			} else if value.Valid {
				_m.ProfileName = value.String
			}
		case depprofile.FieldProfileUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_uuid", values[i])
			} else if value.Valid {
				_m.ProfileUUID = value.String
			}
		case depprofile.FieldAllowPairing:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_pairing", values[i])
			} else if value.Valid {
				_m.AllowPairing = value.Bool
			}
		case depprofile.FieldAnchorCerts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field anchor_certs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AnchorCerts); err != nil {
					return fmt.Errorf("unmarshal field anchor_certs: %w", err)
				}
			}
		case depprofile.FieldAutoAdvanceSetup:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_advance_setup", values[i])
			} else if value.Valid {
				_m.AutoAdvanceSetup = value.Bool
			}
		case depprofile.FieldAwaitDeviceConfigured:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field await_device_configured", values[i])
			} else if value.Valid {
				_m.AwaitDeviceConfigured = value.Bool
			}
		case depprofile.FieldConfigurationWebURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field configuration_web_url", values[i])
			} else if value.Valid {
				_m.ConfigurationWebURL = value.String
			}
		case depprofile.FieldDepartment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field department", values[i])
			} else if value.Valid {
				_m.Department = value.String
			}
		case depprofile.FieldDevices:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field devices", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Devices); err != nil {
					return fmt.Errorf("unmarshal field devices: %w", err)
				}
			}
		case depprofile.FieldDoNotUseProfileFromBackup:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field do_not_use_profile_from_backup", values[i])
			} else if value.Valid {
				_m.DoNotUseProfileFromBackup = value.Bool
			}
		case depprofile.FieldIsReturnToService:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_return_to_service", values[i])
			} else if value.Valid {
				_m.IsReturnToService = value.Bool
			}
		case depprofile.FieldIsMandatory:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_mandatory", values[i])
			} else if value.Valid {
				_m.IsMandatory = value.Bool
			}
		case depprofile.FieldIsMdmRemovable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_mdm_removable", values[i])
			} else if value.Valid {
				_m.IsMdmRemovable = value.Bool
			}
		case depprofile.FieldIsMultiUser:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_multi_user", values[i])
			} else if value.Valid {
				_m.IsMultiUser = value.Bool
			}
		case depprofile.FieldIsSupervised:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_supervised", values[i])
			} else if value.Valid {
				_m.IsSupervised = value.Bool
			}
		case depprofile.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case depprofile.FieldOrgMagic:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field org_magic", values[i])
			} else if value.Valid {
				_m.OrgMagic = value.String
			}
		case depprofile.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case depprofile.FieldSkipSetupItems:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field skip_setup_items", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SkipSetupItems); err != nil {
					return fmt.Errorf("unmarshal field skip_setup_items: %w", err)
				}
			}
		case depprofile.FieldSupervisingHostCerts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field supervising_host_certs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SupervisingHostCerts); err != nil {
					return fmt.Errorf("unmarshal field supervising_host_certs: %w", err)
				}
			}
		case depprofile.FieldSupportEmailAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field support_email_address", values[i])
			} else if value.Valid {
				_m.SupportEmailAddress = value.String
			}
		case depprofile.FieldSupportPhoneNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field support_phone_number", values[i])
			} else if value.Valid {
				_m.SupportPhoneNumber = value.String
			}
		case depprofile.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case depprofile.FieldProfileData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field profile_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ProfileData); err != nil {
					return fmt.Errorf("unmarshal field profile_data: %w", err)
				}
			}
		case depprofile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case depprofile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DepProfile.
// This includes values selected through modifiers, order, etc.
func (_m *DepProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DepProfile.
// Note that you need to call DepProfile.Unwrap() before calling this method if this DepProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DepProfile) Update() *DepProfileUpdateOne {
	return NewDepProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DepProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DepProfile) Unwrap() *DepProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DepProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DepProfile) String() string {
	var builder strings.Builder
	builder.WriteString("DepProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("profile_name=")
	builder.WriteString(_m.ProfileName)
	builder.WriteString(", ")
	builder.WriteString("profile_uuid=")
	builder.WriteString(_m.ProfileUUID)
	builder.WriteString(", ")
	builder.WriteString("allow_pairing=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowPairing))
	builder.WriteString(", ")
	builder.WriteString("anchor_certs=")
	builder.WriteString(fmt.Sprintf("%v", _m.AnchorCerts))
	builder.WriteString(", ")
	builder.WriteString("auto_advance_setup=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoAdvanceSetup))
	builder.WriteString(", ")
	builder.WriteString("await_device_configured=")
	builder.WriteString(fmt.Sprintf("%v", _m.AwaitDeviceConfigured))
	builder.WriteString(", ")
	builder.WriteString("configuration_web_url=")
	builder.WriteString(_m.ConfigurationWebURL)
	builder.WriteString(", ")
	builder.WriteString("department=")
	builder.WriteString(_m.Department)
	builder.WriteString(", ")
	builder.WriteString("devices=")
	builder.WriteString(fmt.Sprintf("%v", _m.Devices))
	builder.WriteString(", ")
	builder.WriteString("do_not_use_profile_from_backup=")
	builder.WriteString(fmt.Sprintf("%v", _m.DoNotUseProfileFromBackup))
	builder.WriteString(", ")
	builder.WriteString("is_return_to_service=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsReturnToService))
	builder.WriteString(", ")
	builder.WriteString("is_mandatory=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsMandatory))
	builder.WriteString(", ")
	builder.WriteString("is_mdm_removable=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsMdmRemovable))
	builder.WriteString(", ")
	builder.WriteString("is_multi_user=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsMultiUser))
	builder.WriteString(", ")
	builder.WriteString("is_supervised=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSupervised))
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	builder.WriteString("org_magic=")
	builder.WriteString(_m.OrgMagic)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("skip_setup_items=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkipSetupItems))
	builder.WriteString(", ")
	builder.WriteString("supervising_host_certs=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupervisingHostCerts))
	builder.WriteString(", ")
	builder.WriteString("support_email_address=")
	builder.WriteString(_m.SupportEmailAddress)
	builder.WriteString(", ")
	builder.WriteString("support_phone_number=")
	builder.WriteString(_m.SupportPhoneNumber)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("profile_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProfileData))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DepProfiles is a parsable slice of DepProfile.
type DepProfiles []*DepProfile
