// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thienel/go-backend-template/internal/ent/device"
	"github.com/thienel/go-backend-template/internal/ent/predicate"
	"github.com/thienel/go-backend-template/internal/ent/user"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSerialNumber sets the "serial_number" field.
func (_u *DeviceUpdate) SetSerialNumber(v string) *DeviceUpdate {
	_u.mutation.SetSerialNumber(v)
	return _u
}

// SetNillableSerialNumber sets the "serial_number" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableSerialNumber(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetSerialNumber(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *DeviceUpdate) SetModel(v string) *DeviceUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableModel(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *DeviceUpdate) SetOwnerID(v uint) *DeviceUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableOwnerID(v *uint) *DeviceUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *DeviceUpdate) ClearOwnerID() *DeviceUpdate {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetIsEnrolled sets the "is_enrolled" field.
func (_u *DeviceUpdate) SetIsEnrolled(v bool) *DeviceUpdate {
	_u.mutation.SetIsEnrolled(v)
	return _u
}

// SetNillableIsEnrolled sets the "is_enrolled" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableIsEnrolled(v *bool) *DeviceUpdate {
	if v != nil {
		_u.SetIsEnrolled(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeviceUpdate) SetName(v string) *DeviceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableName(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *DeviceUpdate) ClearName() *DeviceUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetLastSync sets the "last_sync" field.
func (_u *DeviceUpdate) SetLastSync(v time.Time) *DeviceUpdate {
	_u.mutation.SetLastSync(v)
	return _u
}

// SetNillableLastSync sets the "last_sync" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLastSync(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetLastSync(*v)
	}
	return _u
}

// ClearLastSync clears the value of the "last_sync" field.
func (_u *DeviceUpdate) ClearLastSync() *DeviceUpdate {
	_u.mutation.ClearLastSync()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdate) SetUpdatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *DeviceUpdate) SetOwner(v *User) *DeviceUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdate) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *DeviceUpdate) ClearOwner() *DeviceUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdate) check() error {
	if v, ok := _u.mutation.SerialNumber(); ok {
		if err := device.SerialNumberValidator(v); err != nil {
			return &ValidationError{Name: "serial_number", err: fmt.Errorf(`ent: validator failed for field "Device.serial_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := device.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "Device.model": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SerialNumber(); ok {
		_spec.SetField(device.FieldSerialNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(device.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsEnrolled(); ok {
		_spec.SetField(device.FieldIsEnrolled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(device.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.LastSync(); ok {
		_spec.SetField(device.FieldLastSync, field.TypeTime, value)
	}
	if _u.mutation.LastSyncCleared() {
		_spec.ClearField(device.FieldLastSync, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.OwnerTable,
			Columns: []string{device.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.OwnerTable,
			Columns: []string{device.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetSerialNumber sets the "serial_number" field.
func (_u *DeviceUpdateOne) SetSerialNumber(v string) *DeviceUpdateOne {
	_u.mutation.SetSerialNumber(v)
	return _u
}

// SetNillableSerialNumber sets the "serial_number" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableSerialNumber(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetSerialNumber(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *DeviceUpdateOne) SetModel(v string) *DeviceUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableModel(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *DeviceUpdateOne) SetOwnerID(v uint) *DeviceUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableOwnerID(v *uint) *DeviceUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *DeviceUpdateOne) ClearOwnerID() *DeviceUpdateOne {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetIsEnrolled sets the "is_enrolled" field.
func (_u *DeviceUpdateOne) SetIsEnrolled(v bool) *DeviceUpdateOne {
	_u.mutation.SetIsEnrolled(v)
	return _u
}

// SetNillableIsEnrolled sets the "is_enrolled" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableIsEnrolled(v *bool) *DeviceUpdateOne {
	if v != nil {
		_u.SetIsEnrolled(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeviceUpdateOne) SetName(v string) *DeviceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableName(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *DeviceUpdateOne) ClearName() *DeviceUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetLastSync sets the "last_sync" field.
func (_u *DeviceUpdateOne) SetLastSync(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetLastSync(v)
	return _u
}

// SetNillableLastSync sets the "last_sync" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLastSync(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetLastSync(*v)
	}
	return _u
}

// ClearLastSync clears the value of the "last_sync" field.
func (_u *DeviceUpdateOne) ClearLastSync() *DeviceUpdateOne {
	_u.mutation.ClearLastSync()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdateOne) SetUpdatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *DeviceUpdateOne) SetOwner(v *User) *DeviceUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdateOne) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *DeviceUpdateOne) ClearOwner() *DeviceUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdateOne) Where(ps ...predicate.Device) *DeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Device entity.
func (_u *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdateOne) check() error {
	if v, ok := _u.mutation.SerialNumber(); ok {
		if err := device.SerialNumberValidator(v); err != nil {
			return &ValidationError{Name: "serial_number", err: fmt.Errorf(`ent: validator failed for field "Device.serial_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := device.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "Device.model": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SerialNumber(); ok {
		_spec.SetField(device.FieldSerialNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(device.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsEnrolled(); ok {
		_spec.SetField(device.FieldIsEnrolled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(device.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.LastSync(); ok {
		_spec.SetField(device.FieldLastSync, field.TypeTime, value)
	}
	if _u.mutation.LastSyncCleared() {
		_spec.ClearField(device.FieldLastSync, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.OwnerTable,
			Columns: []string{device.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.OwnerTable,
			Columns: []string{device.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Device{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
