// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/thienel/go-backend-template/internal/ent/mobileconfig"
)

// MobileConfig is the model entity for the MobileConfig schema.
type MobileConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// PayloadIdentifier holds the value of the "payload_identifier" field.
	PayloadIdentifier string `json:"payload_identifier,omitempty"`
	// PayloadType holds the value of the "payload_type" field.
	PayloadType string `json:"payload_type,omitempty"`
	// PayloadDisplayName holds the value of the "payload_display_name" field.
	PayloadDisplayName string `json:"payload_display_name,omitempty"`
	// PayloadDescription holds the value of the "payload_description" field.
	PayloadDescription string `json:"payload_description,omitempty"`
	// PayloadOrganization holds the value of the "payload_organization" field.
	PayloadOrganization string `json:"payload_organization,omitempty"`
	// PayloadUUID holds the value of the "payload_uuid" field.
	PayloadUUID string `json:"payload_uuid,omitempty"`
	// PayloadVersion holds the value of the "payload_version" field.
	PayloadVersion int `json:"payload_version,omitempty"`
	// PayloadRemovalDisallowed holds the value of the "payload_removal_disallowed" field.
	PayloadRemovalDisallowed bool `json:"payload_removal_disallowed,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MobileConfigQuery when eager-loading is set.
	Edges        MobileConfigEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MobileConfigEdges holds the relations/edges for other nodes in the graph.
type MobileConfigEdges struct {
	// Payloads holds the value of the payloads edge.
	Payloads []*Payload `json:"payloads,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PayloadsOrErr returns the Payloads value or an error if the edge
// was not loaded in eager-loading.
func (e MobileConfigEdges) PayloadsOrErr() ([]*Payload, error) {
	if e.loadedTypes[0] {
		return e.Payloads, nil
	}
	return nil, &NotLoadedError{edge: "payloads"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MobileConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mobileconfig.FieldPayloadRemovalDisallowed:
			values[i] = new(sql.NullBool)
		case mobileconfig.FieldID, mobileconfig.FieldPayloadVersion:
			values[i] = new(sql.NullInt64)
		case mobileconfig.FieldName, mobileconfig.FieldPayloadIdentifier, mobileconfig.FieldPayloadType, mobileconfig.FieldPayloadDisplayName, mobileconfig.FieldPayloadDescription, mobileconfig.FieldPayloadOrganization, mobileconfig.FieldPayloadUUID:
			values[i] = new(sql.NullString)
		case mobileconfig.FieldCreatedAt, mobileconfig.FieldUpdatedAt, mobileconfig.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MobileConfig fields.
func (_m *MobileConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mobileconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case mobileconfig.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case mobileconfig.FieldPayloadIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_identifier", values[i])
			} else if value.Valid {
				_m.PayloadIdentifier = value.String
			}
		case mobileconfig.FieldPayloadType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_type", values[i])
			} else if value.Valid {
				_m.PayloadType = value.String
			}
		case mobileconfig.FieldPayloadDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_display_name", values[i])
			} else if value.Valid {
				_m.PayloadDisplayName = value.String
			}
		case mobileconfig.FieldPayloadDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_description", values[i])
			} else if value.Valid {
				_m.PayloadDescription = value.String
			}
		case mobileconfig.FieldPayloadOrganization:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_organization", values[i])
			} else if value.Valid {
				_m.PayloadOrganization = value.String
			}
		case mobileconfig.FieldPayloadUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_uuid", values[i])
			} else if value.Valid {
				_m.PayloadUUID = value.String
			}
		case mobileconfig.FieldPayloadVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payload_version", values[i])
			} else if value.Valid {
				_m.PayloadVersion = int(value.Int64)
			}
		case mobileconfig.FieldPayloadRemovalDisallowed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field payload_removal_disallowed", values[i])
			} else if value.Valid {
				_m.PayloadRemovalDisallowed = value.Bool
			}
		case mobileconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mobileconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case mobileconfig.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MobileConfig.
// This includes values selected through modifiers, order, etc.
func (_m *MobileConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPayloads queries the "payloads" edge of the MobileConfig entity.
func (_m *MobileConfig) QueryPayloads() *PayloadQuery {
	return NewMobileConfigClient(_m.config).QueryPayloads(_m)
}

// Update returns a builder for updating this MobileConfig.
// Note that you need to call MobileConfig.Unwrap() before calling this method if this MobileConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MobileConfig) Update() *MobileConfigUpdateOne {
	return NewMobileConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MobileConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MobileConfig) Unwrap() *MobileConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MobileConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MobileConfig) String() string {
	var builder strings.Builder
	builder.WriteString("MobileConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("payload_identifier=")
	builder.WriteString(_m.PayloadIdentifier)
	builder.WriteString(", ")
	builder.WriteString("payload_type=")
	builder.WriteString(_m.PayloadType)
	builder.WriteString(", ")
	builder.WriteString("payload_display_name=")
	builder.WriteString(_m.PayloadDisplayName)
	builder.WriteString(", ")
	builder.WriteString("payload_description=")
	builder.WriteString(_m.PayloadDescription)
	builder.WriteString(", ")
	builder.WriteString("payload_organization=")
	builder.WriteString(_m.PayloadOrganization)
	builder.WriteString(", ")
	builder.WriteString("payload_uuid=")
	builder.WriteString(_m.PayloadUUID)
	builder.WriteString(", ")
	builder.WriteString("payload_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.PayloadVersion))
	builder.WriteString(", ")
	builder.WriteString("payload_removal_disallowed=")
	builder.WriteString(fmt.Sprintf("%v", _m.PayloadRemovalDisallowed))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MobileConfigs is a parsable slice of MobileConfig.
type MobileConfigs []*MobileConfig
