// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thienel/go-backend-template/internal/ent/mobileconfig"
	"github.com/thienel/go-backend-template/internal/ent/payload"
	"github.com/thienel/go-backend-template/internal/ent/predicate"
)

// MobileConfigUpdate is the builder for updating MobileConfig entities.
type MobileConfigUpdate struct {
	config
	hooks    []Hook
	mutation *MobileConfigMutation
}

// Where appends a list predicates to the MobileConfigUpdate builder.
func (_u *MobileConfigUpdate) Where(ps ...predicate.MobileConfig) *MobileConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *MobileConfigUpdate) SetName(v string) *MobileConfigUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MobileConfigUpdate) SetNillableName(v *string) *MobileConfigUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPayloadIdentifier sets the "payload_identifier" field.
func (_u *MobileConfigUpdate) SetPayloadIdentifier(v string) *MobileConfigUpdate {
	_u.mutation.SetPayloadIdentifier(v)
	return _u
}

// SetNillablePayloadIdentifier sets the "payload_identifier" field if the given value is not nil.
func (_u *MobileConfigUpdate) SetNillablePayloadIdentifier(v *string) *MobileConfigUpdate {
	if v != nil {
		_u.SetPayloadIdentifier(*v)
	}
	return _u
}

// SetPayloadType sets the "payload_type" field.
func (_u *MobileConfigUpdate) SetPayloadType(v string) *MobileConfigUpdate {
	_u.mutation.SetPayloadType(v)
	return _u
}

// SetNillablePayloadType sets the "payload_type" field if the given value is not nil.
func (_u *MobileConfigUpdate) SetNillablePayloadType(v *string) *MobileConfigUpdate {
	if v != nil {
		_u.SetPayloadType(*v)
	}
	return _u
}

// SetPayloadDisplayName sets the "payload_display_name" field.
func (_u *MobileConfigUpdate) SetPayloadDisplayName(v string) *MobileConfigUpdate {
	_u.mutation.SetPayloadDisplayName(v)
	return _u
}

// SetNillablePayloadDisplayName sets the "payload_display_name" field if the given value is not nil.
func (_u *MobileConfigUpdate) SetNillablePayloadDisplayName(v *string) *MobileConfigUpdate {
	if v != nil {
		_u.SetPayloadDisplayName(*v)
	}
	return _u
}

// SetPayloadDescription sets the "payload_description" field.
func (_u *MobileConfigUpdate) SetPayloadDescription(v string) *MobileConfigUpdate {
	_u.mutation.SetPayloadDescription(v)
	return _u
}

// SetNillablePayloadDescription sets the "payload_description" field if the given value is not nil.
func (_u *MobileConfigUpdate) SetNillablePayloadDescription(v *string) *MobileConfigUpdate {
	if v != nil {
		_u.SetPayloadDescription(*v)
	}
	return _u
}

// ClearPayloadDescription clears the value of the "payload_description" field.
func (_u *MobileConfigUpdate) ClearPayloadDescription() *MobileConfigUpdate {
	_u.mutation.ClearPayloadDescription()
	return _u
}

// SetPayloadOrganization sets the "payload_organization" field.
func (_u *MobileConfigUpdate) SetPayloadOrganization(v string) *MobileConfigUpdate {
	_u.mutation.SetPayloadOrganization(v)
	return _u
}

// SetNillablePayloadOrganization sets the "payload_organization" field if the given value is not nil.
func (_u *MobileConfigUpdate) SetNillablePayloadOrganization(v *string) *MobileConfigUpdate {
	if v != nil {
		_u.SetPayloadOrganization(*v)
	}
	return _u
}

// ClearPayloadOrganization clears the value of the "payload_organization" field.
func (_u *MobileConfigUpdate) ClearPayloadOrganization() *MobileConfigUpdate {
	_u.mutation.ClearPayloadOrganization()
	return _u
}

// SetPayloadUUID sets the "payload_uuid" field.
func (_u *MobileConfigUpdate) SetPayloadUUID(v string) *MobileConfigUpdate {
	_u.mutation.SetPayloadUUID(v)
	return _u
}

// SetNillablePayloadUUID sets the "payload_uuid" field if the given value is not nil.
func (_u *MobileConfigUpdate) SetNillablePayloadUUID(v *string) *MobileConfigUpdate {
	if v != nil {
		_u.SetPayloadUUID(*v)
	}
	return _u
}

// SetPayloadVersion sets the "payload_version" field.
func (_u *MobileConfigUpdate) SetPayloadVersion(v int) *MobileConfigUpdate {
	_u.mutation.ResetPayloadVersion()
	_u.mutation.SetPayloadVersion(v)
	return _u
}

// SetNillablePayloadVersion sets the "payload_version" field if the given value is not nil.
func (_u *MobileConfigUpdate) SetNillablePayloadVersion(v *int) *MobileConfigUpdate {
	if v != nil {
		_u.SetPayloadVersion(*v)
	}
	return _u
}

// AddPayloadVersion adds value to the "payload_version" field.
func (_u *MobileConfigUpdate) AddPayloadVersion(v int) *MobileConfigUpdate {
	_u.mutation.AddPayloadVersion(v)
	return _u
}

// SetPayloadRemovalDisallowed sets the "payload_removal_disallowed" field.
func (_u *MobileConfigUpdate) SetPayloadRemovalDisallowed(v bool) *MobileConfigUpdate {
	_u.mutation.SetPayloadRemovalDisallowed(v)
	return _u
}

// SetNillablePayloadRemovalDisallowed sets the "payload_removal_disallowed" field if the given value is not nil.
func (_u *MobileConfigUpdate) SetNillablePayloadRemovalDisallowed(v *bool) *MobileConfigUpdate {
	if v != nil {
		_u.SetPayloadRemovalDisallowed(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MobileConfigUpdate) SetUpdatedAt(v time.Time) *MobileConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MobileConfigUpdate) SetDeletedAt(v time.Time) *MobileConfigUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MobileConfigUpdate) SetNillableDeletedAt(v *time.Time) *MobileConfigUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MobileConfigUpdate) ClearDeletedAt() *MobileConfigUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddPayloadIDs adds the "payloads" edge to the Payload entity by IDs.
func (_u *MobileConfigUpdate) AddPayloadIDs(ids ...uint) *MobileConfigUpdate {
	_u.mutation.AddPayloadIDs(ids...)
	return _u
}

// AddPayloads adds the "payloads" edges to the Payload entity.
func (_u *MobileConfigUpdate) AddPayloads(v ...*Payload) *MobileConfigUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPayloadIDs(ids...)
}

// Mutation returns the MobileConfigMutation object of the builder.
func (_u *MobileConfigUpdate) Mutation() *MobileConfigMutation {
	return _u.mutation
}

// ClearPayloads clears all "payloads" edges to the Payload entity.
func (_u *MobileConfigUpdate) ClearPayloads() *MobileConfigUpdate {
	_u.mutation.ClearPayloads()
	return _u
}

// RemovePayloadIDs removes the "payloads" edge to Payload entities by IDs.
func (_u *MobileConfigUpdate) RemovePayloadIDs(ids ...uint) *MobileConfigUpdate {
	_u.mutation.RemovePayloadIDs(ids...)
	return _u
}

// RemovePayloads removes "payloads" edges to Payload entities.
func (_u *MobileConfigUpdate) RemovePayloads(v ...*Payload) *MobileConfigUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePayloadIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MobileConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MobileConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MobileConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MobileConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MobileConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mobileconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MobileConfigUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := mobileconfig.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MobileConfig.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadIdentifier(); ok {
		if err := mobileconfig.PayloadIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "payload_identifier", err: fmt.Errorf(`ent: validator failed for field "MobileConfig.payload_identifier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadType(); ok {
		if err := mobileconfig.PayloadTypeValidator(v); err != nil {
			return &ValidationError{Name: "payload_type", err: fmt.Errorf(`ent: validator failed for field "MobileConfig.payload_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadDisplayName(); ok {
		if err := mobileconfig.PayloadDisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "payload_display_name", err: fmt.Errorf(`ent: validator failed for field "MobileConfig.payload_display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadOrganization(); ok {
		if err := mobileconfig.PayloadOrganizationValidator(v); err != nil {
			return &ValidationError{Name: "payload_organization", err: fmt.Errorf(`ent: validator failed for field "MobileConfig.payload_organization": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadUUID(); ok {
		if err := mobileconfig.PayloadUUIDValidator(v); err != nil {
			return &ValidationError{Name: "payload_uuid", err: fmt.Errorf(`ent: validator failed for field "MobileConfig.payload_uuid": %w`, err)}
		}
	}
	return nil
}

func (_u *MobileConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mobileconfig.Table, mobileconfig.Columns, sqlgraph.NewFieldSpec(mobileconfig.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mobileconfig.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadIdentifier(); ok {
		_spec.SetField(mobileconfig.FieldPayloadIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadType(); ok {
		_spec.SetField(mobileconfig.FieldPayloadType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadDisplayName(); ok {
		_spec.SetField(mobileconfig.FieldPayloadDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadDescription(); ok {
		_spec.SetField(mobileconfig.FieldPayloadDescription, field.TypeString, value)
	}
	if _u.mutation.PayloadDescriptionCleared() {
		_spec.ClearField(mobileconfig.FieldPayloadDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadOrganization(); ok {
		_spec.SetField(mobileconfig.FieldPayloadOrganization, field.TypeString, value)
	}
	if _u.mutation.PayloadOrganizationCleared() {
		_spec.ClearField(mobileconfig.FieldPayloadOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadUUID(); ok {
		_spec.SetField(mobileconfig.FieldPayloadUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadVersion(); ok {
		_spec.SetField(mobileconfig.FieldPayloadVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPayloadVersion(); ok {
		_spec.AddField(mobileconfig.FieldPayloadVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PayloadRemovalDisallowed(); ok {
		_spec.SetField(mobileconfig.FieldPayloadRemovalDisallowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mobileconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mobileconfig.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mobileconfig.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.PayloadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mobileconfig.PayloadsTable,
			Columns: []string{mobileconfig.PayloadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payload.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPayloadsIDs(); len(nodes) > 0 && !_u.mutation.PayloadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mobileconfig.PayloadsTable,
			Columns: []string{mobileconfig.PayloadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payload.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PayloadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mobileconfig.PayloadsTable,
			Columns: []string{mobileconfig.PayloadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payload.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mobileconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MobileConfigUpdateOne is the builder for updating a single MobileConfig entity.
type MobileConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MobileConfigMutation
}

// SetName sets the "name" field.
func (_u *MobileConfigUpdateOne) SetName(v string) *MobileConfigUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MobileConfigUpdateOne) SetNillableName(v *string) *MobileConfigUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPayloadIdentifier sets the "payload_identifier" field.
func (_u *MobileConfigUpdateOne) SetPayloadIdentifier(v string) *MobileConfigUpdateOne {
	_u.mutation.SetPayloadIdentifier(v)
	return _u
}

// SetNillablePayloadIdentifier sets the "payload_identifier" field if the given value is not nil.
func (_u *MobileConfigUpdateOne) SetNillablePayloadIdentifier(v *string) *MobileConfigUpdateOne {
	if v != nil {
		_u.SetPayloadIdentifier(*v)
	}
	return _u
}

// SetPayloadType sets the "payload_type" field.
func (_u *MobileConfigUpdateOne) SetPayloadType(v string) *MobileConfigUpdateOne {
	_u.mutation.SetPayloadType(v)
	return _u
}

// SetNillablePayloadType sets the "payload_type" field if the given value is not nil.
func (_u *MobileConfigUpdateOne) SetNillablePayloadType(v *string) *MobileConfigUpdateOne {
	if v != nil {
		_u.SetPayloadType(*v)
	}
	return _u
}

// SetPayloadDisplayName sets the "payload_display_name" field.
func (_u *MobileConfigUpdateOne) SetPayloadDisplayName(v string) *MobileConfigUpdateOne {
	_u.mutation.SetPayloadDisplayName(v)
	return _u
}

// SetNillablePayloadDisplayName sets the "payload_display_name" field if the given value is not nil.
func (_u *MobileConfigUpdateOne) SetNillablePayloadDisplayName(v *string) *MobileConfigUpdateOne {
	if v != nil {
		_u.SetPayloadDisplayName(*v)
	}
	return _u
}

// SetPayloadDescription sets the "payload_description" field.
func (_u *MobileConfigUpdateOne) SetPayloadDescription(v string) *MobileConfigUpdateOne {
	_u.mutation.SetPayloadDescription(v)
	return _u
}

// SetNillablePayloadDescription sets the "payload_description" field if the given value is not nil.
func (_u *MobileConfigUpdateOne) SetNillablePayloadDescription(v *string) *MobileConfigUpdateOne {
	if v != nil {
		_u.SetPayloadDescription(*v)
	}
	return _u
}

// ClearPayloadDescription clears the value of the "payload_description" field.
func (_u *MobileConfigUpdateOne) ClearPayloadDescription() *MobileConfigUpdateOne {
	_u.mutation.ClearPayloadDescription()
	return _u
}

// SetPayloadOrganization sets the "payload_organization" field.
func (_u *MobileConfigUpdateOne) SetPayloadOrganization(v string) *MobileConfigUpdateOne {
	_u.mutation.SetPayloadOrganization(v)
	return _u
}

// SetNillablePayloadOrganization sets the "payload_organization" field if the given value is not nil.
func (_u *MobileConfigUpdateOne) SetNillablePayloadOrganization(v *string) *MobileConfigUpdateOne {
	if v != nil {
		_u.SetPayloadOrganization(*v)
	}
	return _u
}

// ClearPayloadOrganization clears the value of the "payload_organization" field.
func (_u *MobileConfigUpdateOne) ClearPayloadOrganization() *MobileConfigUpdateOne {
	_u.mutation.ClearPayloadOrganization()
	return _u
}

// SetPayloadUUID sets the "payload_uuid" field.
func (_u *MobileConfigUpdateOne) SetPayloadUUID(v string) *MobileConfigUpdateOne {
	_u.mutation.SetPayloadUUID(v)
	return _u
}

// SetNillablePayloadUUID sets the "payload_uuid" field if the given value is not nil.
func (_u *MobileConfigUpdateOne) SetNillablePayloadUUID(v *string) *MobileConfigUpdateOne {
	if v != nil {
		_u.SetPayloadUUID(*v)
	}
	return _u
}

// SetPayloadVersion sets the "payload_version" field.
func (_u *MobileConfigUpdateOne) SetPayloadVersion(v int) *MobileConfigUpdateOne {
	_u.mutation.ResetPayloadVersion()
	_u.mutation.SetPayloadVersion(v)
	return _u
}

// SetNillablePayloadVersion sets the "payload_version" field if the given value is not nil.
func (_u *MobileConfigUpdateOne) SetNillablePayloadVersion(v *int) *MobileConfigUpdateOne {
	if v != nil {
		_u.SetPayloadVersion(*v)
	}
	return _u
}

// AddPayloadVersion adds value to the "payload_version" field.
func (_u *MobileConfigUpdateOne) AddPayloadVersion(v int) *MobileConfigUpdateOne {
	_u.mutation.AddPayloadVersion(v)
	return _u
}

// SetPayloadRemovalDisallowed sets the "payload_removal_disallowed" field.
func (_u *MobileConfigUpdateOne) SetPayloadRemovalDisallowed(v bool) *MobileConfigUpdateOne {
	_u.mutation.SetPayloadRemovalDisallowed(v)
	return _u
}

// SetNillablePayloadRemovalDisallowed sets the "payload_removal_disallowed" field if the given value is not nil.
func (_u *MobileConfigUpdateOne) SetNillablePayloadRemovalDisallowed(v *bool) *MobileConfigUpdateOne {
	if v != nil {
		_u.SetPayloadRemovalDisallowed(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MobileConfigUpdateOne) SetUpdatedAt(v time.Time) *MobileConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MobileConfigUpdateOne) SetDeletedAt(v time.Time) *MobileConfigUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MobileConfigUpdateOne) SetNillableDeletedAt(v *time.Time) *MobileConfigUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MobileConfigUpdateOne) ClearDeletedAt() *MobileConfigUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddPayloadIDs adds the "payloads" edge to the Payload entity by IDs.
func (_u *MobileConfigUpdateOne) AddPayloadIDs(ids ...uint) *MobileConfigUpdateOne {
	_u.mutation.AddPayloadIDs(ids...)
	return _u
}

// AddPayloads adds the "payloads" edges to the Payload entity.
func (_u *MobileConfigUpdateOne) AddPayloads(v ...*Payload) *MobileConfigUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPayloadIDs(ids...)
}

// Mutation returns the MobileConfigMutation object of the builder.
func (_u *MobileConfigUpdateOne) Mutation() *MobileConfigMutation {
	return _u.mutation
}

// ClearPayloads clears all "payloads" edges to the Payload entity.
func (_u *MobileConfigUpdateOne) ClearPayloads() *MobileConfigUpdateOne {
	_u.mutation.ClearPayloads()
	return _u
}

// RemovePayloadIDs removes the "payloads" edge to Payload entities by IDs.
func (_u *MobileConfigUpdateOne) RemovePayloadIDs(ids ...uint) *MobileConfigUpdateOne {
	_u.mutation.RemovePayloadIDs(ids...)
	return _u
}

// RemovePayloads removes "payloads" edges to Payload entities.
func (_u *MobileConfigUpdateOne) RemovePayloads(v ...*Payload) *MobileConfigUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePayloadIDs(ids...)
}

// Where appends a list predicates to the MobileConfigUpdate builder.
func (_u *MobileConfigUpdateOne) Where(ps ...predicate.MobileConfig) *MobileConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MobileConfigUpdateOne) Select(field string, fields ...string) *MobileConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MobileConfig entity.
func (_u *MobileConfigUpdateOne) Save(ctx context.Context) (*MobileConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MobileConfigUpdateOne) SaveX(ctx context.Context) *MobileConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MobileConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MobileConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MobileConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mobileconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MobileConfigUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := mobileconfig.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MobileConfig.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadIdentifier(); ok {
		if err := mobileconfig.PayloadIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "payload_identifier", err: fmt.Errorf(`ent: validator failed for field "MobileConfig.payload_identifier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadType(); ok {
		if err := mobileconfig.PayloadTypeValidator(v); err != nil {
			return &ValidationError{Name: "payload_type", err: fmt.Errorf(`ent: validator failed for field "MobileConfig.payload_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadDisplayName(); ok {
		if err := mobileconfig.PayloadDisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "payload_display_name", err: fmt.Errorf(`ent: validator failed for field "MobileConfig.payload_display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadOrganization(); ok {
		if err := mobileconfig.PayloadOrganizationValidator(v); err != nil {
			return &ValidationError{Name: "payload_organization", err: fmt.Errorf(`ent: validator failed for field "MobileConfig.payload_organization": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadUUID(); ok {
		if err := mobileconfig.PayloadUUIDValidator(v); err != nil {
			return &ValidationError{Name: "payload_uuid", err: fmt.Errorf(`ent: validator failed for field "MobileConfig.payload_uuid": %w`, err)}
		}
	}
	return nil
}

func (_u *MobileConfigUpdateOne) sqlSave(ctx context.Context) (_node *MobileConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mobileconfig.Table, mobileconfig.Columns, sqlgraph.NewFieldSpec(mobileconfig.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MobileConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mobileconfig.FieldID)
		for _, f := range fields {
			if !mobileconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mobileconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mobileconfig.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadIdentifier(); ok {
		_spec.SetField(mobileconfig.FieldPayloadIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadType(); ok {
		_spec.SetField(mobileconfig.FieldPayloadType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadDisplayName(); ok {
		_spec.SetField(mobileconfig.FieldPayloadDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadDescription(); ok {
		_spec.SetField(mobileconfig.FieldPayloadDescription, field.TypeString, value)
	}
	if _u.mutation.PayloadDescriptionCleared() {
		_spec.ClearField(mobileconfig.FieldPayloadDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadOrganization(); ok {
		_spec.SetField(mobileconfig.FieldPayloadOrganization, field.TypeString, value)
	}
	if _u.mutation.PayloadOrganizationCleared() {
		_spec.ClearField(mobileconfig.FieldPayloadOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadUUID(); ok {
		_spec.SetField(mobileconfig.FieldPayloadUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadVersion(); ok {
		_spec.SetField(mobileconfig.FieldPayloadVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPayloadVersion(); ok {
		_spec.AddField(mobileconfig.FieldPayloadVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PayloadRemovalDisallowed(); ok {
		_spec.SetField(mobileconfig.FieldPayloadRemovalDisallowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mobileconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mobileconfig.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mobileconfig.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.PayloadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mobileconfig.PayloadsTable,
			Columns: []string{mobileconfig.PayloadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payload.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPayloadsIDs(); len(nodes) > 0 && !_u.mutation.PayloadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mobileconfig.PayloadsTable,
			Columns: []string{mobileconfig.PayloadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payload.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PayloadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mobileconfig.PayloadsTable,
			Columns: []string{mobileconfig.PayloadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payload.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MobileConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mobileconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
