// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/thienel/go-backend-template/internal/ent/mobileconfig"
	"github.com/thienel/go-backend-template/internal/ent/payload"
)

// Payload is the model entity for the Payload schema.
type Payload struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// PayloadDescription holds the value of the "payload_description" field.
	PayloadDescription string `json:"payload_description,omitempty"`
	// PayloadDisplayName holds the value of the "payload_display_name" field.
	PayloadDisplayName string `json:"payload_display_name,omitempty"`
	// PayloadIdentifier holds the value of the "payload_identifier" field.
	PayloadIdentifier string `json:"payload_identifier,omitempty"`
	// PayloadOrganization holds the value of the "payload_organization" field.
	PayloadOrganization string `json:"payload_organization,omitempty"`
	// PayloadType holds the value of the "payload_type" field.
	PayloadType string `json:"payload_type,omitempty"`
	// PayloadUUID holds the value of the "payload_uuid" field.
	PayloadUUID string `json:"payload_uuid,omitempty"`
	// PayloadVersion holds the value of the "payload_version" field.
	PayloadVersion int `json:"payload_version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PayloadQuery when eager-loading is set.
	Edges                  PayloadEdges `json:"edges"`
	mobile_config_payloads *uint
	selectValues           sql.SelectValues
}

// PayloadEdges holds the relations/edges for other nodes in the graph.
type PayloadEdges struct {
	// MobileConfig holds the value of the mobile_config edge.
	MobileConfig *MobileConfig `json:"mobile_config,omitempty"`
	// Properties holds the value of the properties edge.
	Properties []*PayloadProperty `json:"properties,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MobileConfigOrErr returns the MobileConfig value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PayloadEdges) MobileConfigOrErr() (*MobileConfig, error) {
	if e.MobileConfig != nil {
		return e.MobileConfig, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: mobileconfig.Label}
	}
	return nil, &NotLoadedError{edge: "mobile_config"}
}

// PropertiesOrErr returns the Properties value or an error if the edge
// was not loaded in eager-loading.
func (e PayloadEdges) PropertiesOrErr() ([]*PayloadProperty, error) {
	if e.loadedTypes[1] {
		return e.Properties, nil
	}
	return nil, &NotLoadedError{edge: "properties"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Payload) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case payload.FieldID, payload.FieldPayloadVersion:
			values[i] = new(sql.NullInt64)
		case payload.FieldPayloadDescription, payload.FieldPayloadDisplayName, payload.FieldPayloadIdentifier, payload.FieldPayloadOrganization, payload.FieldPayloadType, payload.FieldPayloadUUID:
			values[i] = new(sql.NullString)
		case payload.FieldCreatedAt, payload.FieldUpdatedAt, payload.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case payload.ForeignKeys[0]: // mobile_config_payloads
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Payload fields.
func (_m *Payload) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case payload.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case payload.FieldPayloadDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_description", values[i])
			} else if value.Valid {
				_m.PayloadDescription = value.String
			}
		case payload.FieldPayloadDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_display_name", values[i])
			} else if value.Valid {
				_m.PayloadDisplayName = value.String
			}
		case payload.FieldPayloadIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_identifier", values[i])
			} else if value.Valid {
				_m.PayloadIdentifier = value.String
			}
		case payload.FieldPayloadOrganization:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_organization", values[i])
			} else if value.Valid {
				_m.PayloadOrganization = value.String
			}
		case payload.FieldPayloadType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_type", values[i])
			} else if value.Valid {
				_m.PayloadType = value.String
			}
		case payload.FieldPayloadUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_uuid", values[i])
			} else if value.Valid {
				_m.PayloadUUID = value.String
			}
		case payload.FieldPayloadVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payload_version", values[i])
			} else if value.Valid {
				_m.PayloadVersion = int(value.Int64)
			}
		case payload.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case payload.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case payload.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case payload.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field mobile_config_payloads", value)
			} else if value.Valid {
				_m.mobile_config_payloads = new(uint)
				*_m.mobile_config_payloads = uint(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Payload.
// This includes values selected through modifiers, order, etc.
func (_m *Payload) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMobileConfig queries the "mobile_config" edge of the Payload entity.
func (_m *Payload) QueryMobileConfig() *MobileConfigQuery {
	return NewPayloadClient(_m.config).QueryMobileConfig(_m)
}

// QueryProperties queries the "properties" edge of the Payload entity.
func (_m *Payload) QueryProperties() *PayloadPropertyQuery {
	return NewPayloadClient(_m.config).QueryProperties(_m)
}

// Update returns a builder for updating this Payload.
// Note that you need to call Payload.Unwrap() before calling this method if this Payload
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Payload) Update() *PayloadUpdateOne {
	return NewPayloadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Payload entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Payload) Unwrap() *Payload {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Payload is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Payload) String() string {
	var builder strings.Builder
	builder.WriteString("Payload(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("payload_description=")
	builder.WriteString(_m.PayloadDescription)
	builder.WriteString(", ")
	builder.WriteString("payload_display_name=")
	builder.WriteString(_m.PayloadDisplayName)
	builder.WriteString(", ")
	builder.WriteString("payload_identifier=")
	builder.WriteString(_m.PayloadIdentifier)
	builder.WriteString(", ")
	builder.WriteString("payload_organization=")
	builder.WriteString(_m.PayloadOrganization)
	builder.WriteString(", ")
	builder.WriteString("payload_type=")
	builder.WriteString(_m.PayloadType)
	builder.WriteString(", ")
	builder.WriteString("payload_uuid=")
	builder.WriteString(_m.PayloadUUID)
	builder.WriteString(", ")
	builder.WriteString("payload_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.PayloadVersion))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Payloads is a parsable slice of Payload.
type Payloads []*Payload
