// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thienel/go-backend-template/internal/ent/mobileconfig"
	"github.com/thienel/go-backend-template/internal/ent/payload"
	"github.com/thienel/go-backend-template/internal/ent/payloadproperty"
	"github.com/thienel/go-backend-template/internal/ent/predicate"
)

// PayloadUpdate is the builder for updating Payload entities.
type PayloadUpdate struct {
	config
	hooks    []Hook
	mutation *PayloadMutation
}

// Where appends a list predicates to the PayloadUpdate builder.
func (_u *PayloadUpdate) Where(ps ...predicate.Payload) *PayloadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPayloadDescription sets the "payload_description" field.
func (_u *PayloadUpdate) SetPayloadDescription(v string) *PayloadUpdate {
	_u.mutation.SetPayloadDescription(v)
	return _u
}

// SetNillablePayloadDescription sets the "payload_description" field if the given value is not nil.
func (_u *PayloadUpdate) SetNillablePayloadDescription(v *string) *PayloadUpdate {
	if v != nil {
		_u.SetPayloadDescription(*v)
	}
	return _u
}

// ClearPayloadDescription clears the value of the "payload_description" field.
func (_u *PayloadUpdate) ClearPayloadDescription() *PayloadUpdate {
	_u.mutation.ClearPayloadDescription()
	return _u
}

// SetPayloadDisplayName sets the "payload_display_name" field.
func (_u *PayloadUpdate) SetPayloadDisplayName(v string) *PayloadUpdate {
	_u.mutation.SetPayloadDisplayName(v)
	return _u
}

// SetNillablePayloadDisplayName sets the "payload_display_name" field if the given value is not nil.
func (_u *PayloadUpdate) SetNillablePayloadDisplayName(v *string) *PayloadUpdate {
	if v != nil {
		_u.SetPayloadDisplayName(*v)
	}
	return _u
}

// SetPayloadIdentifier sets the "payload_identifier" field.
func (_u *PayloadUpdate) SetPayloadIdentifier(v string) *PayloadUpdate {
	_u.mutation.SetPayloadIdentifier(v)
	return _u
}

// SetNillablePayloadIdentifier sets the "payload_identifier" field if the given value is not nil.
func (_u *PayloadUpdate) SetNillablePayloadIdentifier(v *string) *PayloadUpdate {
	if v != nil {
		_u.SetPayloadIdentifier(*v)
	}
	return _u
}

// SetPayloadOrganization sets the "payload_organization" field.
func (_u *PayloadUpdate) SetPayloadOrganization(v string) *PayloadUpdate {
	_u.mutation.SetPayloadOrganization(v)
	return _u
}

// SetNillablePayloadOrganization sets the "payload_organization" field if the given value is not nil.
func (_u *PayloadUpdate) SetNillablePayloadOrganization(v *string) *PayloadUpdate {
	if v != nil {
		_u.SetPayloadOrganization(*v)
	}
	return _u
}

// ClearPayloadOrganization clears the value of the "payload_organization" field.
func (_u *PayloadUpdate) ClearPayloadOrganization() *PayloadUpdate {
	_u.mutation.ClearPayloadOrganization()
	return _u
}

// SetPayloadType sets the "payload_type" field.
func (_u *PayloadUpdate) SetPayloadType(v string) *PayloadUpdate {
	_u.mutation.SetPayloadType(v)
	return _u
}

// SetNillablePayloadType sets the "payload_type" field if the given value is not nil.
func (_u *PayloadUpdate) SetNillablePayloadType(v *string) *PayloadUpdate {
	if v != nil {
		_u.SetPayloadType(*v)
	}
	return _u
}

// SetPayloadUUID sets the "payload_uuid" field.
func (_u *PayloadUpdate) SetPayloadUUID(v string) *PayloadUpdate {
	_u.mutation.SetPayloadUUID(v)
	return _u
}

// SetNillablePayloadUUID sets the "payload_uuid" field if the given value is not nil.
func (_u *PayloadUpdate) SetNillablePayloadUUID(v *string) *PayloadUpdate {
	if v != nil {
		_u.SetPayloadUUID(*v)
	}
	return _u
}

// SetPayloadVersion sets the "payload_version" field.
func (_u *PayloadUpdate) SetPayloadVersion(v int) *PayloadUpdate {
	_u.mutation.ResetPayloadVersion()
	_u.mutation.SetPayloadVersion(v)
	return _u
}

// SetNillablePayloadVersion sets the "payload_version" field if the given value is not nil.
func (_u *PayloadUpdate) SetNillablePayloadVersion(v *int) *PayloadUpdate {
	if v != nil {
		_u.SetPayloadVersion(*v)
	}
	return _u
}

// AddPayloadVersion adds value to the "payload_version" field.
func (_u *PayloadUpdate) AddPayloadVersion(v int) *PayloadUpdate {
	_u.mutation.AddPayloadVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PayloadUpdate) SetUpdatedAt(v time.Time) *PayloadUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PayloadUpdate) SetDeletedAt(v time.Time) *PayloadUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PayloadUpdate) SetNillableDeletedAt(v *time.Time) *PayloadUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PayloadUpdate) ClearDeletedAt() *PayloadUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetMobileConfigID sets the "mobile_config" edge to the MobileConfig entity by ID.
func (_u *PayloadUpdate) SetMobileConfigID(id uint) *PayloadUpdate {
	_u.mutation.SetMobileConfigID(id)
	return _u
}

// SetMobileConfig sets the "mobile_config" edge to the MobileConfig entity.
func (_u *PayloadUpdate) SetMobileConfig(v *MobileConfig) *PayloadUpdate {
	return _u.SetMobileConfigID(v.ID)
}

// AddPropertyIDs adds the "properties" edge to the PayloadProperty entity by IDs.
func (_u *PayloadUpdate) AddPropertyIDs(ids ...uint) *PayloadUpdate {
	_u.mutation.AddPropertyIDs(ids...)
	return _u
}

// AddProperties adds the "properties" edges to the PayloadProperty entity.
func (_u *PayloadUpdate) AddProperties(v ...*PayloadProperty) *PayloadUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPropertyIDs(ids...)
}

// Mutation returns the PayloadMutation object of the builder.
func (_u *PayloadUpdate) Mutation() *PayloadMutation {
	return _u.mutation
}

// ClearMobileConfig clears the "mobile_config" edge to the MobileConfig entity.
func (_u *PayloadUpdate) ClearMobileConfig() *PayloadUpdate {
	_u.mutation.ClearMobileConfig()
	return _u
}

// ClearProperties clears all "properties" edges to the PayloadProperty entity.
func (_u *PayloadUpdate) ClearProperties() *PayloadUpdate {
	_u.mutation.ClearProperties()
	return _u
}

// RemovePropertyIDs removes the "properties" edge to PayloadProperty entities by IDs.
func (_u *PayloadUpdate) RemovePropertyIDs(ids ...uint) *PayloadUpdate {
	_u.mutation.RemovePropertyIDs(ids...)
	return _u
}

// RemoveProperties removes "properties" edges to PayloadProperty entities.
func (_u *PayloadUpdate) RemoveProperties(v ...*PayloadProperty) *PayloadUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePropertyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PayloadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PayloadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PayloadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PayloadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PayloadUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := payload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PayloadUpdate) check() error {
	if v, ok := _u.mutation.PayloadDisplayName(); ok {
		if err := payload.PayloadDisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "payload_display_name", err: fmt.Errorf(`ent: validator failed for field "Payload.payload_display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadIdentifier(); ok {
		if err := payload.PayloadIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "payload_identifier", err: fmt.Errorf(`ent: validator failed for field "Payload.payload_identifier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadOrganization(); ok {
		if err := payload.PayloadOrganizationValidator(v); err != nil {
			return &ValidationError{Name: "payload_organization", err: fmt.Errorf(`ent: validator failed for field "Payload.payload_organization": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadType(); ok {
		if err := payload.PayloadTypeValidator(v); err != nil {
			return &ValidationError{Name: "payload_type", err: fmt.Errorf(`ent: validator failed for field "Payload.payload_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadUUID(); ok {
		if err := payload.PayloadUUIDValidator(v); err != nil {
			return &ValidationError{Name: "payload_uuid", err: fmt.Errorf(`ent: validator failed for field "Payload.payload_uuid": %w`, err)}
		}
	}
	if _u.mutation.MobileConfigCleared() && len(_u.mutation.MobileConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payload.mobile_config"`)
	}
	return nil
}

func (_u *PayloadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payload.Table, payload.Columns, sqlgraph.NewFieldSpec(payload.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PayloadDescription(); ok {
		_spec.SetField(payload.FieldPayloadDescription, field.TypeString, value)
	}
	if _u.mutation.PayloadDescriptionCleared() {
		_spec.ClearField(payload.FieldPayloadDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadDisplayName(); ok {
		_spec.SetField(payload.FieldPayloadDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadIdentifier(); ok {
		_spec.SetField(payload.FieldPayloadIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadOrganization(); ok {
		_spec.SetField(payload.FieldPayloadOrganization, field.TypeString, value)
	}
	if _u.mutation.PayloadOrganizationCleared() {
		_spec.ClearField(payload.FieldPayloadOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadType(); ok {
		_spec.SetField(payload.FieldPayloadType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadUUID(); ok {
		_spec.SetField(payload.FieldPayloadUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadVersion(); ok {
		_spec.SetField(payload.FieldPayloadVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPayloadVersion(); ok {
		_spec.AddField(payload.FieldPayloadVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payload.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(payload.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(payload.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.MobileConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payload.MobileConfigTable,
			Columns: []string{payload.MobileConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mobileconfig.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MobileConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payload.MobileConfigTable,
			Columns: []string{payload.MobileConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mobileconfig.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payload.PropertiesTable,
			Columns: []string{payload.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPropertiesIDs(); len(nodes) > 0 && !_u.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payload.PropertiesTable,
			Columns: []string{payload.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PropertiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payload.PropertiesTable,
			Columns: []string{payload.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PayloadUpdateOne is the builder for updating a single Payload entity.
type PayloadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PayloadMutation
}

// SetPayloadDescription sets the "payload_description" field.
func (_u *PayloadUpdateOne) SetPayloadDescription(v string) *PayloadUpdateOne {
	_u.mutation.SetPayloadDescription(v)
	return _u
}

// SetNillablePayloadDescription sets the "payload_description" field if the given value is not nil.
func (_u *PayloadUpdateOne) SetNillablePayloadDescription(v *string) *PayloadUpdateOne {
	if v != nil {
		_u.SetPayloadDescription(*v)
	}
	return _u
}

// ClearPayloadDescription clears the value of the "payload_description" field.
func (_u *PayloadUpdateOne) ClearPayloadDescription() *PayloadUpdateOne {
	_u.mutation.ClearPayloadDescription()
	return _u
}

// SetPayloadDisplayName sets the "payload_display_name" field.
func (_u *PayloadUpdateOne) SetPayloadDisplayName(v string) *PayloadUpdateOne {
	_u.mutation.SetPayloadDisplayName(v)
	return _u
}

// SetNillablePayloadDisplayName sets the "payload_display_name" field if the given value is not nil.
func (_u *PayloadUpdateOne) SetNillablePayloadDisplayName(v *string) *PayloadUpdateOne {
	if v != nil {
		_u.SetPayloadDisplayName(*v)
	}
	return _u
}

// SetPayloadIdentifier sets the "payload_identifier" field.
func (_u *PayloadUpdateOne) SetPayloadIdentifier(v string) *PayloadUpdateOne {
	_u.mutation.SetPayloadIdentifier(v)
	return _u
}

// SetNillablePayloadIdentifier sets the "payload_identifier" field if the given value is not nil.
func (_u *PayloadUpdateOne) SetNillablePayloadIdentifier(v *string) *PayloadUpdateOne {
	if v != nil {
		_u.SetPayloadIdentifier(*v)
	}
	return _u
}

// SetPayloadOrganization sets the "payload_organization" field.
func (_u *PayloadUpdateOne) SetPayloadOrganization(v string) *PayloadUpdateOne {
	_u.mutation.SetPayloadOrganization(v)
	return _u
}

// SetNillablePayloadOrganization sets the "payload_organization" field if the given value is not nil.
func (_u *PayloadUpdateOne) SetNillablePayloadOrganization(v *string) *PayloadUpdateOne {
	if v != nil {
		_u.SetPayloadOrganization(*v)
	}
	return _u
}

// ClearPayloadOrganization clears the value of the "payload_organization" field.
func (_u *PayloadUpdateOne) ClearPayloadOrganization() *PayloadUpdateOne {
	_u.mutation.ClearPayloadOrganization()
	return _u
}

// SetPayloadType sets the "payload_type" field.
func (_u *PayloadUpdateOne) SetPayloadType(v string) *PayloadUpdateOne {
	_u.mutation.SetPayloadType(v)
	return _u
}

// SetNillablePayloadType sets the "payload_type" field if the given value is not nil.
func (_u *PayloadUpdateOne) SetNillablePayloadType(v *string) *PayloadUpdateOne {
	if v != nil {
		_u.SetPayloadType(*v)
	}
	return _u
}

// SetPayloadUUID sets the "payload_uuid" field.
func (_u *PayloadUpdateOne) SetPayloadUUID(v string) *PayloadUpdateOne {
	_u.mutation.SetPayloadUUID(v)
	return _u
}

// SetNillablePayloadUUID sets the "payload_uuid" field if the given value is not nil.
func (_u *PayloadUpdateOne) SetNillablePayloadUUID(v *string) *PayloadUpdateOne {
	if v != nil {
		_u.SetPayloadUUID(*v)
	}
	return _u
}

// SetPayloadVersion sets the "payload_version" field.
func (_u *PayloadUpdateOne) SetPayloadVersion(v int) *PayloadUpdateOne {
	_u.mutation.ResetPayloadVersion()
	_u.mutation.SetPayloadVersion(v)
	return _u
}

// SetNillablePayloadVersion sets the "payload_version" field if the given value is not nil.
func (_u *PayloadUpdateOne) SetNillablePayloadVersion(v *int) *PayloadUpdateOne {
	if v != nil {
		_u.SetPayloadVersion(*v)
	}
	return _u
}

// AddPayloadVersion adds value to the "payload_version" field.
func (_u *PayloadUpdateOne) AddPayloadVersion(v int) *PayloadUpdateOne {
	_u.mutation.AddPayloadVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PayloadUpdateOne) SetUpdatedAt(v time.Time) *PayloadUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PayloadUpdateOne) SetDeletedAt(v time.Time) *PayloadUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PayloadUpdateOne) SetNillableDeletedAt(v *time.Time) *PayloadUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PayloadUpdateOne) ClearDeletedAt() *PayloadUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetMobileConfigID sets the "mobile_config" edge to the MobileConfig entity by ID.
func (_u *PayloadUpdateOne) SetMobileConfigID(id uint) *PayloadUpdateOne {
	_u.mutation.SetMobileConfigID(id)
	return _u
}

// SetMobileConfig sets the "mobile_config" edge to the MobileConfig entity.
func (_u *PayloadUpdateOne) SetMobileConfig(v *MobileConfig) *PayloadUpdateOne {
	return _u.SetMobileConfigID(v.ID)
}

// AddPropertyIDs adds the "properties" edge to the PayloadProperty entity by IDs.
func (_u *PayloadUpdateOne) AddPropertyIDs(ids ...uint) *PayloadUpdateOne {
	_u.mutation.AddPropertyIDs(ids...)
	return _u
}

// AddProperties adds the "properties" edges to the PayloadProperty entity.
func (_u *PayloadUpdateOne) AddProperties(v ...*PayloadProperty) *PayloadUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPropertyIDs(ids...)
}

// Mutation returns the PayloadMutation object of the builder.
func (_u *PayloadUpdateOne) Mutation() *PayloadMutation {
	return _u.mutation
}

// ClearMobileConfig clears the "mobile_config" edge to the MobileConfig entity.
func (_u *PayloadUpdateOne) ClearMobileConfig() *PayloadUpdateOne {
	_u.mutation.ClearMobileConfig()
	return _u
}

// ClearProperties clears all "properties" edges to the PayloadProperty entity.
func (_u *PayloadUpdateOne) ClearProperties() *PayloadUpdateOne {
	_u.mutation.ClearProperties()
	return _u
}

// RemovePropertyIDs removes the "properties" edge to PayloadProperty entities by IDs.
func (_u *PayloadUpdateOne) RemovePropertyIDs(ids ...uint) *PayloadUpdateOne {
	_u.mutation.RemovePropertyIDs(ids...)
	return _u
}

// RemoveProperties removes "properties" edges to PayloadProperty entities.
func (_u *PayloadUpdateOne) RemoveProperties(v ...*PayloadProperty) *PayloadUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePropertyIDs(ids...)
}

// Where appends a list predicates to the PayloadUpdate builder.
func (_u *PayloadUpdateOne) Where(ps ...predicate.Payload) *PayloadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PayloadUpdateOne) Select(field string, fields ...string) *PayloadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Payload entity.
func (_u *PayloadUpdateOne) Save(ctx context.Context) (*Payload, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PayloadUpdateOne) SaveX(ctx context.Context) *Payload {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PayloadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PayloadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PayloadUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := payload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PayloadUpdateOne) check() error {
	if v, ok := _u.mutation.PayloadDisplayName(); ok {
		if err := payload.PayloadDisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "payload_display_name", err: fmt.Errorf(`ent: validator failed for field "Payload.payload_display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadIdentifier(); ok {
		if err := payload.PayloadIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "payload_identifier", err: fmt.Errorf(`ent: validator failed for field "Payload.payload_identifier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadOrganization(); ok {
		if err := payload.PayloadOrganizationValidator(v); err != nil {
			return &ValidationError{Name: "payload_organization", err: fmt.Errorf(`ent: validator failed for field "Payload.payload_organization": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadType(); ok {
		if err := payload.PayloadTypeValidator(v); err != nil {
			return &ValidationError{Name: "payload_type", err: fmt.Errorf(`ent: validator failed for field "Payload.payload_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadUUID(); ok {
		if err := payload.PayloadUUIDValidator(v); err != nil {
			return &ValidationError{Name: "payload_uuid", err: fmt.Errorf(`ent: validator failed for field "Payload.payload_uuid": %w`, err)}
		}
	}
	if _u.mutation.MobileConfigCleared() && len(_u.mutation.MobileConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payload.mobile_config"`)
	}
	return nil
}

func (_u *PayloadUpdateOne) sqlSave(ctx context.Context) (_node *Payload, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payload.Table, payload.Columns, sqlgraph.NewFieldSpec(payload.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payload.FieldID)
		for _, f := range fields {
			if !payload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PayloadDescription(); ok {
		_spec.SetField(payload.FieldPayloadDescription, field.TypeString, value)
	}
	if _u.mutation.PayloadDescriptionCleared() {
		_spec.ClearField(payload.FieldPayloadDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadDisplayName(); ok {
		_spec.SetField(payload.FieldPayloadDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadIdentifier(); ok {
		_spec.SetField(payload.FieldPayloadIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadOrganization(); ok {
		_spec.SetField(payload.FieldPayloadOrganization, field.TypeString, value)
	}
	if _u.mutation.PayloadOrganizationCleared() {
		_spec.ClearField(payload.FieldPayloadOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadType(); ok {
		_spec.SetField(payload.FieldPayloadType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadUUID(); ok {
		_spec.SetField(payload.FieldPayloadUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadVersion(); ok {
		_spec.SetField(payload.FieldPayloadVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPayloadVersion(); ok {
		_spec.AddField(payload.FieldPayloadVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payload.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(payload.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(payload.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.MobileConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payload.MobileConfigTable,
			Columns: []string{payload.MobileConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mobileconfig.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MobileConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payload.MobileConfigTable,
			Columns: []string{payload.MobileConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mobileconfig.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payload.PropertiesTable,
			Columns: []string{payload.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPropertiesIDs(); len(nodes) > 0 && !_u.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payload.PropertiesTable,
			Columns: []string{payload.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PropertiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payload.PropertiesTable,
			Columns: []string{payload.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Payload{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
