// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thienel/go-backend-template/internal/ent/payloadproperty"
	"github.com/thienel/go-backend-template/internal/ent/payloadpropertydefinition"
)

// PayloadPropertyDefinitionCreate is the builder for creating a PayloadPropertyDefinition entity.
type PayloadPropertyDefinitionCreate struct {
	config
	mutation *PayloadPropertyDefinitionMutation
	hooks    []Hook
}

// SetPayloadType sets the "payload_type" field.
func (_c *PayloadPropertyDefinitionCreate) SetPayloadType(v string) *PayloadPropertyDefinitionCreate {
	_c.mutation.SetPayloadType(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *PayloadPropertyDefinitionCreate) SetKey(v string) *PayloadPropertyDefinitionCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValueType sets the "value_type" field.
func (_c *PayloadPropertyDefinitionCreate) SetValueType(v string) *PayloadPropertyDefinitionCreate {
	_c.mutation.SetValueType(v)
	return _c
}

// SetDefaultValue sets the "default_value" field.
func (_c *PayloadPropertyDefinitionCreate) SetDefaultValue(v map[string]interface{}) *PayloadPropertyDefinitionCreate {
	_c.mutation.SetDefaultValue(v)
	return _c
}

// SetEnumValues sets the "enum_values" field.
func (_c *PayloadPropertyDefinitionCreate) SetEnumValues(v []string) *PayloadPropertyDefinitionCreate {
	_c.mutation.SetEnumValues(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PayloadPropertyDefinitionCreate) SetDescription(v string) *PayloadPropertyDefinitionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PayloadPropertyDefinitionCreate) SetNillableDescription(v *string) *PayloadPropertyDefinitionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PayloadPropertyDefinitionCreate) SetCreatedAt(v time.Time) *PayloadPropertyDefinitionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PayloadPropertyDefinitionCreate) SetNillableCreatedAt(v *time.Time) *PayloadPropertyDefinitionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PayloadPropertyDefinitionCreate) SetUpdatedAt(v time.Time) *PayloadPropertyDefinitionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PayloadPropertyDefinitionCreate) SetNillableUpdatedAt(v *time.Time) *PayloadPropertyDefinitionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PayloadPropertyDefinitionCreate) SetDeletedAt(v time.Time) *PayloadPropertyDefinitionCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *PayloadPropertyDefinitionCreate) SetNillableDeletedAt(v *time.Time) *PayloadPropertyDefinitionCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// AddPropertyIDs adds the "properties" edge to the PayloadProperty entity by IDs.
func (_c *PayloadPropertyDefinitionCreate) AddPropertyIDs(ids ...uint) *PayloadPropertyDefinitionCreate {
	_c.mutation.AddPropertyIDs(ids...)
	return _c
}

// AddProperties adds the "properties" edges to the PayloadProperty entity.
func (_c *PayloadPropertyDefinitionCreate) AddProperties(v ...*PayloadProperty) *PayloadPropertyDefinitionCreate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPropertyIDs(ids...)
}

// Mutation returns the PayloadPropertyDefinitionMutation object of the builder.
func (_c *PayloadPropertyDefinitionCreate) Mutation() *PayloadPropertyDefinitionMutation {
	return _c.mutation
}

// Save creates the PayloadPropertyDefinition in the database.
func (_c *PayloadPropertyDefinitionCreate) Save(ctx context.Context) (*PayloadPropertyDefinition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PayloadPropertyDefinitionCreate) SaveX(ctx context.Context) *PayloadPropertyDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PayloadPropertyDefinitionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PayloadPropertyDefinitionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PayloadPropertyDefinitionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := payloadpropertydefinition.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := payloadpropertydefinition.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PayloadPropertyDefinitionCreate) check() error {
	if _, ok := _c.mutation.PayloadType(); !ok {
		return &ValidationError{Name: "payload_type", err: errors.New(`ent: missing required field "PayloadPropertyDefinition.payload_type"`)}
	}
	if v, ok := _c.mutation.PayloadType(); ok {
		if err := payloadpropertydefinition.PayloadTypeValidator(v); err != nil {
			return &ValidationError{Name: "payload_type", err: fmt.Errorf(`ent: validator failed for field "PayloadPropertyDefinition.payload_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "PayloadPropertyDefinition.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := payloadpropertydefinition.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "PayloadPropertyDefinition.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValueType(); !ok {
		return &ValidationError{Name: "value_type", err: errors.New(`ent: missing required field "PayloadPropertyDefinition.value_type"`)}
	}
	if v, ok := _c.mutation.ValueType(); ok {
		if err := payloadpropertydefinition.ValueTypeValidator(v); err != nil {
			return &ValidationError{Name: "value_type", err: fmt.Errorf(`ent: validator failed for field "PayloadPropertyDefinition.value_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PayloadPropertyDefinition.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PayloadPropertyDefinition.updated_at"`)}
	}
	return nil
}

func (_c *PayloadPropertyDefinitionCreate) sqlSave(ctx context.Context) (*PayloadPropertyDefinition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PayloadPropertyDefinitionCreate) createSpec() (*PayloadPropertyDefinition, *sqlgraph.CreateSpec) {
	var (
		_node = &PayloadPropertyDefinition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(payloadpropertydefinition.Table, sqlgraph.NewFieldSpec(payloadpropertydefinition.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PayloadType(); ok {
		_spec.SetField(payloadpropertydefinition.FieldPayloadType, field.TypeString, value)
		_node.PayloadType = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(payloadpropertydefinition.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.ValueType(); ok {
		_spec.SetField(payloadpropertydefinition.FieldValueType, field.TypeString, value)
		_node.ValueType = value
	}
	if value, ok := _c.mutation.DefaultValue(); ok {
		_spec.SetField(payloadpropertydefinition.FieldDefaultValue, field.TypeJSON, value)
		_node.DefaultValue = value
	}
	if value, ok := _c.mutation.EnumValues(); ok {
		_spec.SetField(payloadpropertydefinition.FieldEnumValues, field.TypeJSON, value)
		_node.EnumValues = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(payloadpropertydefinition.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(payloadpropertydefinition.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(payloadpropertydefinition.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(payloadpropertydefinition.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.PropertiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payloadpropertydefinition.PropertiesTable,
			Columns: []string{payloadpropertydefinition.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PayloadPropertyDefinitionCreateBulk is the builder for creating many PayloadPropertyDefinition entities in bulk.
type PayloadPropertyDefinitionCreateBulk struct {
	config
	err      error
	builders []*PayloadPropertyDefinitionCreate
}

// Save creates the PayloadPropertyDefinition entities in the database.
func (_c *PayloadPropertyDefinitionCreateBulk) Save(ctx context.Context) ([]*PayloadPropertyDefinition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PayloadPropertyDefinition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PayloadPropertyDefinitionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PayloadPropertyDefinitionCreateBulk) SaveX(ctx context.Context) []*PayloadPropertyDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PayloadPropertyDefinitionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PayloadPropertyDefinitionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
