// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/thienel/go-backend-template/internal/ent/payloadproperty"
	"github.com/thienel/go-backend-template/internal/ent/payloadpropertydefinition"
	"github.com/thienel/go-backend-template/internal/ent/predicate"
)

// PayloadPropertyDefinitionUpdate is the builder for updating PayloadPropertyDefinition entities.
type PayloadPropertyDefinitionUpdate struct {
	config
	hooks    []Hook
	mutation *PayloadPropertyDefinitionMutation
}

// Where appends a list predicates to the PayloadPropertyDefinitionUpdate builder.
func (_u *PayloadPropertyDefinitionUpdate) Where(ps ...predicate.PayloadPropertyDefinition) *PayloadPropertyDefinitionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPayloadType sets the "payload_type" field.
func (_u *PayloadPropertyDefinitionUpdate) SetPayloadType(v string) *PayloadPropertyDefinitionUpdate {
	_u.mutation.SetPayloadType(v)
	return _u
}

// SetNillablePayloadType sets the "payload_type" field if the given value is not nil.
func (_u *PayloadPropertyDefinitionUpdate) SetNillablePayloadType(v *string) *PayloadPropertyDefinitionUpdate {
	if v != nil {
		_u.SetPayloadType(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *PayloadPropertyDefinitionUpdate) SetKey(v string) *PayloadPropertyDefinitionUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *PayloadPropertyDefinitionUpdate) SetNillableKey(v *string) *PayloadPropertyDefinitionUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValueType sets the "value_type" field.
func (_u *PayloadPropertyDefinitionUpdate) SetValueType(v string) *PayloadPropertyDefinitionUpdate {
	_u.mutation.SetValueType(v)
	return _u
}

// SetNillableValueType sets the "value_type" field if the given value is not nil.
func (_u *PayloadPropertyDefinitionUpdate) SetNillableValueType(v *string) *PayloadPropertyDefinitionUpdate {
	if v != nil {
		_u.SetValueType(*v)
	}
	return _u
}

// SetDefaultValue sets the "default_value" field.
func (_u *PayloadPropertyDefinitionUpdate) SetDefaultValue(v map[string]any) *PayloadPropertyDefinitionUpdate {
	_u.mutation.SetDefaultValue(v)
	return _u
}

// ClearDefaultValue clears the value of the "default_value" field.
func (_u *PayloadPropertyDefinitionUpdate) ClearDefaultValue() *PayloadPropertyDefinitionUpdate {
	_u.mutation.ClearDefaultValue()
	return _u
}

// SetEnumValues sets the "enum_values" field.
func (_u *PayloadPropertyDefinitionUpdate) SetEnumValues(v []any) *PayloadPropertyDefinitionUpdate {
	_u.mutation.SetEnumValues(v)
	return _u
}

// AppendEnumValues appends value to the "enum_values" field.
func (_u *PayloadPropertyDefinitionUpdate) AppendEnumValues(v []any) *PayloadPropertyDefinitionUpdate {
	_u.mutation.AppendEnumValues(v)
	return _u
}

// ClearEnumValues clears the value of the "enum_values" field.
func (_u *PayloadPropertyDefinitionUpdate) ClearEnumValues() *PayloadPropertyDefinitionUpdate {
	_u.mutation.ClearEnumValues()
	return _u
}

// SetDescription sets the "description" field.
func (_u *PayloadPropertyDefinitionUpdate) SetDescription(v string) *PayloadPropertyDefinitionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PayloadPropertyDefinitionUpdate) SetNillableDescription(v *string) *PayloadPropertyDefinitionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PayloadPropertyDefinitionUpdate) ClearDescription() *PayloadPropertyDefinitionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PayloadPropertyDefinitionUpdate) SetUpdatedAt(v time.Time) *PayloadPropertyDefinitionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PayloadPropertyDefinitionUpdate) SetDeletedAt(v time.Time) *PayloadPropertyDefinitionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PayloadPropertyDefinitionUpdate) SetNillableDeletedAt(v *time.Time) *PayloadPropertyDefinitionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PayloadPropertyDefinitionUpdate) ClearDeletedAt() *PayloadPropertyDefinitionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddPropertyIDs adds the "properties" edge to the PayloadProperty entity by IDs.
func (_u *PayloadPropertyDefinitionUpdate) AddPropertyIDs(ids ...uint) *PayloadPropertyDefinitionUpdate {
	_u.mutation.AddPropertyIDs(ids...)
	return _u
}

// AddProperties adds the "properties" edges to the PayloadProperty entity.
func (_u *PayloadPropertyDefinitionUpdate) AddProperties(v ...*PayloadProperty) *PayloadPropertyDefinitionUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPropertyIDs(ids...)
}

// Mutation returns the PayloadPropertyDefinitionMutation object of the builder.
func (_u *PayloadPropertyDefinitionUpdate) Mutation() *PayloadPropertyDefinitionMutation {
	return _u.mutation
}

// ClearProperties clears all "properties" edges to the PayloadProperty entity.
func (_u *PayloadPropertyDefinitionUpdate) ClearProperties() *PayloadPropertyDefinitionUpdate {
	_u.mutation.ClearProperties()
	return _u
}

// RemovePropertyIDs removes the "properties" edge to PayloadProperty entities by IDs.
func (_u *PayloadPropertyDefinitionUpdate) RemovePropertyIDs(ids ...uint) *PayloadPropertyDefinitionUpdate {
	_u.mutation.RemovePropertyIDs(ids...)
	return _u
}

// RemoveProperties removes "properties" edges to PayloadProperty entities.
func (_u *PayloadPropertyDefinitionUpdate) RemoveProperties(v ...*PayloadProperty) *PayloadPropertyDefinitionUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePropertyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PayloadPropertyDefinitionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PayloadPropertyDefinitionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PayloadPropertyDefinitionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PayloadPropertyDefinitionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PayloadPropertyDefinitionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := payloadpropertydefinition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PayloadPropertyDefinitionUpdate) check() error {
	if v, ok := _u.mutation.PayloadType(); ok {
		if err := payloadpropertydefinition.PayloadTypeValidator(v); err != nil {
			return &ValidationError{Name: "payload_type", err: fmt.Errorf(`ent: validator failed for field "PayloadPropertyDefinition.payload_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Key(); ok {
		if err := payloadpropertydefinition.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "PayloadPropertyDefinition.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValueType(); ok {
		if err := payloadpropertydefinition.ValueTypeValidator(v); err != nil {
			return &ValidationError{Name: "value_type", err: fmt.Errorf(`ent: validator failed for field "PayloadPropertyDefinition.value_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PayloadPropertyDefinitionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payloadpropertydefinition.Table, payloadpropertydefinition.Columns, sqlgraph.NewFieldSpec(payloadpropertydefinition.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PayloadType(); ok {
		_spec.SetField(payloadpropertydefinition.FieldPayloadType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(payloadpropertydefinition.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValueType(); ok {
		_spec.SetField(payloadpropertydefinition.FieldValueType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultValue(); ok {
		_spec.SetField(payloadpropertydefinition.FieldDefaultValue, field.TypeJSON, value)
	}
	if _u.mutation.DefaultValueCleared() {
		_spec.ClearField(payloadpropertydefinition.FieldDefaultValue, field.TypeJSON)
	}
	if value, ok := _u.mutation.EnumValues(); ok {
		_spec.SetField(payloadpropertydefinition.FieldEnumValues, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEnumValues(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, payloadpropertydefinition.FieldEnumValues, value)
		})
	}
	if _u.mutation.EnumValuesCleared() {
		_spec.ClearField(payloadpropertydefinition.FieldEnumValues, field.TypeJSON)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(payloadpropertydefinition.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(payloadpropertydefinition.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payloadpropertydefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(payloadpropertydefinition.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(payloadpropertydefinition.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payloadpropertydefinition.PropertiesTable,
			Columns: []string{payloadpropertydefinition.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPropertiesIDs(); len(nodes) > 0 && !_u.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payloadpropertydefinition.PropertiesTable,
			Columns: []string{payloadpropertydefinition.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PropertiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payloadpropertydefinition.PropertiesTable,
			Columns: []string{payloadpropertydefinition.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payloadpropertydefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PayloadPropertyDefinitionUpdateOne is the builder for updating a single PayloadPropertyDefinition entity.
type PayloadPropertyDefinitionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PayloadPropertyDefinitionMutation
}

// SetPayloadType sets the "payload_type" field.
func (_u *PayloadPropertyDefinitionUpdateOne) SetPayloadType(v string) *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.SetPayloadType(v)
	return _u
}

// SetNillablePayloadType sets the "payload_type" field if the given value is not nil.
func (_u *PayloadPropertyDefinitionUpdateOne) SetNillablePayloadType(v *string) *PayloadPropertyDefinitionUpdateOne {
	if v != nil {
		_u.SetPayloadType(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *PayloadPropertyDefinitionUpdateOne) SetKey(v string) *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *PayloadPropertyDefinitionUpdateOne) SetNillableKey(v *string) *PayloadPropertyDefinitionUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValueType sets the "value_type" field.
func (_u *PayloadPropertyDefinitionUpdateOne) SetValueType(v string) *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.SetValueType(v)
	return _u
}

// SetNillableValueType sets the "value_type" field if the given value is not nil.
func (_u *PayloadPropertyDefinitionUpdateOne) SetNillableValueType(v *string) *PayloadPropertyDefinitionUpdateOne {
	if v != nil {
		_u.SetValueType(*v)
	}
	return _u
}

// SetDefaultValue sets the "default_value" field.
func (_u *PayloadPropertyDefinitionUpdateOne) SetDefaultValue(v map[string]any) *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.SetDefaultValue(v)
	return _u
}

// ClearDefaultValue clears the value of the "default_value" field.
func (_u *PayloadPropertyDefinitionUpdateOne) ClearDefaultValue() *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.ClearDefaultValue()
	return _u
}

// SetEnumValues sets the "enum_values" field.
func (_u *PayloadPropertyDefinitionUpdateOne) SetEnumValues(v []any) *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.SetEnumValues(v)
	return _u
}

// AppendEnumValues appends value to the "enum_values" field.
func (_u *PayloadPropertyDefinitionUpdateOne) AppendEnumValues(v []any) *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.AppendEnumValues(v)
	return _u
}

// ClearEnumValues clears the value of the "enum_values" field.
func (_u *PayloadPropertyDefinitionUpdateOne) ClearEnumValues() *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.ClearEnumValues()
	return _u
}

// SetDescription sets the "description" field.
func (_u *PayloadPropertyDefinitionUpdateOne) SetDescription(v string) *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PayloadPropertyDefinitionUpdateOne) SetNillableDescription(v *string) *PayloadPropertyDefinitionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PayloadPropertyDefinitionUpdateOne) ClearDescription() *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PayloadPropertyDefinitionUpdateOne) SetUpdatedAt(v time.Time) *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PayloadPropertyDefinitionUpdateOne) SetDeletedAt(v time.Time) *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PayloadPropertyDefinitionUpdateOne) SetNillableDeletedAt(v *time.Time) *PayloadPropertyDefinitionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PayloadPropertyDefinitionUpdateOne) ClearDeletedAt() *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddPropertyIDs adds the "properties" edge to the PayloadProperty entity by IDs.
func (_u *PayloadPropertyDefinitionUpdateOne) AddPropertyIDs(ids ...uint) *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.AddPropertyIDs(ids...)
	return _u
}

// AddProperties adds the "properties" edges to the PayloadProperty entity.
func (_u *PayloadPropertyDefinitionUpdateOne) AddProperties(v ...*PayloadProperty) *PayloadPropertyDefinitionUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPropertyIDs(ids...)
}

// Mutation returns the PayloadPropertyDefinitionMutation object of the builder.
func (_u *PayloadPropertyDefinitionUpdateOne) Mutation() *PayloadPropertyDefinitionMutation {
	return _u.mutation
}

// ClearProperties clears all "properties" edges to the PayloadProperty entity.
func (_u *PayloadPropertyDefinitionUpdateOne) ClearProperties() *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.ClearProperties()
	return _u
}

// RemovePropertyIDs removes the "properties" edge to PayloadProperty entities by IDs.
func (_u *PayloadPropertyDefinitionUpdateOne) RemovePropertyIDs(ids ...uint) *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.RemovePropertyIDs(ids...)
	return _u
}

// RemoveProperties removes "properties" edges to PayloadProperty entities.
func (_u *PayloadPropertyDefinitionUpdateOne) RemoveProperties(v ...*PayloadProperty) *PayloadPropertyDefinitionUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePropertyIDs(ids...)
}

// Where appends a list predicates to the PayloadPropertyDefinitionUpdate builder.
func (_u *PayloadPropertyDefinitionUpdateOne) Where(ps ...predicate.PayloadPropertyDefinition) *PayloadPropertyDefinitionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PayloadPropertyDefinitionUpdateOne) Select(field string, fields ...string) *PayloadPropertyDefinitionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PayloadPropertyDefinition entity.
func (_u *PayloadPropertyDefinitionUpdateOne) Save(ctx context.Context) (*PayloadPropertyDefinition, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PayloadPropertyDefinitionUpdateOne) SaveX(ctx context.Context) *PayloadPropertyDefinition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PayloadPropertyDefinitionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PayloadPropertyDefinitionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PayloadPropertyDefinitionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := payloadpropertydefinition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PayloadPropertyDefinitionUpdateOne) check() error {
	if v, ok := _u.mutation.PayloadType(); ok {
		if err := payloadpropertydefinition.PayloadTypeValidator(v); err != nil {
			return &ValidationError{Name: "payload_type", err: fmt.Errorf(`ent: validator failed for field "PayloadPropertyDefinition.payload_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Key(); ok {
		if err := payloadpropertydefinition.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "PayloadPropertyDefinition.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValueType(); ok {
		if err := payloadpropertydefinition.ValueTypeValidator(v); err != nil {
			return &ValidationError{Name: "value_type", err: fmt.Errorf(`ent: validator failed for field "PayloadPropertyDefinition.value_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PayloadPropertyDefinitionUpdateOne) sqlSave(ctx context.Context) (_node *PayloadPropertyDefinition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payloadpropertydefinition.Table, payloadpropertydefinition.Columns, sqlgraph.NewFieldSpec(payloadpropertydefinition.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PayloadPropertyDefinition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payloadpropertydefinition.FieldID)
		for _, f := range fields {
			if !payloadpropertydefinition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payloadpropertydefinition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PayloadType(); ok {
		_spec.SetField(payloadpropertydefinition.FieldPayloadType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(payloadpropertydefinition.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValueType(); ok {
		_spec.SetField(payloadpropertydefinition.FieldValueType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultValue(); ok {
		_spec.SetField(payloadpropertydefinition.FieldDefaultValue, field.TypeJSON, value)
	}
	if _u.mutation.DefaultValueCleared() {
		_spec.ClearField(payloadpropertydefinition.FieldDefaultValue, field.TypeJSON)
	}
	if value, ok := _u.mutation.EnumValues(); ok {
		_spec.SetField(payloadpropertydefinition.FieldEnumValues, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEnumValues(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, payloadpropertydefinition.FieldEnumValues, value)
		})
	}
	if _u.mutation.EnumValuesCleared() {
		_spec.ClearField(payloadpropertydefinition.FieldEnumValues, field.TypeJSON)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(payloadpropertydefinition.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(payloadpropertydefinition.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payloadpropertydefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(payloadpropertydefinition.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(payloadpropertydefinition.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payloadpropertydefinition.PropertiesTable,
			Columns: []string{payloadpropertydefinition.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPropertiesIDs(); len(nodes) > 0 && !_u.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payloadpropertydefinition.PropertiesTable,
			Columns: []string{payloadpropertydefinition.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PropertiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payloadpropertydefinition.PropertiesTable,
			Columns: []string{payloadpropertydefinition.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PayloadPropertyDefinition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payloadpropertydefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
