// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thienel/go-backend-template/internal/ent/payload"
	"github.com/thienel/go-backend-template/internal/ent/payloadproperty"
	"github.com/thienel/go-backend-template/internal/ent/payloadpropertydefinition"
	"github.com/thienel/go-backend-template/internal/ent/predicate"
)

// PayloadPropertyUpdate is the builder for updating PayloadProperty entities.
type PayloadPropertyUpdate struct {
	config
	hooks    []Hook
	mutation *PayloadPropertyMutation
}

// Where appends a list predicates to the PayloadPropertyUpdate builder.
func (_u *PayloadPropertyUpdate) Where(ps ...predicate.PayloadProperty) *PayloadPropertyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetValueJSON sets the "value_json" field.
func (_u *PayloadPropertyUpdate) SetValueJSON(v map[string]interface{}) *PayloadPropertyUpdate {
	_u.mutation.SetValueJSON(v)
	return _u
}

// ClearValueJSON clears the value of the "value_json" field.
func (_u *PayloadPropertyUpdate) ClearValueJSON() *PayloadPropertyUpdate {
	_u.mutation.ClearValueJSON()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PayloadPropertyUpdate) SetUpdatedAt(v time.Time) *PayloadPropertyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PayloadPropertyUpdate) SetDeletedAt(v time.Time) *PayloadPropertyUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PayloadPropertyUpdate) SetNillableDeletedAt(v *time.Time) *PayloadPropertyUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PayloadPropertyUpdate) ClearDeletedAt() *PayloadPropertyUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPayloadID sets the "payload" edge to the Payload entity by ID.
func (_u *PayloadPropertyUpdate) SetPayloadID(id uint) *PayloadPropertyUpdate {
	_u.mutation.SetPayloadID(id)
	return _u
}

// SetPayload sets the "payload" edge to the Payload entity.
func (_u *PayloadPropertyUpdate) SetPayload(v *Payload) *PayloadPropertyUpdate {
	return _u.SetPayloadID(v.ID)
}

// SetDefinitionID sets the "definition" edge to the PayloadPropertyDefinition entity by ID.
func (_u *PayloadPropertyUpdate) SetDefinitionID(id int) *PayloadPropertyUpdate {
	_u.mutation.SetDefinitionID(id)
	return _u
}

// SetDefinition sets the "definition" edge to the PayloadPropertyDefinition entity.
func (_u *PayloadPropertyUpdate) SetDefinition(v *PayloadPropertyDefinition) *PayloadPropertyUpdate {
	return _u.SetDefinitionID(v.ID)
}

// Mutation returns the PayloadPropertyMutation object of the builder.
func (_u *PayloadPropertyUpdate) Mutation() *PayloadPropertyMutation {
	return _u.mutation
}

// ClearPayload clears the "payload" edge to the Payload entity.
func (_u *PayloadPropertyUpdate) ClearPayload() *PayloadPropertyUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// ClearDefinition clears the "definition" edge to the PayloadPropertyDefinition entity.
func (_u *PayloadPropertyUpdate) ClearDefinition() *PayloadPropertyUpdate {
	_u.mutation.ClearDefinition()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PayloadPropertyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PayloadPropertyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PayloadPropertyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PayloadPropertyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PayloadPropertyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := payloadproperty.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PayloadPropertyUpdate) check() error {
	if _u.mutation.PayloadCleared() && len(_u.mutation.PayloadIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PayloadProperty.payload"`)
	}
	if _u.mutation.DefinitionCleared() && len(_u.mutation.DefinitionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PayloadProperty.definition"`)
	}
	return nil
}

func (_u *PayloadPropertyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payloadproperty.Table, payloadproperty.Columns, sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ValueJSON(); ok {
		_spec.SetField(payloadproperty.FieldValueJSON, field.TypeJSON, value)
	}
	if _u.mutation.ValueJSONCleared() {
		_spec.ClearField(payloadproperty.FieldValueJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payloadproperty.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(payloadproperty.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(payloadproperty.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.PayloadCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payloadproperty.PayloadTable,
			Columns: []string{payloadproperty.PayloadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payload.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PayloadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payloadproperty.PayloadTable,
			Columns: []string{payloadproperty.PayloadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payload.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DefinitionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payloadproperty.DefinitionTable,
			Columns: []string{payloadproperty.DefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadpropertydefinition.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DefinitionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payloadproperty.DefinitionTable,
			Columns: []string{payloadproperty.DefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadpropertydefinition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payloadproperty.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PayloadPropertyUpdateOne is the builder for updating a single PayloadProperty entity.
type PayloadPropertyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PayloadPropertyMutation
}

// SetValueJSON sets the "value_json" field.
func (_u *PayloadPropertyUpdateOne) SetValueJSON(v map[string]interface{}) *PayloadPropertyUpdateOne {
	_u.mutation.SetValueJSON(v)
	return _u
}

// ClearValueJSON clears the value of the "value_json" field.
func (_u *PayloadPropertyUpdateOne) ClearValueJSON() *PayloadPropertyUpdateOne {
	_u.mutation.ClearValueJSON()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PayloadPropertyUpdateOne) SetUpdatedAt(v time.Time) *PayloadPropertyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PayloadPropertyUpdateOne) SetDeletedAt(v time.Time) *PayloadPropertyUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PayloadPropertyUpdateOne) SetNillableDeletedAt(v *time.Time) *PayloadPropertyUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PayloadPropertyUpdateOne) ClearDeletedAt() *PayloadPropertyUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPayloadID sets the "payload" edge to the Payload entity by ID.
func (_u *PayloadPropertyUpdateOne) SetPayloadID(id uint) *PayloadPropertyUpdateOne {
	_u.mutation.SetPayloadID(id)
	return _u
}

// SetPayload sets the "payload" edge to the Payload entity.
func (_u *PayloadPropertyUpdateOne) SetPayload(v *Payload) *PayloadPropertyUpdateOne {
	return _u.SetPayloadID(v.ID)
}

// SetDefinitionID sets the "definition" edge to the PayloadPropertyDefinition entity by ID.
func (_u *PayloadPropertyUpdateOne) SetDefinitionID(id int) *PayloadPropertyUpdateOne {
	_u.mutation.SetDefinitionID(id)
	return _u
}

// SetDefinition sets the "definition" edge to the PayloadPropertyDefinition entity.
func (_u *PayloadPropertyUpdateOne) SetDefinition(v *PayloadPropertyDefinition) *PayloadPropertyUpdateOne {
	return _u.SetDefinitionID(v.ID)
}

// Mutation returns the PayloadPropertyMutation object of the builder.
func (_u *PayloadPropertyUpdateOne) Mutation() *PayloadPropertyMutation {
	return _u.mutation
}

// ClearPayload clears the "payload" edge to the Payload entity.
func (_u *PayloadPropertyUpdateOne) ClearPayload() *PayloadPropertyUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// ClearDefinition clears the "definition" edge to the PayloadPropertyDefinition entity.
func (_u *PayloadPropertyUpdateOne) ClearDefinition() *PayloadPropertyUpdateOne {
	_u.mutation.ClearDefinition()
	return _u
}

// Where appends a list predicates to the PayloadPropertyUpdate builder.
func (_u *PayloadPropertyUpdateOne) Where(ps ...predicate.PayloadProperty) *PayloadPropertyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PayloadPropertyUpdateOne) Select(field string, fields ...string) *PayloadPropertyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PayloadProperty entity.
func (_u *PayloadPropertyUpdateOne) Save(ctx context.Context) (*PayloadProperty, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PayloadPropertyUpdateOne) SaveX(ctx context.Context) *PayloadProperty {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PayloadPropertyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PayloadPropertyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PayloadPropertyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := payloadproperty.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PayloadPropertyUpdateOne) check() error {
	if _u.mutation.PayloadCleared() && len(_u.mutation.PayloadIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PayloadProperty.payload"`)
	}
	if _u.mutation.DefinitionCleared() && len(_u.mutation.DefinitionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PayloadProperty.definition"`)
	}
	return nil
}

func (_u *PayloadPropertyUpdateOne) sqlSave(ctx context.Context) (_node *PayloadProperty, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payloadproperty.Table, payloadproperty.Columns, sqlgraph.NewFieldSpec(payloadproperty.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PayloadProperty.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payloadproperty.FieldID)
		for _, f := range fields {
			if !payloadproperty.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payloadproperty.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ValueJSON(); ok {
		_spec.SetField(payloadproperty.FieldValueJSON, field.TypeJSON, value)
	}
	if _u.mutation.ValueJSONCleared() {
		_spec.ClearField(payloadproperty.FieldValueJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payloadproperty.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(payloadproperty.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(payloadproperty.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.PayloadCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payloadproperty.PayloadTable,
			Columns: []string{payloadproperty.PayloadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payload.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PayloadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payloadproperty.PayloadTable,
			Columns: []string{payloadproperty.PayloadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payload.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DefinitionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payloadproperty.DefinitionTable,
			Columns: []string{payloadproperty.DefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadpropertydefinition.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DefinitionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payloadproperty.DefinitionTable,
			Columns: []string{payloadproperty.DefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payloadpropertydefinition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PayloadProperty{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payloadproperty.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
