// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/thienel/go-backend-template/internal/ent/profile"
	"github.com/thienel/go-backend-template/internal/ent/profileversion"
)

// ProfileVersion is the model entity for the ProfileVersion schema.
type ProfileVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// ProfileID holds the value of the "profile_id" field.
	ProfileID uint `json:"profile_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// Data holds the value of the "data" field.
	Data map[string]interface{} `json:"data,omitempty"`
	// ChangeNotes holds the value of the "change_notes" field.
	ChangeNotes string `json:"change_notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProfileVersionQuery when eager-loading is set.
	Edges        ProfileVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProfileVersionEdges holds the relations/edges for other nodes in the graph.
type ProfileVersionEdges struct {
	// Profile holds the value of the profile edge.
	Profile *Profile `json:"profile,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProfileOrErr returns the Profile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProfileVersionEdges) ProfileOrErr() (*Profile, error) {
	if e.Profile != nil {
		return e.Profile, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: profile.Label}
	}
	return nil, &NotLoadedError{edge: "profile"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProfileVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case profileversion.FieldData:
			values[i] = new([]byte)
		case profileversion.FieldID, profileversion.FieldProfileID, profileversion.FieldVersion:
			values[i] = new(sql.NullInt64)
		case profileversion.FieldChangeNotes:
			values[i] = new(sql.NullString)
		case profileversion.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProfileVersion fields.
func (_m *ProfileVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case profileversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case profileversion.FieldProfileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field profile_id", values[i])
			} else if value.Valid {
				_m.ProfileID = uint(value.Int64)
			}
		case profileversion.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case profileversion.FieldData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Data); err != nil {
					return fmt.Errorf("unmarshal field data: %w", err)
				}
			}
		case profileversion.FieldChangeNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_notes", values[i])
			} else if value.Valid {
				_m.ChangeNotes = value.String
			}
		case profileversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProfileVersion.
// This includes values selected through modifiers, order, etc.
func (_m *ProfileVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProfile queries the "profile" edge of the ProfileVersion entity.
func (_m *ProfileVersion) QueryProfile() *ProfileQuery {
	return NewProfileVersionClient(_m.config).QueryProfile(_m)
}

// Update returns a builder for updating this ProfileVersion.
// Note that you need to call ProfileVersion.Unwrap() before calling this method if this ProfileVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProfileVersion) Update() *ProfileVersionUpdateOne {
	return NewProfileVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProfileVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProfileVersion) Unwrap() *ProfileVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProfileVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProfileVersion) String() string {
	var builder strings.Builder
	builder.WriteString("ProfileVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("profile_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProfileID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("data=")
	builder.WriteString(fmt.Sprintf("%v", _m.Data))
	builder.WriteString(", ")
	builder.WriteString("change_notes=")
	builder.WriteString(_m.ChangeNotes)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProfileVersions is a parsable slice of ProfileVersion.
type ProfileVersions []*ProfileVersion
