// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thienel/go-backend-template/internal/ent/device"
	"github.com/thienel/go-backend-template/internal/ent/profile"
	"github.com/thienel/go-backend-template/internal/ent/profiledeploymentstatus"
)

// ProfileDeploymentStatusCreate is the builder for creating a ProfileDeploymentStatus entity.
type ProfileDeploymentStatusCreate struct {
	config
	mutation *ProfileDeploymentStatusMutation
	hooks    []Hook
}

// SetProfileID sets the "profile_id" field.
func (_c *ProfileDeploymentStatusCreate) SetProfileID(v uint) *ProfileDeploymentStatusCreate {
	_c.mutation.SetProfileID(v)
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *ProfileDeploymentStatusCreate) SetDeviceID(v string) *ProfileDeploymentStatusCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProfileDeploymentStatusCreate) SetStatus(v profiledeploymentstatus.Status) *ProfileDeploymentStatusCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProfileDeploymentStatusCreate) SetNillableStatus(v *profiledeploymentstatus.Status) *ProfileDeploymentStatusCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *ProfileDeploymentStatusCreate) SetErrorMessage(v string) *ProfileDeploymentStatusCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *ProfileDeploymentStatusCreate) SetNillableErrorMessage(v *string) *ProfileDeploymentStatusCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetAppliedAt sets the "applied_at" field.
func (_c *ProfileDeploymentStatusCreate) SetAppliedAt(v time.Time) *ProfileDeploymentStatusCreate {
	_c.mutation.SetAppliedAt(v)
	return _c
}

// SetNillableAppliedAt sets the "applied_at" field if the given value is not nil.
func (_c *ProfileDeploymentStatusCreate) SetNillableAppliedAt(v *time.Time) *ProfileDeploymentStatusCreate {
	if v != nil {
		_c.SetAppliedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProfileDeploymentStatusCreate) SetCreatedAt(v time.Time) *ProfileDeploymentStatusCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProfileDeploymentStatusCreate) SetNillableCreatedAt(v *time.Time) *ProfileDeploymentStatusCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProfileDeploymentStatusCreate) SetUpdatedAt(v time.Time) *ProfileDeploymentStatusCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProfileDeploymentStatusCreate) SetNillableUpdatedAt(v *time.Time) *ProfileDeploymentStatusCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProfileDeploymentStatusCreate) SetID(v uint) *ProfileDeploymentStatusCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetProfile sets the "profile" edge to the Profile entity.
func (_c *ProfileDeploymentStatusCreate) SetProfile(v *Profile) *ProfileDeploymentStatusCreate {
	return _c.SetProfileID(v.ID)
}

// SetDevice sets the "device" edge to the Device entity.
func (_c *ProfileDeploymentStatusCreate) SetDevice(v *Device) *ProfileDeploymentStatusCreate {
	return _c.SetDeviceID(v.ID)
}

// Mutation returns the ProfileDeploymentStatusMutation object of the builder.
func (_c *ProfileDeploymentStatusCreate) Mutation() *ProfileDeploymentStatusMutation {
	return _c.mutation
}

// Save creates the ProfileDeploymentStatus in the database.
func (_c *ProfileDeploymentStatusCreate) Save(ctx context.Context) (*ProfileDeploymentStatus, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProfileDeploymentStatusCreate) SaveX(ctx context.Context) *ProfileDeploymentStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProfileDeploymentStatusCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProfileDeploymentStatusCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProfileDeploymentStatusCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := profiledeploymentstatus.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := profiledeploymentstatus.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := profiledeploymentstatus.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProfileDeploymentStatusCreate) check() error {
	if _, ok := _c.mutation.ProfileID(); !ok {
		return &ValidationError{Name: "profile_id", err: errors.New(`ent: missing required field "ProfileDeploymentStatus.profile_id"`)}
	}
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "ProfileDeploymentStatus.device_id"`)}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := profiledeploymentstatus.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "ProfileDeploymentStatus.device_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ProfileDeploymentStatus.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := profiledeploymentstatus.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProfileDeploymentStatus.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProfileDeploymentStatus.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProfileDeploymentStatus.updated_at"`)}
	}
	if len(_c.mutation.ProfileIDs()) == 0 {
		return &ValidationError{Name: "profile", err: errors.New(`ent: missing required edge "ProfileDeploymentStatus.profile"`)}
	}
	if len(_c.mutation.DeviceIDs()) == 0 {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required edge "ProfileDeploymentStatus.device"`)}
	}
	return nil
}

func (_c *ProfileDeploymentStatusCreate) sqlSave(ctx context.Context) (*ProfileDeploymentStatus, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProfileDeploymentStatusCreate) createSpec() (*ProfileDeploymentStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &ProfileDeploymentStatus{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(profiledeploymentstatus.Table, sqlgraph.NewFieldSpec(profiledeploymentstatus.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(profiledeploymentstatus.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(profiledeploymentstatus.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.AppliedAt(); ok {
		_spec.SetField(profiledeploymentstatus.FieldAppliedAt, field.TypeTime, value)
		_node.AppliedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(profiledeploymentstatus.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(profiledeploymentstatus.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profiledeploymentstatus.ProfileTable,
			Columns: []string{profiledeploymentstatus.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProfileID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   profiledeploymentstatus.DeviceTable,
			Columns: []string{profiledeploymentstatus.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeviceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProfileDeploymentStatusCreateBulk is the builder for creating many ProfileDeploymentStatus entities in bulk.
type ProfileDeploymentStatusCreateBulk struct {
	config
	err      error
	builders []*ProfileDeploymentStatusCreate
}

// Save creates the ProfileDeploymentStatus entities in the database.
func (_c *ProfileDeploymentStatusCreateBulk) Save(ctx context.Context) ([]*ProfileDeploymentStatus, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProfileDeploymentStatus, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProfileDeploymentStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProfileDeploymentStatusCreateBulk) SaveX(ctx context.Context) []*ProfileDeploymentStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProfileDeploymentStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProfileDeploymentStatusCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
