// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thienel/go-backend-template/internal/ent/device"
	"github.com/thienel/go-backend-template/internal/ent/devicegroup"
	"github.com/thienel/go-backend-template/internal/ent/predicate"
	"github.com/thienel/go-backend-template/internal/ent/profile"
	"github.com/thienel/go-backend-template/internal/ent/profileassignment"
)

// ProfileAssignmentUpdate is the builder for updating ProfileAssignment entities.
type ProfileAssignmentUpdate struct {
	config
	hooks    []Hook
	mutation *ProfileAssignmentMutation
}

// Where appends a list predicates to the ProfileAssignmentUpdate builder.
func (_u *ProfileAssignmentUpdate) Where(ps ...predicate.ProfileAssignment) *ProfileAssignmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *ProfileAssignmentUpdate) SetProfileID(v uint) *ProfileAssignmentUpdate {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *ProfileAssignmentUpdate) SetNillableProfileID(v *uint) *ProfileAssignmentUpdate {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *ProfileAssignmentUpdate) SetTargetType(v profileassignment.TargetType) *ProfileAssignmentUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *ProfileAssignmentUpdate) SetNillableTargetType(v *profileassignment.TargetType) *ProfileAssignmentUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *ProfileAssignmentUpdate) SetDeviceID(v string) *ProfileAssignmentUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *ProfileAssignmentUpdate) SetNillableDeviceID(v *string) *ProfileAssignmentUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// ClearDeviceID clears the value of the "device_id" field.
func (_u *ProfileAssignmentUpdate) ClearDeviceID() *ProfileAssignmentUpdate {
	_u.mutation.ClearDeviceID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ProfileAssignmentUpdate) SetGroupID(v uint) *ProfileAssignmentUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ProfileAssignmentUpdate) SetNillableGroupID(v *uint) *ProfileAssignmentUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ProfileAssignmentUpdate) ClearGroupID() *ProfileAssignmentUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetScheduleType sets the "schedule_type" field.
func (_u *ProfileAssignmentUpdate) SetScheduleType(v profileassignment.ScheduleType) *ProfileAssignmentUpdate {
	_u.mutation.SetScheduleType(v)
	return _u
}

// SetNillableScheduleType sets the "schedule_type" field if the given value is not nil.
func (_u *ProfileAssignmentUpdate) SetNillableScheduleType(v *profileassignment.ScheduleType) *ProfileAssignmentUpdate {
	if v != nil {
		_u.SetScheduleType(*v)
	}
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *ProfileAssignmentUpdate) SetScheduledAt(v time.Time) *ProfileAssignmentUpdate {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *ProfileAssignmentUpdate) SetNillableScheduledAt(v *time.Time) *ProfileAssignmentUpdate {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// ClearScheduledAt clears the value of the "scheduled_at" field.
func (_u *ProfileAssignmentUpdate) ClearScheduledAt() *ProfileAssignmentUpdate {
	_u.mutation.ClearScheduledAt()
	return _u
}

// SetProfile sets the "profile" edge to the Profile entity.
func (_u *ProfileAssignmentUpdate) SetProfile(v *Profile) *ProfileAssignmentUpdate {
	return _u.SetProfileID(v.ID)
}

// SetDevice sets the "device" edge to the Device entity.
func (_u *ProfileAssignmentUpdate) SetDevice(v *Device) *ProfileAssignmentUpdate {
	return _u.SetDeviceID(v.ID)
}

// SetGroup sets the "group" edge to the DeviceGroup entity.
func (_u *ProfileAssignmentUpdate) SetGroup(v *DeviceGroup) *ProfileAssignmentUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the ProfileAssignmentMutation object of the builder.
func (_u *ProfileAssignmentUpdate) Mutation() *ProfileAssignmentMutation {
	return _u.mutation
}

// ClearProfile clears the "profile" edge to the Profile entity.
func (_u *ProfileAssignmentUpdate) ClearProfile() *ProfileAssignmentUpdate {
	_u.mutation.ClearProfile()
	return _u
}

// ClearDevice clears the "device" edge to the Device entity.
func (_u *ProfileAssignmentUpdate) ClearDevice() *ProfileAssignmentUpdate {
	_u.mutation.ClearDevice()
	return _u
}

// ClearGroup clears the "group" edge to the DeviceGroup entity.
func (_u *ProfileAssignmentUpdate) ClearGroup() *ProfileAssignmentUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProfileAssignmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProfileAssignmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProfileAssignmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProfileAssignmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProfileAssignmentUpdate) check() error {
	if v, ok := _u.mutation.TargetType(); ok {
		if err := profileassignment.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.target_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScheduleType(); ok {
		if err := profileassignment.ScheduleTypeValidator(v); err != nil {
			return &ValidationError{Name: "schedule_type", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.schedule_type": %w`, err)}
		}
	}
	if _u.mutation.ProfileCleared() && len(_u.mutation.ProfileIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProfileAssignment.profile"`)
	}
	return nil
}

func (_u *ProfileAssignmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(profileassignment.Table, profileassignment.Columns, sqlgraph.NewFieldSpec(profileassignment.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(profileassignment.FieldTargetType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScheduleType(); ok {
		_spec.SetField(profileassignment.FieldScheduleType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(profileassignment.FieldScheduledAt, field.TypeTime, value)
	}
	if _u.mutation.ScheduledAtCleared() {
		_spec.ClearField(profileassignment.FieldScheduledAt, field.TypeTime)
	}
	if _u.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profileassignment.ProfileTable,
			Columns: []string{profileassignment.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profileassignment.ProfileTable,
			Columns: []string{profileassignment.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   profileassignment.DeviceTable,
			Columns: []string{profileassignment.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   profileassignment.DeviceTable,
			Columns: []string{profileassignment.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   profileassignment.GroupTable,
			Columns: []string{profileassignment.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicegroup.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   profileassignment.GroupTable,
			Columns: []string{profileassignment.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicegroup.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profileassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProfileAssignmentUpdateOne is the builder for updating a single ProfileAssignment entity.
type ProfileAssignmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfileAssignmentMutation
}

// SetProfileID sets the "profile_id" field.
func (_u *ProfileAssignmentUpdateOne) SetProfileID(v uint) *ProfileAssignmentUpdateOne {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *ProfileAssignmentUpdateOne) SetNillableProfileID(v *uint) *ProfileAssignmentUpdateOne {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *ProfileAssignmentUpdateOne) SetTargetType(v profileassignment.TargetType) *ProfileAssignmentUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *ProfileAssignmentUpdateOne) SetNillableTargetType(v *profileassignment.TargetType) *ProfileAssignmentUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *ProfileAssignmentUpdateOne) SetDeviceID(v string) *ProfileAssignmentUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *ProfileAssignmentUpdateOne) SetNillableDeviceID(v *string) *ProfileAssignmentUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// ClearDeviceID clears the value of the "device_id" field.
func (_u *ProfileAssignmentUpdateOne) ClearDeviceID() *ProfileAssignmentUpdateOne {
	_u.mutation.ClearDeviceID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ProfileAssignmentUpdateOne) SetGroupID(v uint) *ProfileAssignmentUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ProfileAssignmentUpdateOne) SetNillableGroupID(v *uint) *ProfileAssignmentUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ProfileAssignmentUpdateOne) ClearGroupID() *ProfileAssignmentUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetScheduleType sets the "schedule_type" field.
func (_u *ProfileAssignmentUpdateOne) SetScheduleType(v profileassignment.ScheduleType) *ProfileAssignmentUpdateOne {
	_u.mutation.SetScheduleType(v)
	return _u
}

// SetNillableScheduleType sets the "schedule_type" field if the given value is not nil.
func (_u *ProfileAssignmentUpdateOne) SetNillableScheduleType(v *profileassignment.ScheduleType) *ProfileAssignmentUpdateOne {
	if v != nil {
		_u.SetScheduleType(*v)
	}
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *ProfileAssignmentUpdateOne) SetScheduledAt(v time.Time) *ProfileAssignmentUpdateOne {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *ProfileAssignmentUpdateOne) SetNillableScheduledAt(v *time.Time) *ProfileAssignmentUpdateOne {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// ClearScheduledAt clears the value of the "scheduled_at" field.
func (_u *ProfileAssignmentUpdateOne) ClearScheduledAt() *ProfileAssignmentUpdateOne {
	_u.mutation.ClearScheduledAt()
	return _u
}

// SetProfile sets the "profile" edge to the Profile entity.
func (_u *ProfileAssignmentUpdateOne) SetProfile(v *Profile) *ProfileAssignmentUpdateOne {
	return _u.SetProfileID(v.ID)
}

// SetDevice sets the "device" edge to the Device entity.
func (_u *ProfileAssignmentUpdateOne) SetDevice(v *Device) *ProfileAssignmentUpdateOne {
	return _u.SetDeviceID(v.ID)
}

// SetGroup sets the "group" edge to the DeviceGroup entity.
func (_u *ProfileAssignmentUpdateOne) SetGroup(v *DeviceGroup) *ProfileAssignmentUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the ProfileAssignmentMutation object of the builder.
func (_u *ProfileAssignmentUpdateOne) Mutation() *ProfileAssignmentMutation {
	return _u.mutation
}

// ClearProfile clears the "profile" edge to the Profile entity.
func (_u *ProfileAssignmentUpdateOne) ClearProfile() *ProfileAssignmentUpdateOne {
	_u.mutation.ClearProfile()
	return _u
}

// ClearDevice clears the "device" edge to the Device entity.
func (_u *ProfileAssignmentUpdateOne) ClearDevice() *ProfileAssignmentUpdateOne {
	_u.mutation.ClearDevice()
	return _u
}

// ClearGroup clears the "group" edge to the DeviceGroup entity.
func (_u *ProfileAssignmentUpdateOne) ClearGroup() *ProfileAssignmentUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the ProfileAssignmentUpdate builder.
func (_u *ProfileAssignmentUpdateOne) Where(ps ...predicate.ProfileAssignment) *ProfileAssignmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProfileAssignmentUpdateOne) Select(field string, fields ...string) *ProfileAssignmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProfileAssignment entity.
func (_u *ProfileAssignmentUpdateOne) Save(ctx context.Context) (*ProfileAssignment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProfileAssignmentUpdateOne) SaveX(ctx context.Context) *ProfileAssignment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProfileAssignmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProfileAssignmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProfileAssignmentUpdateOne) check() error {
	if v, ok := _u.mutation.TargetType(); ok {
		if err := profileassignment.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.target_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScheduleType(); ok {
		if err := profileassignment.ScheduleTypeValidator(v); err != nil {
			return &ValidationError{Name: "schedule_type", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.schedule_type": %w`, err)}
		}
	}
	if _u.mutation.ProfileCleared() && len(_u.mutation.ProfileIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProfileAssignment.profile"`)
	}
	return nil
}

func (_u *ProfileAssignmentUpdateOne) sqlSave(ctx context.Context) (_node *ProfileAssignment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(profileassignment.Table, profileassignment.Columns, sqlgraph.NewFieldSpec(profileassignment.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProfileAssignment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profileassignment.FieldID)
		for _, f := range fields {
			if !profileassignment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != profileassignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(profileassignment.FieldTargetType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScheduleType(); ok {
		_spec.SetField(profileassignment.FieldScheduleType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(profileassignment.FieldScheduledAt, field.TypeTime, value)
	}
	if _u.mutation.ScheduledAtCleared() {
		_spec.ClearField(profileassignment.FieldScheduledAt, field.TypeTime)
	}
	if _u.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profileassignment.ProfileTable,
			Columns: []string{profileassignment.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profileassignment.ProfileTable,
			Columns: []string{profileassignment.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   profileassignment.DeviceTable,
			Columns: []string{profileassignment.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   profileassignment.DeviceTable,
			Columns: []string{profileassignment.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   profileassignment.GroupTable,
			Columns: []string{profileassignment.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicegroup.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   profileassignment.GroupTable,
			Columns: []string{profileassignment.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicegroup.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProfileAssignment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profileassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
