// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/thienel/go-backend-template/internal/ent/profile"
)

// Profile is the model entity for the Profile schema.
type Profile struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform profile.Platform `json:"platform,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope profile.Scope `json:"scope,omitempty"`
	// Status holds the value of the "status" field.
	Status profile.Status `json:"status,omitempty"`
	// SecuritySettings holds the value of the "security_settings" field.
	SecuritySettings map[string]any `json:"security_settings,omitempty"`
	// NetworkConfig holds the value of the "network_config" field.
	NetworkConfig map[string]any `json:"network_config,omitempty"`
	// Restrictions holds the value of the "restrictions" field.
	Restrictions map[string]any `json:"restrictions,omitempty"`
	// ContentFilter holds the value of the "content_filter" field.
	ContentFilter map[string]any `json:"content_filter,omitempty"`
	// ComplianceRules holds the value of the "compliance_rules" field.
	ComplianceRules map[string]any `json:"compliance_rules,omitempty"`
	// Payloads holds the value of the "payloads" field.
	Payloads map[string]any `json:"payloads,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProfileQuery when eager-loading is set.
	Edges        ProfileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProfileEdges holds the relations/edges for other nodes in the graph.
type ProfileEdges struct {
	// DeviceGroups holds the value of the device_groups edge.
	DeviceGroups []*DeviceGroup `json:"device_groups,omitempty"`
	// Assignments holds the value of the assignments edge.
	Assignments []*ProfileAssignment `json:"assignments,omitempty"`
	// Versions holds the value of the versions edge.
	Versions []*ProfileVersion `json:"versions,omitempty"`
	// DeploymentStatuses holds the value of the deployment_statuses edge.
	DeploymentStatuses []*ProfileDeploymentStatus `json:"deployment_statuses,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// DeviceGroupsOrErr returns the DeviceGroups value or an error if the edge
// was not loaded in eager-loading.
func (e ProfileEdges) DeviceGroupsOrErr() ([]*DeviceGroup, error) {
	if e.loadedTypes[0] {
		return e.DeviceGroups, nil
	}
	return nil, &NotLoadedError{edge: "device_groups"}
}

// AssignmentsOrErr returns the Assignments value or an error if the edge
// was not loaded in eager-loading.
func (e ProfileEdges) AssignmentsOrErr() ([]*ProfileAssignment, error) {
	if e.loadedTypes[1] {
		return e.Assignments, nil
	}
	return nil, &NotLoadedError{edge: "assignments"}
}

// VersionsOrErr returns the Versions value or an error if the edge
// was not loaded in eager-loading.
func (e ProfileEdges) VersionsOrErr() ([]*ProfileVersion, error) {
	if e.loadedTypes[2] {
		return e.Versions, nil
	}
	return nil, &NotLoadedError{edge: "versions"}
}

// DeploymentStatusesOrErr returns the DeploymentStatuses value or an error if the edge
// was not loaded in eager-loading.
func (e ProfileEdges) DeploymentStatusesOrErr() ([]*ProfileDeploymentStatus, error) {
	if e.loadedTypes[3] {
		return e.DeploymentStatuses, nil
	}
	return nil, &NotLoadedError{edge: "deployment_statuses"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Profile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case profile.FieldSecuritySettings, profile.FieldNetworkConfig, profile.FieldRestrictions, profile.FieldContentFilter, profile.FieldComplianceRules, profile.FieldPayloads:
			values[i] = new([]byte)
		case profile.FieldID, profile.FieldVersion:
			values[i] = new(sql.NullInt64)
		case profile.FieldName, profile.FieldPlatform, profile.FieldScope, profile.FieldStatus:
			values[i] = new(sql.NullString)
		case profile.FieldCreatedAt, profile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Profile fields.
func (_m *Profile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case profile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case profile.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case profile.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = profile.Platform(value.String)
			}
		case profile.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = profile.Scope(value.String)
			}
		case profile.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = profile.Status(value.String)
			}
		case profile.FieldSecuritySettings:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field security_settings", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SecuritySettings); err != nil {
					return fmt.Errorf("unmarshal field security_settings: %w", err)
				}
			}
		case profile.FieldNetworkConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field network_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NetworkConfig); err != nil {
					return fmt.Errorf("unmarshal field network_config: %w", err)
				}
			}
		case profile.FieldRestrictions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field restrictions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Restrictions); err != nil {
					return fmt.Errorf("unmarshal field restrictions: %w", err)
				}
			}
		case profile.FieldContentFilter:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field content_filter", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ContentFilter); err != nil {
					return fmt.Errorf("unmarshal field content_filter: %w", err)
				}
			}
		case profile.FieldComplianceRules:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field compliance_rules", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ComplianceRules); err != nil {
					return fmt.Errorf("unmarshal field compliance_rules: %w", err)
				}
			}
		case profile.FieldPayloads:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payloads", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payloads); err != nil {
					return fmt.Errorf("unmarshal field payloads: %w", err)
				}
			}
		case profile.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case profile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case profile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Profile.
// This includes values selected through modifiers, order, etc.
func (_m *Profile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDeviceGroups queries the "device_groups" edge of the Profile entity.
func (_m *Profile) QueryDeviceGroups() *DeviceGroupQuery {
	return NewProfileClient(_m.config).QueryDeviceGroups(_m)
}

// QueryAssignments queries the "assignments" edge of the Profile entity.
func (_m *Profile) QueryAssignments() *ProfileAssignmentQuery {
	return NewProfileClient(_m.config).QueryAssignments(_m)
}

// QueryVersions queries the "versions" edge of the Profile entity.
func (_m *Profile) QueryVersions() *ProfileVersionQuery {
	return NewProfileClient(_m.config).QueryVersions(_m)
}

// QueryDeploymentStatuses queries the "deployment_statuses" edge of the Profile entity.
func (_m *Profile) QueryDeploymentStatuses() *ProfileDeploymentStatusQuery {
	return NewProfileClient(_m.config).QueryDeploymentStatuses(_m)
}

// Update returns a builder for updating this Profile.
// Note that you need to call Profile.Unwrap() before calling this method if this Profile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Profile) Update() *ProfileUpdateOne {
	return NewProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Profile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Profile) Unwrap() *Profile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Profile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Profile) String() string {
	var builder strings.Builder
	builder.WriteString("Profile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(fmt.Sprintf("%v", _m.Platform))
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scope))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("security_settings=")
	builder.WriteString(fmt.Sprintf("%v", _m.SecuritySettings))
	builder.WriteString(", ")
	builder.WriteString("network_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.NetworkConfig))
	builder.WriteString(", ")
	builder.WriteString("restrictions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Restrictions))
	builder.WriteString(", ")
	builder.WriteString("content_filter=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContentFilter))
	builder.WriteString(", ")
	builder.WriteString("compliance_rules=")
	builder.WriteString(fmt.Sprintf("%v", _m.ComplianceRules))
	builder.WriteString(", ")
	builder.WriteString("payloads=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payloads))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Profiles is a parsable slice of Profile.
type Profiles []*Profile
