-- Create "dep_names" table
CREATE TABLE "public"."dep_names" (
  "name" character varying NOT NULL,
  "consumer_key" text NULL,
  "consumer_secret" text NULL,
  "access_token" text NULL,
  "access_secret" text NULL,
  "access_token_expiry" timestamptz NULL,
  "config_base_url" character varying NULL,
  "tokenpki_cert_pem" text NULL,
  "tokenpki_key_pem" text NULL,
  "syncer_cursor" character varying NULL,
  "assigner_profile_uuid" text NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("name")
);
-- Create "dep_profiles" table
CREATE TABLE "public"."dep_profiles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "profile_name" character varying NOT NULL,
  "profile_uuid" character varying NULL,
  "allow_pairing" boolean NOT NULL DEFAULT true,
  "anchor_certs" jsonb NULL,
  "auto_advance_setup" boolean NOT NULL DEFAULT false,
  "await_device_configured" boolean NOT NULL DEFAULT false,
  "configuration_web_url" character varying NULL,
  "department" character varying NULL,
  "devices" jsonb NULL,
  "do_not_use_profile_from_backup" boolean NOT NULL DEFAULT false,
  "is_return_to_service" boolean NOT NULL DEFAULT false,
  "is_mandatory" boolean NOT NULL DEFAULT false,
  "is_mdm_removable" boolean NOT NULL DEFAULT true,
  "is_multi_user" boolean NOT NULL DEFAULT false,
  "is_supervised" boolean NOT NULL DEFAULT false,
  "language" character varying NULL,
  "org_magic" character varying NULL,
  "region" character varying NULL,
  "skip_setup_items" jsonb NULL,
  "supervising_host_certs" jsonb NULL,
  "support_email_address" character varying NULL,
  "support_phone_number" character varying NULL,
  "url" character varying NULL,
  "profile_data" jsonb NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "dep_profiles_profile_name_key" to table: "dep_profiles"
CREATE UNIQUE INDEX "dep_profiles_profile_name_key" ON "public"."dep_profiles" ("profile_name");
-- Create index "dep_profiles_profile_uuid_key" to table: "dep_profiles"
CREATE UNIQUE INDEX "dep_profiles_profile_uuid_key" ON "public"."dep_profiles" ("profile_uuid");
-- Create "portal_users" table
CREATE TABLE "public"."portal_users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" character varying NOT NULL,
  "email" character varying NOT NULL,
  "password" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'ACTIVE',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "portal_users_email_key" to table: "portal_users"
CREATE UNIQUE INDEX "portal_users_email_key" ON "public"."portal_users" ("email");
-- Create index "portal_users_username_key" to table: "portal_users"
CREATE UNIQUE INDEX "portal_users_username_key" ON "public"."portal_users" ("username");
-- Create "push_certs" table
CREATE TABLE "public"."push_certs" (
  "topic" character varying NOT NULL,
  "cert_pem" text NOT NULL,
  "key_pem" text NOT NULL,
  "stale_token" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("topic")
);
-- Create "devices" table
CREATE TABLE "public"."devices" (
  "id" character varying(255) NOT NULL,
  "serial_number" character varying(127) NULL,
  "model" character varying(255) NULL,
  "is_enrolled" boolean NOT NULL DEFAULT false,
  "name" character varying NULL,
  "last_sync" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "owner_id" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "devices_portal_users_devices" FOREIGN KEY ("owner_id") REFERENCES "public"."portal_users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "devices_serial_number_key" to table: "devices"
CREATE UNIQUE INDEX "devices_serial_number_key" ON "public"."devices" ("serial_number");
