-- Create "portal_push_certs" table
CREATE TABLE "public"."portal_push_certs" (
  "topic" character varying NOT NULL,
  "cert_pem" text NOT NULL,
  "key_pem" text NOT NULL,
  "stale_token" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("topic")
);
-- Create "portal_dep_names" table
CREATE TABLE "public"."portal_dep_names" (
  "name" character varying NOT NULL,
  "consumer_key" text NULL,
  "consumer_secret" text NULL,
  "access_token" text NULL,
  "access_secret" text NULL,
  "access_token_expiry" timestamptz NULL,
  "config_base_url" character varying NULL,
  "tokenpki_cert_pem" text NULL,
  "tokenpki_key_pem" text NULL,
  "syncer_cursor" character varying NULL,
  "assigner_profile_uuid" text NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("name")
);
-- Create "applications" table
CREATE TABLE "public"."applications" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "bundle_id" character varying NOT NULL,
  "platform" character varying NOT NULL,
  "type" character varying NOT NULL DEFAULT 'app_store',
  "description" character varying NULL,
  "icon_url" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "applications_bundle_id_key" to table: "applications"
CREATE UNIQUE INDEX "applications_bundle_id_key" ON "public"."applications" ("bundle_id");
-- Create "dep_profiles" table
CREATE TABLE "public"."dep_profiles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "profile_name" character varying NOT NULL,
  "profile_uuid" character varying NULL,
  "allow_pairing" boolean NOT NULL DEFAULT true,
  "anchor_certs" jsonb NULL,
  "auto_advance_setup" boolean NOT NULL DEFAULT false,
  "await_device_configured" boolean NOT NULL DEFAULT false,
  "configuration_web_url" character varying NULL,
  "department" character varying NULL,
  "devices" jsonb NULL,
  "do_not_use_profile_from_backup" boolean NOT NULL DEFAULT false,
  "is_return_to_service" boolean NOT NULL DEFAULT false,
  "is_mandatory" boolean NOT NULL DEFAULT false,
  "is_mdm_removable" boolean NOT NULL DEFAULT true,
  "is_multi_user" boolean NOT NULL DEFAULT false,
  "is_supervised" boolean NOT NULL DEFAULT false,
  "language" character varying NULL,
  "org_magic" character varying NULL,
  "region" character varying NULL,
  "skip_setup_items" jsonb NULL,
  "supervising_host_certs" jsonb NULL,
  "support_email_address" character varying NULL,
  "support_phone_number" character varying NULL,
  "url" character varying NULL,
  "profile_data" jsonb NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "dep_profiles_profile_name_key" to table: "dep_profiles"
CREATE UNIQUE INDEX "dep_profiles_profile_name_key" ON "public"."dep_profiles" ("profile_name");
-- Create index "dep_profiles_profile_uuid_key" to table: "dep_profiles"
CREATE UNIQUE INDEX "dep_profiles_profile_uuid_key" ON "public"."dep_profiles" ("profile_uuid");
-- Create "settings" table
CREATE TABLE "public"."settings" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "key" character varying NOT NULL,
  "value" text NOT NULL,
  "description" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "settings_key_key" to table: "settings"
CREATE UNIQUE INDEX "settings_key_key" ON "public"."settings" ("key");
-- Create "alert_rules" table
CREATE TABLE "public"."alert_rules" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "description" character varying NULL,
  "condition" jsonb NULL,
  "actions" jsonb NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "alerts" table
CREATE TABLE "public"."alerts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "severity" character varying NOT NULL DEFAULT 'medium',
  "title" character varying NOT NULL,
  "type" character varying NOT NULL DEFAULT 'security',
  "status" character varying NOT NULL DEFAULT 'open',
  "device_id" character varying NULL,
  "user_id" bigint NULL,
  "details" jsonb NULL,
  "created_at" timestamptz NOT NULL,
  "acknowledged_at" timestamptz NULL,
  "resolved_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create "app_versions" table
CREATE TABLE "public"."app_versions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "version" character varying NOT NULL,
  "build_number" character varying NOT NULL,
  "minimum_os_version" character varying NULL,
  "file_url" character varying NULL,
  "size" bigint NULL,
  "metadata" jsonb NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "application_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "app_versions_applications_versions" FOREIGN KEY ("application_id") REFERENCES "public"."applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "app_deployments" table
CREATE TABLE "public"."app_deployments" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "target_type" character varying NOT NULL,
  "target_id" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'pending',
  "error_message" character varying NULL,
  "installed_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "app_version_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "app_deployments_app_versions_deployments" FOREIGN KEY ("app_version_id") REFERENCES "public"."app_versions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "device_groups" table
CREATE TABLE "public"."device_groups" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "description" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "portal_users" table
CREATE TABLE "public"."portal_users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" character varying NOT NULL,
  "email" character varying NOT NULL,
  "password" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'ACTIVE',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "portal_users_email_key" to table: "portal_users"
CREATE UNIQUE INDEX "portal_users_email_key" ON "public"."portal_users" ("email");
-- Create index "portal_users_username_key" to table: "portal_users"
CREATE UNIQUE INDEX "portal_users_username_key" ON "public"."portal_users" ("username");
-- Create "portal_devices" table
CREATE TABLE "public"."portal_devices" (
  "id" character varying(255) NOT NULL,
  "udid" character varying(255) NULL,
  "serial_number" character varying(127) NULL,
  "model" character varying(255) NULL,
  "is_enrolled" boolean NOT NULL DEFAULT false,
  "name" character varying NULL,
  "last_sync" timestamptz NULL,
  "platform" character varying NULL DEFAULT 'other',
  "status" character varying NULL DEFAULT 'pending',
  "compliance_status" character varying NULL DEFAULT 'unknown',
  "os_version" character varying NULL,
  "device_type" character varying NULL,
  "last_seen" timestamptz NULL,
  "enrolled_at" timestamptz NULL,
  "mac_address" character varying NULL,
  "ip_address" character varying NULL,
  "battery_level" double precision NULL,
  "storage_capacity" bigint NULL,
  "storage_used" bigint NULL,
  "is_jailbroken" boolean NOT NULL DEFAULT false,
  "enrollment_type" character varying NULL DEFAULT 'unknown',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "owner_id" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "portal_devices_portal_users_devices" FOREIGN KEY ("owner_id") REFERENCES "public"."portal_users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "portal_devices_serial_number_key" to table: "portal_devices"
CREATE UNIQUE INDEX "portal_devices_serial_number_key" ON "public"."portal_devices" ("serial_number");
-- Create index "portal_devices_udid_key" to table: "portal_devices"
CREATE UNIQUE INDEX "portal_devices_udid_key" ON "public"."portal_devices" ("udid");
-- Create "device_group_devices" table
CREATE TABLE "public"."device_group_devices" (
  "device_group_id" bigint NOT NULL,
  "device_id" character varying(255) NOT NULL,
  PRIMARY KEY ("device_group_id", "device_id"),
  CONSTRAINT "device_group_devices_device_group_id" FOREIGN KEY ("device_group_id") REFERENCES "public"."device_groups" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "device_group_devices_device_id" FOREIGN KEY ("device_id") REFERENCES "public"."portal_devices" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "profiles" table
CREATE TABLE "public"."profiles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "platform" character varying NOT NULL DEFAULT 'all',
  "scope" character varying NOT NULL DEFAULT 'device',
  "status" character varying NOT NULL DEFAULT 'draft',
  "security_settings" jsonb NULL,
  "network_config" jsonb NULL,
  "restrictions" jsonb NULL,
  "content_filter" jsonb NULL,
  "compliance_rules" jsonb NULL,
  "payloads" jsonb NULL,
  "version" bigint NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "profiles_name_key" to table: "profiles"
CREATE UNIQUE INDEX "profiles_name_key" ON "public"."profiles" ("name");
-- Create "device_group_profiles" table
CREATE TABLE "public"."device_group_profiles" (
  "device_group_id" bigint NOT NULL,
  "profile_id" bigint NOT NULL,
  PRIMARY KEY ("device_group_id", "profile_id"),
  CONSTRAINT "device_group_profiles_device_group_id" FOREIGN KEY ("device_group_id") REFERENCES "public"."device_groups" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "device_group_profiles_profile_id" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "payload_property_definitions" table
CREATE TABLE "public"."payload_property_definitions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "payload_type" character varying NOT NULL,
  "key" character varying NOT NULL,
  "value_type" character varying NOT NULL,
  "default_value" jsonb NULL,
  "enum_values" jsonb NULL,
  "deprecated" boolean NOT NULL DEFAULT false,
  "description" character varying NULL,
  "nested_reference" character varying NULL,
  "items_type" character varying NULL,
  "items_reference" character varying NULL,
  "is_nested" boolean NOT NULL DEFAULT false,
  "order_index" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "payloadpropertydefinition_payload_type_key" to table: "payload_property_definitions"
CREATE UNIQUE INDEX "payloadpropertydefinition_payload_type_key" ON "public"."payload_property_definitions" ("payload_type", "key");
-- Create "mobile_configs" table
CREATE TABLE "public"."mobile_configs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "payload_identifier" character varying NOT NULL,
  "payload_type" character varying NOT NULL,
  "payload_display_name" character varying NOT NULL,
  "payload_description" character varying NULL,
  "payload_organization" character varying NULL,
  "payload_uuid" character varying NOT NULL,
  "payload_version" bigint NOT NULL DEFAULT 1,
  "payload_removal_disallowed" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "mobile_configs_name_key" to table: "mobile_configs"
CREATE UNIQUE INDEX "mobile_configs_name_key" ON "public"."mobile_configs" ("name");
-- Create index "mobile_configs_payload_identifier_key" to table: "mobile_configs"
CREATE UNIQUE INDEX "mobile_configs_payload_identifier_key" ON "public"."mobile_configs" ("payload_identifier");
-- Create index "mobileconfig_payload_identifier" to table: "mobile_configs"
CREATE UNIQUE INDEX "mobileconfig_payload_identifier" ON "public"."mobile_configs" ("payload_identifier");
-- Create "payloads" table
CREATE TABLE "public"."payloads" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "payload_description" character varying NULL,
  "payload_display_name" character varying NOT NULL,
  "payload_identifier" character varying NOT NULL,
  "payload_organization" character varying NULL,
  "payload_type" character varying NOT NULL,
  "payload_uuid" character varying NOT NULL,
  "payload_version" bigint NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  "mobile_config_payloads" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "payloads_mobile_configs_payloads" FOREIGN KEY ("mobile_config_payloads") REFERENCES "public"."mobile_configs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "payloads_payload_identifier_key" to table: "payloads"
CREATE UNIQUE INDEX "payloads_payload_identifier_key" ON "public"."payloads" ("payload_identifier");
-- Create "payload_properties" table
CREATE TABLE "public"."payload_properties" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "value_json" jsonb NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  "payload_properties" bigint NOT NULL,
  "payload_property_definition_properties" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "payload_properties_payload_property_definitions_properties" FOREIGN KEY ("payload_property_definition_properties") REFERENCES "public"."payload_property_definitions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "payload_properties_payloads_properties" FOREIGN KEY ("payload_properties") REFERENCES "public"."payloads" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "profile_assignments" table
CREATE TABLE "public"."profile_assignments" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "target_type" character varying NOT NULL,
  "schedule_type" character varying NOT NULL DEFAULT 'immediate',
  "scheduled_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "profile_id" bigint NOT NULL,
  "device_id" character varying(255) NULL,
  "group_id" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "profile_assignments_device_groups_group" FOREIGN KEY ("group_id") REFERENCES "public"."device_groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "profile_assignments_portal_devices_device" FOREIGN KEY ("device_id") REFERENCES "public"."portal_devices" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "profile_assignments_profiles_assignments" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "profile_deployment_statuses" table
CREATE TABLE "public"."profile_deployment_statuses" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "status" character varying NOT NULL DEFAULT 'pending',
  "error_message" character varying NULL,
  "applied_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "profile_id" bigint NOT NULL,
  "device_id" character varying(255) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "profile_deployment_statuses_portal_devices_device" FOREIGN KEY ("device_id") REFERENCES "public"."portal_devices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "profile_deployment_statuses_profiles_deployment_statuses" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "profile_versions" table
CREATE TABLE "public"."profile_versions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "version" bigint NOT NULL,
  "data" jsonb NULL,
  "change_notes" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "profile_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "profile_versions_profiles_versions" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
