// Code generated by ent, DO NOT EDIT.

package apnsconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the apnsconfig type in the database.
	Label = "apns_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTopic holds the string denoting the topic field in the database.
	FieldTopic = "topic"
	// FieldCertFilePath holds the string denoting the cert_file_path field in the database.
	FieldCertFilePath = "cert_file_path"
	// FieldKeyFilePath holds the string denoting the key_file_path field in the database.
	FieldKeyFilePath = "key_file_path"
	// FieldExpiry holds the string denoting the expiry field in the database.
	FieldExpiry = "expiry"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the apnsconfig in the database.
	Table = "apns_configs"
)

// Columns holds all SQL columns for apnsconfig fields.
var Columns = []string{
	FieldID,
	FieldTopic,
	FieldCertFilePath,
	FieldKeyFilePath,
	FieldExpiry,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TopicValidator is a validator for the "topic" field. It is called by the builders before save.
	TopicValidator func(string) error
	// CertFilePathValidator is a validator for the "cert_file_path" field. It is called by the builders before save.
	CertFilePathValidator func(string) error
	// KeyFilePathValidator is a validator for the "key_file_path" field. It is called by the builders before save.
	KeyFilePathValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the APNSConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTopic orders the results by the topic field.
func ByTopic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTopic, opts...).ToFunc()
}

// ByCertFilePath orders the results by the cert_file_path field.
func ByCertFilePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCertFilePath, opts...).ToFunc()
}

// ByKeyFilePath orders the results by the key_file_path field.
func ByKeyFilePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyFilePath, opts...).ToFunc()
}

// ByExpiry orders the results by the expiry field.
func ByExpiry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiry, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
