// Code generated by ent, DO NOT EDIT.

package payloadpropertydefinition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the payloadpropertydefinition type in the database.
	Label = "payload_property_definition"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPayloadType holds the string denoting the payload_type field in the database.
	FieldPayloadType = "payload_type"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldValueType holds the string denoting the value_type field in the database.
	FieldValueType = "value_type"
	// FieldDefaultValue holds the string denoting the default_value field in the database.
	FieldDefaultValue = "default_value"
	// FieldEnumValues holds the string denoting the enum_values field in the database.
	FieldEnumValues = "enum_values"
	// FieldDeprecated holds the string denoting the deprecated field in the database.
	FieldDeprecated = "deprecated"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldNestedReference holds the string denoting the nested_reference field in the database.
	FieldNestedReference = "nested_reference"
	// FieldItemsType holds the string denoting the items_type field in the database.
	FieldItemsType = "items_type"
	// FieldItemsReference holds the string denoting the items_reference field in the database.
	FieldItemsReference = "items_reference"
	// FieldIsNested holds the string denoting the is_nested field in the database.
	FieldIsNested = "is_nested"
	// FieldOrderIndex holds the string denoting the order_index field in the database.
	FieldOrderIndex = "order_index"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeProperties holds the string denoting the properties edge name in mutations.
	EdgeProperties = "properties"
	// Table holds the table name of the payloadpropertydefinition in the database.
	Table = "payload_property_definitions"
	// PropertiesTable is the table that holds the properties relation/edge.
	PropertiesTable = "payload_properties"
	// PropertiesInverseTable is the table name for the PayloadProperty entity.
	// It exists in this package in order to avoid circular dependency with the "payloadproperty" package.
	PropertiesInverseTable = "payload_properties"
	// PropertiesColumn is the table column denoting the properties relation/edge.
	PropertiesColumn = "payload_property_definition_properties"
)

// Columns holds all SQL columns for payloadpropertydefinition fields.
var Columns = []string{
	FieldID,
	FieldPayloadType,
	FieldKey,
	FieldValueType,
	FieldDefaultValue,
	FieldEnumValues,
	FieldDeprecated,
	FieldDescription,
	FieldNestedReference,
	FieldItemsType,
	FieldItemsReference,
	FieldIsNested,
	FieldOrderIndex,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PayloadTypeValidator is a validator for the "payload_type" field. It is called by the builders before save.
	PayloadTypeValidator func(string) error
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// ValueTypeValidator is a validator for the "value_type" field. It is called by the builders before save.
	ValueTypeValidator func(string) error
	// DefaultDeprecated holds the default value on creation for the "deprecated" field.
	DefaultDeprecated bool
	// DefaultIsNested holds the default value on creation for the "is_nested" field.
	DefaultIsNested bool
	// DefaultOrderIndex holds the default value on creation for the "order_index" field.
	DefaultOrderIndex int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PayloadPropertyDefinition queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPayloadType orders the results by the payload_type field.
func ByPayloadType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadType, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByValueType orders the results by the value_type field.
func ByValueType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValueType, opts...).ToFunc()
}

// ByDeprecated orders the results by the deprecated field.
func ByDeprecated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeprecated, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByNestedReference orders the results by the nested_reference field.
func ByNestedReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNestedReference, opts...).ToFunc()
}

// ByItemsType orders the results by the items_type field.
func ByItemsType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemsType, opts...).ToFunc()
}

// ByItemsReference orders the results by the items_reference field.
func ByItemsReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemsReference, opts...).ToFunc()
}

// ByIsNested orders the results by the is_nested field.
func ByIsNested(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsNested, opts...).ToFunc()
}

// ByOrderIndex orders the results by the order_index field.
func ByOrderIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderIndex, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByPropertiesCount orders the results by properties count.
func ByPropertiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPropertiesStep(), opts...)
	}
}

// ByProperties orders the results by properties terms.
func ByProperties(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPropertiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPropertiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PropertiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PropertiesTable, PropertiesColumn),
	)
}
