// Code generated by ent, DO NOT EDIT.

package payloadpropertydefinition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/thienel/go-backend-template/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldID, id))
}

// PayloadType applies equality check predicate on the "payload_type" field. It's identical to PayloadTypeEQ.
func PayloadType(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldPayloadType, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldKey, v))
}

// ValueType applies equality check predicate on the "value_type" field. It's identical to ValueTypeEQ.
func ValueType(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldValueType, v))
}

// Deprecated applies equality check predicate on the "deprecated" field. It's identical to DeprecatedEQ.
func Deprecated(v bool) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldDeprecated, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldDeletedAt, v))
}

// PayloadTypeEQ applies the EQ predicate on the "payload_type" field.
func PayloadTypeEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldPayloadType, v))
}

// PayloadTypeNEQ applies the NEQ predicate on the "payload_type" field.
func PayloadTypeNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldPayloadType, v))
}

// PayloadTypeIn applies the In predicate on the "payload_type" field.
func PayloadTypeIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldPayloadType, vs...))
}

// PayloadTypeNotIn applies the NotIn predicate on the "payload_type" field.
func PayloadTypeNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldPayloadType, vs...))
}

// PayloadTypeGT applies the GT predicate on the "payload_type" field.
func PayloadTypeGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldPayloadType, v))
}

// PayloadTypeGTE applies the GTE predicate on the "payload_type" field.
func PayloadTypeGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldPayloadType, v))
}

// PayloadTypeLT applies the LT predicate on the "payload_type" field.
func PayloadTypeLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldPayloadType, v))
}

// PayloadTypeLTE applies the LTE predicate on the "payload_type" field.
func PayloadTypeLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldPayloadType, v))
}

// PayloadTypeContains applies the Contains predicate on the "payload_type" field.
func PayloadTypeContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldPayloadType, v))
}

// PayloadTypeHasPrefix applies the HasPrefix predicate on the "payload_type" field.
func PayloadTypeHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldPayloadType, v))
}

// PayloadTypeHasSuffix applies the HasSuffix predicate on the "payload_type" field.
func PayloadTypeHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldPayloadType, v))
}

// PayloadTypeEqualFold applies the EqualFold predicate on the "payload_type" field.
func PayloadTypeEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldPayloadType, v))
}

// PayloadTypeContainsFold applies the ContainsFold predicate on the "payload_type" field.
func PayloadTypeContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldPayloadType, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldKey, v))
}

// ValueTypeEQ applies the EQ predicate on the "value_type" field.
func ValueTypeEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldValueType, v))
}

// ValueTypeNEQ applies the NEQ predicate on the "value_type" field.
func ValueTypeNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldValueType, v))
}

// ValueTypeIn applies the In predicate on the "value_type" field.
func ValueTypeIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldValueType, vs...))
}

// ValueTypeNotIn applies the NotIn predicate on the "value_type" field.
func ValueTypeNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldValueType, vs...))
}

// ValueTypeGT applies the GT predicate on the "value_type" field.
func ValueTypeGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldValueType, v))
}

// ValueTypeGTE applies the GTE predicate on the "value_type" field.
func ValueTypeGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldValueType, v))
}

// ValueTypeLT applies the LT predicate on the "value_type" field.
func ValueTypeLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldValueType, v))
}

// ValueTypeLTE applies the LTE predicate on the "value_type" field.
func ValueTypeLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldValueType, v))
}

// ValueTypeContains applies the Contains predicate on the "value_type" field.
func ValueTypeContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldValueType, v))
}

// ValueTypeHasPrefix applies the HasPrefix predicate on the "value_type" field.
func ValueTypeHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldValueType, v))
}

// ValueTypeHasSuffix applies the HasSuffix predicate on the "value_type" field.
func ValueTypeHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldValueType, v))
}

// ValueTypeEqualFold applies the EqualFold predicate on the "value_type" field.
func ValueTypeEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldValueType, v))
}

// ValueTypeContainsFold applies the ContainsFold predicate on the "value_type" field.
func ValueTypeContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldValueType, v))
}

// DefaultValueIsNil applies the IsNil predicate on the "default_value" field.
func DefaultValueIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldDefaultValue))
}

// DefaultValueNotNil applies the NotNil predicate on the "default_value" field.
func DefaultValueNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldDefaultValue))
}

// EnumValuesIsNil applies the IsNil predicate on the "enum_values" field.
func EnumValuesIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldEnumValues))
}

// EnumValuesNotNil applies the NotNil predicate on the "enum_values" field.
func EnumValuesNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldEnumValues))
}

// DeprecatedEQ applies the EQ predicate on the "deprecated" field.
func DeprecatedEQ(v bool) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldDeprecated, v))
}

// DeprecatedNEQ applies the NEQ predicate on the "deprecated" field.
func DeprecatedNEQ(v bool) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldDeprecated, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldDeletedAt))
}

// HasProperties applies the HasEdge predicate on the "properties" edge.
func HasProperties() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PropertiesTable, PropertiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPropertiesWith applies the HasEdge predicate on the "properties" edge with a given conditions (other predicates).
func HasPropertiesWith(preds ...predicate.PayloadProperty) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(func(s *sql.Selector) {
		step := newPropertiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PayloadPropertyDefinition) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PayloadPropertyDefinition) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PayloadPropertyDefinition) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.NotPredicates(p))
}
