// Code generated by ent, DO NOT EDIT.

package payloadpropertydefinition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/thienel/go-backend-template/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldID, id))
}

// PayloadType applies equality check predicate on the "payload_type" field. It's identical to PayloadTypeEQ.
func PayloadType(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldPayloadType, v))
}

// PayloadVariant applies equality check predicate on the "payload_variant" field. It's identical to PayloadVariantEQ.
func PayloadVariant(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldPayloadVariant, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldKey, v))
}

// ValueType applies equality check predicate on the "value_type" field. It's identical to ValueTypeEQ.
func ValueType(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldValueType, v))
}

// ItemsType applies equality check predicate on the "items_type" field. It's identical to ItemsTypeEQ.
func ItemsType(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldItemsType, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldDescription, v))
}

// Presence applies equality check predicate on the "presence" field. It's identical to PresenceEQ.
func Presence(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldPresence, v))
}

// Deprecated applies equality check predicate on the "deprecated" field. It's identical to DeprecatedEQ.
func Deprecated(v bool) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldDeprecated, v))
}

// IsNested applies equality check predicate on the "is_nested" field. It's identical to IsNestedEQ.
func IsNested(v bool) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldIsNested, v))
}

// NestedReference applies equality check predicate on the "nested_reference" field. It's identical to NestedReferenceEQ.
func NestedReference(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldNestedReference, v))
}

// ItemsReference applies equality check predicate on the "items_reference" field. It's identical to ItemsReferenceEQ.
func ItemsReference(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldItemsReference, v))
}

// OrderIndex applies equality check predicate on the "order_index" field. It's identical to OrderIndexEQ.
func OrderIndex(v int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldOrderIndex, v))
}

// YamlSourceFile applies equality check predicate on the "yaml_source_file" field. It's identical to YamlSourceFileEQ.
func YamlSourceFile(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldYamlSourceFile, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldDeletedAt, v))
}

// PayloadTypeEQ applies the EQ predicate on the "payload_type" field.
func PayloadTypeEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldPayloadType, v))
}

// PayloadTypeNEQ applies the NEQ predicate on the "payload_type" field.
func PayloadTypeNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldPayloadType, v))
}

// PayloadTypeIn applies the In predicate on the "payload_type" field.
func PayloadTypeIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldPayloadType, vs...))
}

// PayloadTypeNotIn applies the NotIn predicate on the "payload_type" field.
func PayloadTypeNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldPayloadType, vs...))
}

// PayloadTypeGT applies the GT predicate on the "payload_type" field.
func PayloadTypeGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldPayloadType, v))
}

// PayloadTypeGTE applies the GTE predicate on the "payload_type" field.
func PayloadTypeGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldPayloadType, v))
}

// PayloadTypeLT applies the LT predicate on the "payload_type" field.
func PayloadTypeLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldPayloadType, v))
}

// PayloadTypeLTE applies the LTE predicate on the "payload_type" field.
func PayloadTypeLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldPayloadType, v))
}

// PayloadTypeContains applies the Contains predicate on the "payload_type" field.
func PayloadTypeContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldPayloadType, v))
}

// PayloadTypeHasPrefix applies the HasPrefix predicate on the "payload_type" field.
func PayloadTypeHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldPayloadType, v))
}

// PayloadTypeHasSuffix applies the HasSuffix predicate on the "payload_type" field.
func PayloadTypeHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldPayloadType, v))
}

// PayloadTypeEqualFold applies the EqualFold predicate on the "payload_type" field.
func PayloadTypeEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldPayloadType, v))
}

// PayloadTypeContainsFold applies the ContainsFold predicate on the "payload_type" field.
func PayloadTypeContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldPayloadType, v))
}

// PayloadVariantEQ applies the EQ predicate on the "payload_variant" field.
func PayloadVariantEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldPayloadVariant, v))
}

// PayloadVariantNEQ applies the NEQ predicate on the "payload_variant" field.
func PayloadVariantNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldPayloadVariant, v))
}

// PayloadVariantIn applies the In predicate on the "payload_variant" field.
func PayloadVariantIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldPayloadVariant, vs...))
}

// PayloadVariantNotIn applies the NotIn predicate on the "payload_variant" field.
func PayloadVariantNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldPayloadVariant, vs...))
}

// PayloadVariantGT applies the GT predicate on the "payload_variant" field.
func PayloadVariantGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldPayloadVariant, v))
}

// PayloadVariantGTE applies the GTE predicate on the "payload_variant" field.
func PayloadVariantGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldPayloadVariant, v))
}

// PayloadVariantLT applies the LT predicate on the "payload_variant" field.
func PayloadVariantLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldPayloadVariant, v))
}

// PayloadVariantLTE applies the LTE predicate on the "payload_variant" field.
func PayloadVariantLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldPayloadVariant, v))
}

// PayloadVariantContains applies the Contains predicate on the "payload_variant" field.
func PayloadVariantContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldPayloadVariant, v))
}

// PayloadVariantHasPrefix applies the HasPrefix predicate on the "payload_variant" field.
func PayloadVariantHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldPayloadVariant, v))
}

// PayloadVariantHasSuffix applies the HasSuffix predicate on the "payload_variant" field.
func PayloadVariantHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldPayloadVariant, v))
}

// PayloadVariantEqualFold applies the EqualFold predicate on the "payload_variant" field.
func PayloadVariantEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldPayloadVariant, v))
}

// PayloadVariantContainsFold applies the ContainsFold predicate on the "payload_variant" field.
func PayloadVariantContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldPayloadVariant, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldKey, v))
}

// ValueTypeEQ applies the EQ predicate on the "value_type" field.
func ValueTypeEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldValueType, v))
}

// ValueTypeNEQ applies the NEQ predicate on the "value_type" field.
func ValueTypeNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldValueType, v))
}

// ValueTypeIn applies the In predicate on the "value_type" field.
func ValueTypeIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldValueType, vs...))
}

// ValueTypeNotIn applies the NotIn predicate on the "value_type" field.
func ValueTypeNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldValueType, vs...))
}

// ValueTypeGT applies the GT predicate on the "value_type" field.
func ValueTypeGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldValueType, v))
}

// ValueTypeGTE applies the GTE predicate on the "value_type" field.
func ValueTypeGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldValueType, v))
}

// ValueTypeLT applies the LT predicate on the "value_type" field.
func ValueTypeLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldValueType, v))
}

// ValueTypeLTE applies the LTE predicate on the "value_type" field.
func ValueTypeLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldValueType, v))
}

// ValueTypeContains applies the Contains predicate on the "value_type" field.
func ValueTypeContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldValueType, v))
}

// ValueTypeHasPrefix applies the HasPrefix predicate on the "value_type" field.
func ValueTypeHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldValueType, v))
}

// ValueTypeHasSuffix applies the HasSuffix predicate on the "value_type" field.
func ValueTypeHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldValueType, v))
}

// ValueTypeEqualFold applies the EqualFold predicate on the "value_type" field.
func ValueTypeEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldValueType, v))
}

// ValueTypeContainsFold applies the ContainsFold predicate on the "value_type" field.
func ValueTypeContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldValueType, v))
}

// ItemsTypeEQ applies the EQ predicate on the "items_type" field.
func ItemsTypeEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldItemsType, v))
}

// ItemsTypeNEQ applies the NEQ predicate on the "items_type" field.
func ItemsTypeNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldItemsType, v))
}

// ItemsTypeIn applies the In predicate on the "items_type" field.
func ItemsTypeIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldItemsType, vs...))
}

// ItemsTypeNotIn applies the NotIn predicate on the "items_type" field.
func ItemsTypeNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldItemsType, vs...))
}

// ItemsTypeGT applies the GT predicate on the "items_type" field.
func ItemsTypeGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldItemsType, v))
}

// ItemsTypeGTE applies the GTE predicate on the "items_type" field.
func ItemsTypeGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldItemsType, v))
}

// ItemsTypeLT applies the LT predicate on the "items_type" field.
func ItemsTypeLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldItemsType, v))
}

// ItemsTypeLTE applies the LTE predicate on the "items_type" field.
func ItemsTypeLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldItemsType, v))
}

// ItemsTypeContains applies the Contains predicate on the "items_type" field.
func ItemsTypeContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldItemsType, v))
}

// ItemsTypeHasPrefix applies the HasPrefix predicate on the "items_type" field.
func ItemsTypeHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldItemsType, v))
}

// ItemsTypeHasSuffix applies the HasSuffix predicate on the "items_type" field.
func ItemsTypeHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldItemsType, v))
}

// ItemsTypeIsNil applies the IsNil predicate on the "items_type" field.
func ItemsTypeIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldItemsType))
}

// ItemsTypeNotNil applies the NotNil predicate on the "items_type" field.
func ItemsTypeNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldItemsType))
}

// ItemsTypeEqualFold applies the EqualFold predicate on the "items_type" field.
func ItemsTypeEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldItemsType, v))
}

// ItemsTypeContainsFold applies the ContainsFold predicate on the "items_type" field.
func ItemsTypeContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldItemsType, v))
}

// DefaultValueIsNil applies the IsNil predicate on the "default_value" field.
func DefaultValueIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldDefaultValue))
}

// DefaultValueNotNil applies the NotNil predicate on the "default_value" field.
func DefaultValueNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldDefaultValue))
}

// EnumValuesIsNil applies the IsNil predicate on the "enum_values" field.
func EnumValuesIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldEnumValues))
}

// EnumValuesNotNil applies the NotNil predicate on the "enum_values" field.
func EnumValuesNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldEnumValues))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "title" field.
func TitleIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "title" field.
func TitleNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldDescription, v))
}

// PresenceEQ applies the EQ predicate on the "presence" field.
func PresenceEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldPresence, v))
}

// PresenceNEQ applies the NEQ predicate on the "presence" field.
func PresenceNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldPresence, v))
}

// PresenceIn applies the In predicate on the "presence" field.
func PresenceIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldPresence, vs...))
}

// PresenceNotIn applies the NotIn predicate on the "presence" field.
func PresenceNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldPresence, vs...))
}

// PresenceGT applies the GT predicate on the "presence" field.
func PresenceGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldPresence, v))
}

// PresenceGTE applies the GTE predicate on the "presence" field.
func PresenceGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldPresence, v))
}

// PresenceLT applies the LT predicate on the "presence" field.
func PresenceLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldPresence, v))
}

// PresenceLTE applies the LTE predicate on the "presence" field.
func PresenceLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldPresence, v))
}

// PresenceContains applies the Contains predicate on the "presence" field.
func PresenceContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldPresence, v))
}

// PresenceHasPrefix applies the HasPrefix predicate on the "presence" field.
func PresenceHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldPresence, v))
}

// PresenceHasSuffix applies the HasSuffix predicate on the "presence" field.
func PresenceHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldPresence, v))
}

// PresenceEqualFold applies the EqualFold predicate on the "presence" field.
func PresenceEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldPresence, v))
}

// PresenceContainsFold applies the ContainsFold predicate on the "presence" field.
func PresenceContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldPresence, v))
}

// DeprecatedEQ applies the EQ predicate on the "deprecated" field.
func DeprecatedEQ(v bool) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldDeprecated, v))
}

// DeprecatedNEQ applies the NEQ predicate on the "deprecated" field.
func DeprecatedNEQ(v bool) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldDeprecated, v))
}

// IsNestedEQ applies the EQ predicate on the "is_nested" field.
func IsNestedEQ(v bool) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldIsNested, v))
}

// IsNestedNEQ applies the NEQ predicate on the "is_nested" field.
func IsNestedNEQ(v bool) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldIsNested, v))
}

// NestedReferenceEQ applies the EQ predicate on the "nested_reference" field.
func NestedReferenceEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldNestedReference, v))
}

// NestedReferenceNEQ applies the NEQ predicate on the "nested_reference" field.
func NestedReferenceNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldNestedReference, v))
}

// NestedReferenceIn applies the In predicate on the "nested_reference" field.
func NestedReferenceIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldNestedReference, vs...))
}

// NestedReferenceNotIn applies the NotIn predicate on the "nested_reference" field.
func NestedReferenceNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldNestedReference, vs...))
}

// NestedReferenceGT applies the GT predicate on the "nested_reference" field.
func NestedReferenceGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldNestedReference, v))
}

// NestedReferenceGTE applies the GTE predicate on the "nested_reference" field.
func NestedReferenceGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldNestedReference, v))
}

// NestedReferenceLT applies the LT predicate on the "nested_reference" field.
func NestedReferenceLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldNestedReference, v))
}

// NestedReferenceLTE applies the LTE predicate on the "nested_reference" field.
func NestedReferenceLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldNestedReference, v))
}

// NestedReferenceContains applies the Contains predicate on the "nested_reference" field.
func NestedReferenceContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldNestedReference, v))
}

// NestedReferenceHasPrefix applies the HasPrefix predicate on the "nested_reference" field.
func NestedReferenceHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldNestedReference, v))
}

// NestedReferenceHasSuffix applies the HasSuffix predicate on the "nested_reference" field.
func NestedReferenceHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldNestedReference, v))
}

// NestedReferenceIsNil applies the IsNil predicate on the "nested_reference" field.
func NestedReferenceIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldNestedReference))
}

// NestedReferenceNotNil applies the NotNil predicate on the "nested_reference" field.
func NestedReferenceNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldNestedReference))
}

// NestedReferenceEqualFold applies the EqualFold predicate on the "nested_reference" field.
func NestedReferenceEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldNestedReference, v))
}

// NestedReferenceContainsFold applies the ContainsFold predicate on the "nested_reference" field.
func NestedReferenceContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldNestedReference, v))
}

// ItemsReferenceEQ applies the EQ predicate on the "items_reference" field.
func ItemsReferenceEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldItemsReference, v))
}

// ItemsReferenceNEQ applies the NEQ predicate on the "items_reference" field.
func ItemsReferenceNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldItemsReference, v))
}

// ItemsReferenceIn applies the In predicate on the "items_reference" field.
func ItemsReferenceIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldItemsReference, vs...))
}

// ItemsReferenceNotIn applies the NotIn predicate on the "items_reference" field.
func ItemsReferenceNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldItemsReference, vs...))
}

// ItemsReferenceGT applies the GT predicate on the "items_reference" field.
func ItemsReferenceGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldItemsReference, v))
}

// ItemsReferenceGTE applies the GTE predicate on the "items_reference" field.
func ItemsReferenceGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldItemsReference, v))
}

// ItemsReferenceLT applies the LT predicate on the "items_reference" field.
func ItemsReferenceLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldItemsReference, v))
}

// ItemsReferenceLTE applies the LTE predicate on the "items_reference" field.
func ItemsReferenceLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldItemsReference, v))
}

// ItemsReferenceContains applies the Contains predicate on the "items_reference" field.
func ItemsReferenceContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldItemsReference, v))
}

// ItemsReferenceHasPrefix applies the HasPrefix predicate on the "items_reference" field.
func ItemsReferenceHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldItemsReference, v))
}

// ItemsReferenceHasSuffix applies the HasSuffix predicate on the "items_reference" field.
func ItemsReferenceHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldItemsReference, v))
}

// ItemsReferenceIsNil applies the IsNil predicate on the "items_reference" field.
func ItemsReferenceIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldItemsReference))
}

// ItemsReferenceNotNil applies the NotNil predicate on the "items_reference" field.
func ItemsReferenceNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldItemsReference))
}

// ItemsReferenceEqualFold applies the EqualFold predicate on the "items_reference" field.
func ItemsReferenceEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldItemsReference, v))
}

// ItemsReferenceContainsFold applies the ContainsFold predicate on the "items_reference" field.
func ItemsReferenceContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldItemsReference, v))
}

// SupportedOsIsNil applies the IsNil predicate on the "supported_os" field.
func SupportedOsIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldSupportedOs))
}

// SupportedOsNotNil applies the NotNil predicate on the "supported_os" field.
func SupportedOsNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldSupportedOs))
}

// ConditionsIsNil applies the IsNil predicate on the "conditions" field.
func ConditionsIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldConditions))
}

// ConditionsNotNil applies the NotNil predicate on the "conditions" field.
func ConditionsNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldConditions))
}

// OrderIndexEQ applies the EQ predicate on the "order_index" field.
func OrderIndexEQ(v int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldOrderIndex, v))
}

// OrderIndexNEQ applies the NEQ predicate on the "order_index" field.
func OrderIndexNEQ(v int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldOrderIndex, v))
}

// OrderIndexIn applies the In predicate on the "order_index" field.
func OrderIndexIn(vs ...int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldOrderIndex, vs...))
}

// OrderIndexNotIn applies the NotIn predicate on the "order_index" field.
func OrderIndexNotIn(vs ...int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldOrderIndex, vs...))
}

// OrderIndexGT applies the GT predicate on the "order_index" field.
func OrderIndexGT(v int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldOrderIndex, v))
}

// OrderIndexGTE applies the GTE predicate on the "order_index" field.
func OrderIndexGTE(v int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldOrderIndex, v))
}

// OrderIndexLT applies the LT predicate on the "order_index" field.
func OrderIndexLT(v int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldOrderIndex, v))
}

// OrderIndexLTE applies the LTE predicate on the "order_index" field.
func OrderIndexLTE(v int) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldOrderIndex, v))
}

// YamlSourceFileEQ applies the EQ predicate on the "yaml_source_file" field.
func YamlSourceFileEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldYamlSourceFile, v))
}

// YamlSourceFileNEQ applies the NEQ predicate on the "yaml_source_file" field.
func YamlSourceFileNEQ(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldYamlSourceFile, v))
}

// YamlSourceFileIn applies the In predicate on the "yaml_source_file" field.
func YamlSourceFileIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldYamlSourceFile, vs...))
}

// YamlSourceFileNotIn applies the NotIn predicate on the "yaml_source_file" field.
func YamlSourceFileNotIn(vs ...string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldYamlSourceFile, vs...))
}

// YamlSourceFileGT applies the GT predicate on the "yaml_source_file" field.
func YamlSourceFileGT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldYamlSourceFile, v))
}

// YamlSourceFileGTE applies the GTE predicate on the "yaml_source_file" field.
func YamlSourceFileGTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldYamlSourceFile, v))
}

// YamlSourceFileLT applies the LT predicate on the "yaml_source_file" field.
func YamlSourceFileLT(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldYamlSourceFile, v))
}

// YamlSourceFileLTE applies the LTE predicate on the "yaml_source_file" field.
func YamlSourceFileLTE(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldYamlSourceFile, v))
}

// YamlSourceFileContains applies the Contains predicate on the "yaml_source_file" field.
func YamlSourceFileContains(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContains(FieldYamlSourceFile, v))
}

// YamlSourceFileHasPrefix applies the HasPrefix predicate on the "yaml_source_file" field.
func YamlSourceFileHasPrefix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasPrefix(FieldYamlSourceFile, v))
}

// YamlSourceFileHasSuffix applies the HasSuffix predicate on the "yaml_source_file" field.
func YamlSourceFileHasSuffix(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldHasSuffix(FieldYamlSourceFile, v))
}

// YamlSourceFileIsNil applies the IsNil predicate on the "yaml_source_file" field.
func YamlSourceFileIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldYamlSourceFile))
}

// YamlSourceFileNotNil applies the NotNil predicate on the "yaml_source_file" field.
func YamlSourceFileNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldYamlSourceFile))
}

// YamlSourceFileEqualFold applies the EqualFold predicate on the "yaml_source_file" field.
func YamlSourceFileEqualFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEqualFold(FieldYamlSourceFile, v))
}

// YamlSourceFileContainsFold applies the ContainsFold predicate on the "yaml_source_file" field.
func YamlSourceFileContainsFold(v string) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldContainsFold(FieldYamlSourceFile, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.FieldNotNull(FieldDeletedAt))
}

// HasProperties applies the HasEdge predicate on the "properties" edge.
func HasProperties() predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PropertiesTable, PropertiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPropertiesWith applies the HasEdge predicate on the "properties" edge with a given conditions (other predicates).
func HasPropertiesWith(preds ...predicate.PayloadProperty) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(func(s *sql.Selector) {
		step := newPropertiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PayloadPropertyDefinition) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PayloadPropertyDefinition) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PayloadPropertyDefinition) predicate.PayloadPropertyDefinition {
	return predicate.PayloadPropertyDefinition(sql.NotPredicates(p))
}
