// Code generated by ent, DO NOT EDIT.

package appversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/thienel/go-backend-template/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLTE(FieldID, id))
}

// ApplicationID applies equality check predicate on the "application_id" field. It's identical to ApplicationIDEQ.
func ApplicationID(v uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldApplicationID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldVersion, v))
}

// BuildNumber applies equality check predicate on the "build_number" field. It's identical to BuildNumberEQ.
func BuildNumber(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldBuildNumber, v))
}

// MinimumOsVersion applies equality check predicate on the "minimum_os_version" field. It's identical to MinimumOsVersionEQ.
func MinimumOsVersion(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldMinimumOsVersion, v))
}

// FileURL applies equality check predicate on the "file_url" field. It's identical to FileURLEQ.
func FileURL(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldFileURL, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldSize, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// ApplicationIDEQ applies the EQ predicate on the "application_id" field.
func ApplicationIDEQ(v uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldApplicationID, v))
}

// ApplicationIDNEQ applies the NEQ predicate on the "application_id" field.
func ApplicationIDNEQ(v uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNEQ(FieldApplicationID, v))
}

// ApplicationIDIn applies the In predicate on the "application_id" field.
func ApplicationIDIn(vs ...uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldIn(FieldApplicationID, vs...))
}

// ApplicationIDNotIn applies the NotIn predicate on the "application_id" field.
func ApplicationIDNotIn(vs ...uint) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNotIn(FieldApplicationID, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldContainsFold(FieldVersion, v))
}

// BuildNumberEQ applies the EQ predicate on the "build_number" field.
func BuildNumberEQ(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldBuildNumber, v))
}

// BuildNumberNEQ applies the NEQ predicate on the "build_number" field.
func BuildNumberNEQ(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNEQ(FieldBuildNumber, v))
}

// BuildNumberIn applies the In predicate on the "build_number" field.
func BuildNumberIn(vs ...string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldIn(FieldBuildNumber, vs...))
}

// BuildNumberNotIn applies the NotIn predicate on the "build_number" field.
func BuildNumberNotIn(vs ...string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNotIn(FieldBuildNumber, vs...))
}

// BuildNumberGT applies the GT predicate on the "build_number" field.
func BuildNumberGT(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGT(FieldBuildNumber, v))
}

// BuildNumberGTE applies the GTE predicate on the "build_number" field.
func BuildNumberGTE(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGTE(FieldBuildNumber, v))
}

// BuildNumberLT applies the LT predicate on the "build_number" field.
func BuildNumberLT(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLT(FieldBuildNumber, v))
}

// BuildNumberLTE applies the LTE predicate on the "build_number" field.
func BuildNumberLTE(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLTE(FieldBuildNumber, v))
}

// BuildNumberContains applies the Contains predicate on the "build_number" field.
func BuildNumberContains(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldContains(FieldBuildNumber, v))
}

// BuildNumberHasPrefix applies the HasPrefix predicate on the "build_number" field.
func BuildNumberHasPrefix(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldHasPrefix(FieldBuildNumber, v))
}

// BuildNumberHasSuffix applies the HasSuffix predicate on the "build_number" field.
func BuildNumberHasSuffix(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldHasSuffix(FieldBuildNumber, v))
}

// BuildNumberEqualFold applies the EqualFold predicate on the "build_number" field.
func BuildNumberEqualFold(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEqualFold(FieldBuildNumber, v))
}

// BuildNumberContainsFold applies the ContainsFold predicate on the "build_number" field.
func BuildNumberContainsFold(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldContainsFold(FieldBuildNumber, v))
}

// MinimumOsVersionEQ applies the EQ predicate on the "minimum_os_version" field.
func MinimumOsVersionEQ(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldMinimumOsVersion, v))
}

// MinimumOsVersionNEQ applies the NEQ predicate on the "minimum_os_version" field.
func MinimumOsVersionNEQ(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNEQ(FieldMinimumOsVersion, v))
}

// MinimumOsVersionIn applies the In predicate on the "minimum_os_version" field.
func MinimumOsVersionIn(vs ...string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldIn(FieldMinimumOsVersion, vs...))
}

// MinimumOsVersionNotIn applies the NotIn predicate on the "minimum_os_version" field.
func MinimumOsVersionNotIn(vs ...string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNotIn(FieldMinimumOsVersion, vs...))
}

// MinimumOsVersionGT applies the GT predicate on the "minimum_os_version" field.
func MinimumOsVersionGT(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGT(FieldMinimumOsVersion, v))
}

// MinimumOsVersionGTE applies the GTE predicate on the "minimum_os_version" field.
func MinimumOsVersionGTE(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGTE(FieldMinimumOsVersion, v))
}

// MinimumOsVersionLT applies the LT predicate on the "minimum_os_version" field.
func MinimumOsVersionLT(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLT(FieldMinimumOsVersion, v))
}

// MinimumOsVersionLTE applies the LTE predicate on the "minimum_os_version" field.
func MinimumOsVersionLTE(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLTE(FieldMinimumOsVersion, v))
}

// MinimumOsVersionContains applies the Contains predicate on the "minimum_os_version" field.
func MinimumOsVersionContains(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldContains(FieldMinimumOsVersion, v))
}

// MinimumOsVersionHasPrefix applies the HasPrefix predicate on the "minimum_os_version" field.
func MinimumOsVersionHasPrefix(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldHasPrefix(FieldMinimumOsVersion, v))
}

// MinimumOsVersionHasSuffix applies the HasSuffix predicate on the "minimum_os_version" field.
func MinimumOsVersionHasSuffix(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldHasSuffix(FieldMinimumOsVersion, v))
}

// MinimumOsVersionIsNil applies the IsNil predicate on the "minimum_os_version" field.
func MinimumOsVersionIsNil() predicate.AppVersion {
	return predicate.AppVersion(sql.FieldIsNull(FieldMinimumOsVersion))
}

// MinimumOsVersionNotNil applies the NotNil predicate on the "minimum_os_version" field.
func MinimumOsVersionNotNil() predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNotNull(FieldMinimumOsVersion))
}

// MinimumOsVersionEqualFold applies the EqualFold predicate on the "minimum_os_version" field.
func MinimumOsVersionEqualFold(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEqualFold(FieldMinimumOsVersion, v))
}

// MinimumOsVersionContainsFold applies the ContainsFold predicate on the "minimum_os_version" field.
func MinimumOsVersionContainsFold(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldContainsFold(FieldMinimumOsVersion, v))
}

// FileURLEQ applies the EQ predicate on the "file_url" field.
func FileURLEQ(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldFileURL, v))
}

// FileURLNEQ applies the NEQ predicate on the "file_url" field.
func FileURLNEQ(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNEQ(FieldFileURL, v))
}

// FileURLIn applies the In predicate on the "file_url" field.
func FileURLIn(vs ...string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldIn(FieldFileURL, vs...))
}

// FileURLNotIn applies the NotIn predicate on the "file_url" field.
func FileURLNotIn(vs ...string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNotIn(FieldFileURL, vs...))
}

// FileURLGT applies the GT predicate on the "file_url" field.
func FileURLGT(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGT(FieldFileURL, v))
}

// FileURLGTE applies the GTE predicate on the "file_url" field.
func FileURLGTE(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGTE(FieldFileURL, v))
}

// FileURLLT applies the LT predicate on the "file_url" field.
func FileURLLT(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLT(FieldFileURL, v))
}

// FileURLLTE applies the LTE predicate on the "file_url" field.
func FileURLLTE(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLTE(FieldFileURL, v))
}

// FileURLContains applies the Contains predicate on the "file_url" field.
func FileURLContains(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldContains(FieldFileURL, v))
}

// FileURLHasPrefix applies the HasPrefix predicate on the "file_url" field.
func FileURLHasPrefix(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldHasPrefix(FieldFileURL, v))
}

// FileURLHasSuffix applies the HasSuffix predicate on the "file_url" field.
func FileURLHasSuffix(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldHasSuffix(FieldFileURL, v))
}

// FileURLIsNil applies the IsNil predicate on the "file_url" field.
func FileURLIsNil() predicate.AppVersion {
	return predicate.AppVersion(sql.FieldIsNull(FieldFileURL))
}

// FileURLNotNil applies the NotNil predicate on the "file_url" field.
func FileURLNotNil() predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNotNull(FieldFileURL))
}

// FileURLEqualFold applies the EqualFold predicate on the "file_url" field.
func FileURLEqualFold(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEqualFold(FieldFileURL, v))
}

// FileURLContainsFold applies the ContainsFold predicate on the "file_url" field.
func FileURLContainsFold(v string) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldContainsFold(FieldFileURL, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLTE(FieldSize, v))
}

// SizeIsNil applies the IsNil predicate on the "size" field.
func SizeIsNil() predicate.AppVersion {
	return predicate.AppVersion(sql.FieldIsNull(FieldSize))
}

// SizeNotNil applies the NotNil predicate on the "size" field.
func SizeNotNil() predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNotNull(FieldSize))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AppVersion {
	return predicate.AppVersion(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AppVersion {
	return predicate.AppVersion(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasApplication applies the HasEdge predicate on the "application" edge.
func HasApplication() predicate.AppVersion {
	return predicate.AppVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ApplicationTable, ApplicationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplicationWith applies the HasEdge predicate on the "application" edge with a given conditions (other predicates).
func HasApplicationWith(preds ...predicate.Application) predicate.AppVersion {
	return predicate.AppVersion(func(s *sql.Selector) {
		step := newApplicationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeployments applies the HasEdge predicate on the "deployments" edge.
func HasDeployments() predicate.AppVersion {
	return predicate.AppVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DeploymentsTable, DeploymentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeploymentsWith applies the HasEdge predicate on the "deployments" edge with a given conditions (other predicates).
func HasDeploymentsWith(preds ...predicate.AppDeployment) predicate.AppVersion {
	return predicate.AppVersion(func(s *sql.Selector) {
		step := newDeploymentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppVersion) predicate.AppVersion {
	return predicate.AppVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppVersion) predicate.AppVersion {
	return predicate.AppVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppVersion) predicate.AppVersion {
	return predicate.AppVersion(sql.NotPredicates(p))
}
